"""Saved/SelfTest/roads_oracle.json -> RoadsOracleFixture.inl (step 4)."""
import json
import os

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.normpath(os.path.join(HERE, '..', '..'))
SRC = os.path.join(ROOT, 'Saved', 'SelfTest', 'roads_oracle.json')
OUT = os.path.join(ROOT, 'Source', 'StacktownAlpha', 'Private', 'Tests',
                   'RoadsOracleFixture.inl')


def q(s):
    if s is None:
        return 'nullptr'
    return 'TEXT("%s")' % s.replace('\\', '\\\\').replace('"', '\\"')


def n(v):
    return repr(float(v))


def b(v):
    return 'true' if v else 'false'


def lotdef(l):
    if l is None:
        return '{ 0.0, 0.0, nullptr, nullptr }'
    return '{ %s, %s, %s, %s }' % (n(l['x0']), n(l['x1']), q(l['side']),
                                   q(l.get('road_id')))


def clickcase(c):
    return '{ %s, %s, %s, %s, %s, %s }' % (
        n(c['x']), n(c['y']), b(c['pins_active']), b(c['ok']), q(c['reason']),
        lotdef(c['lot']))


def segdef(s):
    if s is None:
        return '{ nullptr, 0.0, 0.0, 0.0, 0.0, nullptr }'
    return '{ %s, %s, %s, %s, %s, %s }' % (
        q(s['id']), n(s['start'][0]), n(s['start'][1]),
        n(s['end'][0]), n(s['end'][1]), q(s['width_class']))


def main():
    fx = json.load(open(SRC))
    L = []
    w = L.append
    w('// GENERATED by Tools/oracle/emit_roads_inl.py from the Python oracle.')
    w('// DO NOT HAND-EDIT - regenerate. Covers placement.py self-tests 28-48:')
    w('// the drawn-road half (Phase 1 step 4) and road types as mechanics.')
    w('//')
    w('//   python3 Tools/oracle/gen_roads_fixture.py')
    w('//   python3 Tools/oracle/emit_roads_inl.py')
    w('#pragma once')
    w('')
    w('namespace StacktownRoadsOracle')
    w('{')
    w('struct FSegDef { const TCHAR* Id; double StartX; double StartY;')
    w('                 double EndX; double EndY; const TCHAR* WidthClass; };')
    w('struct FDrawCase { double X0; double Y0; double X1; double Y1;')
    w('                   bool bPinsActive; bool bOk; const TCHAR* Reason; FSegDef Road; };')
    w('struct FRectDef { double XMin; double XMax; double YMin; double YMax; };')
    w('struct FLotDef2 { double X0; double X1; const TCHAR* Side; const TCHAR* RoadId; };')
    w('struct FClickCase2 { double X; double Y; bool bPinsActive; bool bOk;')
    w('                     const TCHAR* Reason; FLotDef2 Lot; };')
    w('struct FTypeRow { const TCHAR* Type; double CostPer100uu; double RentMult;')
    w('                  double Width; bool bFrontage; double Half; double MaxReach;')
    w('                  double Cost1400; const TCHAR* Material; };')
    w('struct FRentCase { const TCHAR* Own; const TCHAR* Highway; double Mult; };')
    w('')
    w('inline constexpr double MinRoadLength = %s;' % n(fx['MIN_ROAD_LENGTH']))
    w('// The balance every GEOMETRY case runs on. Roads cost money since road')
    w('// types, and a 1400 uu avenue is $140 against the $100 a fresh city')
    w('// starts with - so a case about geometry is given a balance that cannot')
    w('// be the reason it refuses. The price is tested on its own in 44.')
    w('inline constexpr double GeometryMoney = %s;' % n(fx['GEOMETRY_MONEY']))
    w('')

    w('// 28: lot_rect reduces to the old hard-coded constants for both built-ins.')
    for i, c in enumerate(fx['t28_lot_rect']):
        l = c['lot']
        w('inline const FLotDef2 T28_Lot%d = { %s, %s, %s, %s };' % (
            i, n(l['x0']), n(l['x1']), q(l['side']), q(l.get('road_id'))))
        w('inline const FRectDef T28_Rect%d = { %s, %s, %s, %s };' % (
            i, n(c['rect'][0]), n(c['rect'][1]), n(c['rect'][2]), n(c['rect'][3])))
    w('')

    w('// 29: side conventions READ OFF the segment geometry, not stored.')
    w('struct FOrientCase { FSegDef Seg; const TCHAR* SidePlus; const TCHAR* SideMinus; bool bAxisX; };')
    w('inline const FOrientCase T29Orientation[] = {')
    for c in fx['t29_road_dict']:
        w('\t{ %s, %s, %s, %s },' % (segdef(c['segment']), q(c['side_plus']),
                                     q(c['side_minus']), b(c['axis'] == 'x')))
    w('};')
    w('inline constexpr int32 T29OrientationNum = %d;' % len(fx['t29_road_dict']))
    w('')

    w('// 30: the built-ins, plus whatever has been drawn.')
    t30 = fx['t30_all_roads']
    w('inline const TCHAR* const T30_Before[] = { %s };'
      % ', '.join(q(i) for i in t30['before']))
    w('inline constexpr int32 T30_BeforeNum = %d;' % len(t30['before']))
    w('inline const TCHAR* const T30_After[] = { %s };'
      % ', '.join(q(i) for i in t30['after']))
    w('inline constexpr int32 T30_AfterNum = %d;' % len(t30['after']))
    w('inline const FSegDef T30_Drawn = %s;' % segdef(t30['drawn']))
    w('')

    w('// 31-37: every accept and every named refusal.')
    for key, name in (('t31_happy_horizontal', 'T31'), ('t32_too_diagonal', 'T32'),
                      ('t33_too_short', 'T33'), ('t34_off_board', 'T34'),
                      ('t35_crosses_builtin', 'T35'), ('t36_crosses_pin', 'T36'),
                      ('t36b_empty_mode', 'T36b'), ('t37_happy_vertical', 'T37')):
        c = fx[key]
        w('inline const FDrawCase %s = { %s, %s, %s, %s, %s, %s, %s, %s };' % (
            name, n(c['x0']), n(c['y0']), n(c['x1']), n(c['y1']),
            b(c['pins_active']), b(c['ok']), q(c['reason']), segdef(c['road'])))
    w('')

    w('// ADDED BY THE PORT: a near-axis drag snaps its minor coordinate to the')
    w('// START point. Every accepted road in 28-39 has equal ends, so nothing')
    w('// there separates start from end.')
    for key, name in (('near_horizontal', 'NearHorizontal'), ('near_vertical', 'NearVertical')):
        c = fx[key]
        w('inline const FDrawCase %s = { %s, %s, %s, %s, %s, %s, %s, %s };' % (
            name, n(c['x0']), n(c['y0']), n(c['x1']), n(c['y1']),
            b(c['pins_active']), b(c['ok']), q(c['reason']), segdef(c['road'])))
    w('')
    w('// 38: draw_road end to end, R1 then R2, and a refusal naming R1 itself.')
    t38 = fx['t38_draw_road']
    w('inline const TCHAR* const T38_FirstId = %s;' % q(t38['first']['id']))
    w('inline const FSegDef T38_FirstStored = %s;' % segdef(t38['first']['stored']))
    w('inline const TCHAR* const T38_SecondId = %s;' % q(t38['second']['id']))
    w('inline const FSegDef T38_SecondStored = %s;' % segdef(t38['second']['stored']))
    cr = t38['crosses_r1']
    w('inline const FDrawCase T38_CrossesR1 = { %s, %s, %s, %s, %s, %s, %s, %s };' % (
        n(cr['x0']), n(cr['y0']), n(cr['x1']), n(cr['y1']),
        b(cr['pins_active']), b(cr['ok']), q(cr['reason']), segdef(cr['road'])))
    w('inline const TCHAR* const T38_Ids[] = { %s };'
      % ', '.join(q(i) for i in t38['ids']))
    w('inline constexpr int32 T38_IdsNum = %d;' % len(t38['ids']))
    w('')

    w('// 39: a lot placed AGAINST a drawn road, through place() itself.')
    t39 = fx['t39_place_against_drawn']
    w('inline const FSegDef T39_Drawn = %s;' % segdef(t39['drawn']))
    w('inline constexpr double T39_ClickX = %s;' % n(t39['click'][0]))
    w('inline constexpr double T39_ClickY = %s;' % n(t39['click'][1]))
    w('inline const TCHAR* const T39_Pid = %s;' % q(t39['pid']))
    w('inline constexpr bool T39_Ok = %s;' % b(t39['ok']))
    l = t39['lot']
    w('inline const FLotDef2 T39_Lot = { %s, %s, %s, %s };' % (
        n(l['x0']), n(l['x1']), q(l['side']), q(l.get('road_id'))))
    w('inline const FRectDef T39_Rect = { %s, %s, %s, %s };' % (
        n(t39['rect'][0]), n(t39['rect'][1]), n(t39['rect'][2]), n(t39['rect'][3])))
    w('')
    w('// ---- ROAD TYPES AS MECHANICS, self-tests 40-48 -----------------------')
    w('// MONDAY_DECISIONS section 2. Every number below came out of the oracle')
    w('// running these exact scenarios; none of it was retyped.')
    w('inline constexpr double Verge = %s;' % n(fx['VERGE']))
    w('inline constexpr double HighwayReach = %s;' % n(fx['road_highway_reach']))
    w('// Named apart from Stacktown::DefaultRoadType()/RoadTypeNames() on purpose:')
    w('// a test brings both namespaces in, and the point is to COMPARE them.')
    w('inline const TCHAR* const OracleDefaultType = %s;' % q(fx['DEFAULT_ROAD_TYPE']))
    w('inline const TCHAR* const OracleTypeNames[] = { %s };'
      % ', '.join(q(t) for t in fx['ROAD_TYPES']))
    w('inline constexpr int32 OracleTypeNamesNum = %d;' % len(fx['ROAD_TYPES']))
    w('')
    w('// 40/41: the per-type table as the oracle computes it.')
    w('inline const FTypeRow T40_Types[] = {')
    for t in fx['t40_types']:
        w('\t{ %s, %s, %s, %s, %s, %s, %s, %s, %s },' % (
            q(t['type']), n(t['cost_per_100uu']), n(t['rent_mult']), n(t['width']),
            b(t['frontage']), n(t['half']), n(t['max_reach']), n(t['cost_1400']),
            q(t['material'])))
    w('};')
    w('inline constexpr int32 T40_TypesNum = %d;' % len(fx['t40_types']))
    w('// A road with NO width class - both built-ins - IS the avenue.')
    w('inline constexpr double T40_UntypedHalf = %s;' % n(fx['t40_untyped_half']))
    w('inline constexpr double T40_UntypedReach = %s;' % n(fx['t40_untyped_reach']))
    w('// A vertical 1400 uu run prices identically to a horizontal one.')
    w('inline const FSegDef T41_VerticalSeg = %s;' % segdef(fx['t41_length'][0]['seg']))
    w('inline constexpr double T41_VerticalLength = %s;' % n(fx['t41_length'][0]['length']))
    w('inline const FSegDef T41_ShortDirtSeg = %s;' % segdef(fx['t41_length'][1]['seg']))
    w('inline constexpr double T41_ShortDirtCost = %s;' % n(fx['t41_length'][1]['cost']))
    w('')
    w('// 42: the highway refuses frontage. The SAME segment drawn as each type.')
    t42 = fx['t42_frontage']
    w('inline constexpr double T42_Seg[] = { %s };'
      % ', '.join(n(v) for v in t42['segment']))
    w('inline const FSegDef T42_HighwayStored = %s;' % segdef(t42['highway_drawn']['stored']))
    w('inline constexpr double T42_MoneyAfterHighway = %s;' % n(t42['highway_drawn']['money_after']))
    for key, name in (('click_beside_highway', 'T42_BesideHighway'),
                      ('click_beside_avenue', 'T42_BesideAvenue'),
                      ('far_from_everything', 'T42_FarFromEverything')):
        w('inline const FClickCase2 %s = %s;' % (name, clickcase(t42[key])))
    w('')
    w('// 43: and nothing may be LAID ACROSS one.')
    t43 = fx['t43_across_highway']
    w('inline const FClickCase2 T43_WithHighway = %s;' % clickcase(t43['with_highway']))
    w('inline const FClickCase2 T43_Without = %s;' % clickcase(t43['without']))
    w('')
    w('// 44: roads cost money, on a state left at money_start deliberately.')
    t44 = fx['t44_afford']
    c = t44['avenue_refused']
    w('inline constexpr double T44_MoneyStart = %s;' % n(t44['money_start']))
    w('inline const FDrawCase T44_AvenueRefused = { %s, %s, %s, %s, %s, %s, %s, %s };' % (
        n(c['x0']), n(c['y0']), n(c['x1']), n(c['y1']),
        b(c['pins_active']), b(c['ok']), q(c['reason']), segdef(c['road'])))
    w('inline const TCHAR* const T44_AvenueClass = %s;' % q(c['width_class']))
    w('inline constexpr double T44_MoneyAfterRefusal = %s;' % n(t44['refusal_spends_nothing']))
    w('inline const FSegDef T44_DirtStored = %s;' % segdef(t44['dirt']['stored']))
    w('inline constexpr double T44_MoneyAfter = %s;' % n(t44['money_after']))
    w('')
    w('// 45: a narrower road pulls its own frontage line in.')
    t45 = fx['t45_dirt_frontage']
    w('inline const FRectDef T45_DirtRoadRect = { %s, %s, %s, %s };'
      % tuple(n(v) for v in t45['road_rect']))
    w('inline constexpr double T45_ClickX = %s;' % n(t45['click'][0]))
    w('inline constexpr double T45_ClickY = %s;' % n(t45['click'][1]))
    l = t45['lot']
    w('inline const FLotDef2 T45_Lot = { %s, %s, %s, %s };'
      % (n(l['x0']), n(l['x1']), q(l['side']), q(l.get('road_id'))))
    w('inline const FRectDef T45_LotRect = { %s, %s, %s, %s };'
      % tuple(n(v) for v in t45['rect']))
    w('')
    w('// 46: the rent multiplier - own type, then the highway proximity bonus,')
    w('// which MULTIPLIES, measured pavement to pad and bounded at 2,000 uu.')
    l = fx['t46_lot']
    w('inline const FLotDef2 T46_Lot = { %s, %s, %s, %s };'
      % (n(l['x0']), n(l['x1']), q(l['side']), q(l['road_id'])))
    w('inline const FRectDef T46_DirtLotRect = { %s, %s, %s, %s };'
      % tuple(n(v) for v in fx['t46_dirt_lot_rect']))
    w('inline constexpr double T46_FarDistance = %s;' % n(fx['t46_far_distance']))
    for c in fx['t46_rent']:
        if c['highway']:
            w('inline const FSegDef T46_%sHighway = %s;'
              % (c['highway'].capitalize(), segdef(c['highway_seg'])))
    w('inline const FRentCase T46_Cases[] = {')
    for c in fx['t46_rent']:
        w('\t{ %s, %s, %s },' % (q(c['own']), q(c['highway']), n(c['mult'])))
    w('};')
    w('inline constexpr int32 T46_CasesNum = %d;' % len(fx['t46_rent']))
    w('')
    w('// 47: an unrecognised type is refused at the boundary, with a reason.')
    c = fx['t47_unknown']
    w('inline const TCHAR* const T47_Class = %s;' % q(c['width_class']))
    w('inline const FDrawCase T47_Unknown = { %s, %s, %s, %s, %s, %s, %s, %s };' % (
        n(c['x0']), n(c['y0']), n(c['x1']), n(c['y1']),
        b(c['pins_active']), b(c['ok']), q(c['reason']), segdef(c['road'])))
    w('')
    w('// 48: _in_crossing measures each road\'s OWN pavement.')
    t48 = fx['t48_in_crossing']
    w('inline constexpr double T48_X = %s;' % n(t48['point'][0]))
    w('inline constexpr double T48_Y = %s;' % n(t48['point'][1]))
    w('inline const FSegDef T48_Segment = %s;' % segdef(t48['segment']))
    w('inline constexpr bool T48_Highway = %s;' % b(t48['highway']))
    w('inline constexpr bool T48_Avenue = %s;' % b(t48['avenue']))
    w('inline constexpr bool T48_BuiltinsAtOrigin = %s;' % b(t48['builtins_at_origin']))
    w('')
    w('} // namespace StacktownRoadsOracle')

    with open(OUT, 'w') as f:
        f.write('\n'.join(L) + '\n')
    print('wrote %s (%d lines)' % (os.path.relpath(OUT, ROOT), len(L)))


if __name__ == '__main__':
    main()
