"""Saved/SelfTest/roads_oracle.json -> RoadsOracleFixture.inl (step 4)."""
import json
import os

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.normpath(os.path.join(HERE, '..', '..'))
SRC = os.path.join(ROOT, 'Saved', 'SelfTest', 'roads_oracle.json')
OUT = os.path.join(ROOT, 'Source', 'StacktownAlpha', 'Private', 'Tests',
                   'RoadsOracleFixture.inl')


def q(s):
    if s is None:
        return 'nullptr'
    return 'TEXT("%s")' % s.replace('\\', '\\\\').replace('"', '\\"')


def n(v):
    return repr(float(v))


def b(v):
    return 'true' if v else 'false'


def lotdef(l):
    if l is None:
        return '{ 0.0, 0.0, nullptr, nullptr }'
    return '{ %s, %s, %s, %s }' % (n(l['x0']), n(l['x1']), q(l['side']),
                                   q(l.get('road_id')))


def clickcase(c):
    return '{ %s, %s, %s, %s, %s, %s }' % (
        n(c['x']), n(c['y']), b(c['pins_active']), b(c['ok']), q(c['reason']),
        lotdef(c['lot']))


def segdef(s):
    if s is None:
        return '{ nullptr, 0.0, 0.0, 0.0, 0.0, nullptr, nullptr }'
    return '{ %s, %s, %s, %s, %s, %s, %s }' % (
        q(s['id']), n(s['start'][0]), n(s['start'][1]),
        n(s['end'][0]), n(s['end'][1]), q(s['width_class']),
        q(s.get('path') or None))


def main():
    fx = json.load(open(SRC))
    L = []
    w = L.append
    w('// GENERATED by Tools/oracle/emit_roads_inl.py from the Python oracle.')
    w('// DO NOT HAND-EDIT - regenerate. Covers placement.py self-tests 28-48:')
    w('// the drawn-road half (Phase 1 step 4) and road types as mechanics.')
    w('//')
    w('//   python3 Tools/oracle/gen_roads_fixture.py')
    w('//   python3 Tools/oracle/emit_roads_inl.py')
    w('#pragma once')
    w('')
    w('namespace StacktownRoadsOracle')
    w('{')
    w('struct FSegDef { const TCHAR* Id; double StartX; double StartY;')
    w('                 double EndX; double EndY; const TCHAR* WidthClass;')
    w('                 const TCHAR* Path; };')
    w('struct FDrawCase { double X0; double Y0; double X1; double Y1;')
    w('                   bool bPinsActive; bool bOk; const TCHAR* Reason; FSegDef Road; };')
    w('struct FRectDef { double XMin; double XMax; double YMin; double YMax; };')
    w('struct FLotDef2 { double X0; double X1; const TCHAR* Side; const TCHAR* RoadId; };')
    w('struct FClickCase2 { double X; double Y; bool bPinsActive; bool bOk;')
    w('                     const TCHAR* Reason; FLotDef2 Lot; };')
    w('struct FTypeRow { const TCHAR* Type; double CostPer100uu; double RentMult;')
    w('                  double Width; bool bFrontage; double Half; double MaxReach;')
    w('                  double Cost1400; const TCHAR* Material; };')
    w('struct FRentCase { const TCHAR* Own; const TCHAR* Highway; double Mult; };')
    w('')
    w('inline constexpr double MinRoadLength = %s;' % n(fx['MIN_ROAD_LENGTH']))
    w('// The balance every GEOMETRY case runs on. Roads cost money since road')
    w('// types, and a 1400 uu avenue is $140 against the $100 a fresh city')
    w('// starts with - so a case about geometry is given a balance that cannot')
    w('// be the reason it refuses. The price is tested on its own in 44.')
    w('inline constexpr double GeometryMoney = %s;' % n(fx['GEOMETRY_MONEY']))
    w('')

    w('// 28: lot_rect reduces to the old hard-coded constants for both built-ins.')
    for i, c in enumerate(fx['t28_lot_rect']):
        l = c['lot']
        w('inline const FLotDef2 T28_Lot%d = { %s, %s, %s, %s };' % (
            i, n(l['x0']), n(l['x1']), q(l['side']), q(l.get('road_id'))))
        w('inline const FRectDef T28_Rect%d = { %s, %s, %s, %s };' % (
            i, n(c['rect'][0]), n(c['rect'][1]), n(c['rect'][2]), n(c['rect'][3])))
    w('')

    w('// 29: side conventions READ OFF the segment geometry, not stored.')
    w('struct FOrientCase { FSegDef Seg; const TCHAR* SidePlus; const TCHAR* SideMinus; bool bAxisX; };')
    w('inline const FOrientCase T29Orientation[] = {')
    for c in fx['t29_road_dict']:
        w('\t{ %s, %s, %s, %s },' % (segdef(c['segment']), q(c['side_plus']),
                                     q(c['side_minus']), b(c['axis'] == 'x')))
    w('};')
    w('inline constexpr int32 T29OrientationNum = %d;' % len(fx['t29_road_dict']))
    w('')

    w('// 30: the built-ins, plus whatever has been drawn.')
    t30 = fx['t30_all_roads']
    w('inline const TCHAR* const T30_Before[] = { %s };'
      % ', '.join(q(i) for i in t30['before']))
    w('inline constexpr int32 T30_BeforeNum = %d;' % len(t30['before']))
    w('inline const TCHAR* const T30_After[] = { %s };'
      % ', '.join(q(i) for i in t30['after']))
    w('inline constexpr int32 T30_AfterNum = %d;' % len(t30['after']))
    w('inline const FSegDef T30_Drawn = %s;' % segdef(t30['drawn']))
    w('')

    w('// 31-37: every accept and every named refusal.')
    for key, name in (('t31_happy_horizontal', 'T31'), ('t32_too_diagonal', 'T32'),
                      ('t33_too_short', 'T33'), ('t34_off_board', 'T34'),
                      ('t35_crosses_builtin', 'T35'), ('t36_crosses_pin', 'T36'),
                      ('t36b_empty_mode', 'T36b'), ('t37_happy_vertical', 'T37')):
        c = fx[key]
        w('inline const FDrawCase %s = { %s, %s, %s, %s, %s, %s, %s, %s };' % (
            name, n(c['x0']), n(c['y0']), n(c['x1']), n(c['y1']),
            b(c['pins_active']), b(c['ok']), q(c['reason']), segdef(c['road'])))
    w('')

    w('// ADDED BY THE PORT: a near-axis drag snaps its minor coordinate to the')
    w('// START point. Every accepted road in 28-39 has equal ends, so nothing')
    w('// there separates start from end.')
    for key, name in (('near_horizontal', 'NearHorizontal'), ('near_vertical', 'NearVertical')):
        c = fx[key]
        w('inline const FDrawCase %s = { %s, %s, %s, %s, %s, %s, %s, %s };' % (
            name, n(c['x0']), n(c['y0']), n(c['x1']), n(c['y1']),
            b(c['pins_active']), b(c['ok']), q(c['reason']), segdef(c['road'])))
    w('')
    w('// 38: draw_road end to end, R1 then R2, and a refusal naming R1 itself.')
    t38 = fx['t38_draw_road']
    w('inline const TCHAR* const T38_FirstId = %s;' % q(t38['first']['id']))
    w('inline const FSegDef T38_FirstStored = %s;' % segdef(t38['first']['stored']))
    w('inline const TCHAR* const T38_SecondId = %s;' % q(t38['second']['id']))
    w('inline const FSegDef T38_SecondStored = %s;' % segdef(t38['second']['stored']))
    cr = t38['crosses_r1']
    w('inline const FDrawCase T38_CrossesR1 = { %s, %s, %s, %s, %s, %s, %s, %s };' % (
        n(cr['x0']), n(cr['y0']), n(cr['x1']), n(cr['y1']),
        b(cr['pins_active']), b(cr['ok']), q(cr['reason']), segdef(cr['road'])))
    w('inline const TCHAR* const T38_Ids[] = { %s };'
      % ', '.join(q(i) for i in t38['ids']))
    w('inline constexpr int32 T38_IdsNum = %d;' % len(t38['ids']))
    w('')

    w('// 39: a lot placed AGAINST a drawn road, through place() itself.')
    t39 = fx['t39_place_against_drawn']
    w('inline const FSegDef T39_Drawn = %s;' % segdef(t39['drawn']))
    w('inline constexpr double T39_ClickX = %s;' % n(t39['click'][0]))
    w('inline constexpr double T39_ClickY = %s;' % n(t39['click'][1]))
    w('inline const TCHAR* const T39_Pid = %s;' % q(t39['pid']))
    w('inline constexpr bool T39_Ok = %s;' % b(t39['ok']))
    l = t39['lot']
    w('inline const FLotDef2 T39_Lot = { %s, %s, %s, %s };' % (
        n(l['x0']), n(l['x1']), q(l['side']), q(l.get('road_id'))))
    w('inline const FRectDef T39_Rect = { %s, %s, %s, %s };' % (
        n(t39['rect'][0]), n(t39['rect'][1]), n(t39['rect'][2]), n(t39['rect'][3])))
    w('')
    w('// ---- ROAD TYPES AS MECHANICS, self-tests 40-48 -----------------------')
    w('// MONDAY_DECISIONS section 2. Every number below came out of the oracle')
    w('// running these exact scenarios; none of it was retyped.')
    w('inline constexpr double Verge = %s;' % n(fx['VERGE']))
    w('inline constexpr double HighwayReach = %s;' % n(fx['road_highway_reach']))
    w('// Named apart from Stacktown::DefaultRoadType()/RoadTypeNames() on purpose:')
    w('// a test brings both namespaces in, and the point is to COMPARE them.')
    w('inline const TCHAR* const OracleDefaultType = %s;' % q(fx['DEFAULT_ROAD_TYPE']))
    w('inline const TCHAR* const OracleTypeNames[] = { %s };'
      % ', '.join(q(t) for t in fx['ROAD_TYPES']))
    w('inline constexpr int32 OracleTypeNamesNum = %d;' % len(fx['ROAD_TYPES']))
    w('')
    w('// 40/41: the per-type table as the oracle computes it.')
    w('inline const FTypeRow T40_Types[] = {')
    for t in fx['t40_types']:
        w('\t{ %s, %s, %s, %s, %s, %s, %s, %s, %s },' % (
            q(t['type']), n(t['cost_per_100uu']), n(t['rent_mult']), n(t['width']),
            b(t['frontage']), n(t['half']), n(t['max_reach']), n(t['cost_1400']),
            q(t['material'])))
    w('};')
    w('inline constexpr int32 T40_TypesNum = %d;' % len(fx['t40_types']))
    w('// A road with NO width class - both built-ins - IS the avenue.')
    w('inline constexpr double T40_UntypedHalf = %s;' % n(fx['t40_untyped_half']))
    w('inline constexpr double T40_UntypedReach = %s;' % n(fx['t40_untyped_reach']))
    w('// A vertical 1400 uu run prices identically to a horizontal one.')
    w('inline const FSegDef T41_VerticalSeg = %s;' % segdef(fx['t41_length'][0]['seg']))
    w('inline constexpr double T41_VerticalLength = %s;' % n(fx['t41_length'][0]['length']))
    w('inline const FSegDef T41_ShortDirtSeg = %s;' % segdef(fx['t41_length'][1]['seg']))
    w('inline constexpr double T41_ShortDirtCost = %s;' % n(fx['t41_length'][1]['cost']))
    w('')
    w('// 42: the highway refuses frontage. The SAME segment drawn as each type.')
    t42 = fx['t42_frontage']
    w('inline constexpr double T42_Seg[] = { %s };'
      % ', '.join(n(v) for v in t42['segment']))
    w('inline const FSegDef T42_HighwayStored = %s;' % segdef(t42['highway_drawn']['stored']))
    w('inline constexpr double T42_MoneyAfterHighway = %s;' % n(t42['highway_drawn']['money_after']))
    for key, name in (('click_beside_highway', 'T42_BesideHighway'),
                      ('click_beside_avenue', 'T42_BesideAvenue'),
                      ('far_from_everything', 'T42_FarFromEverything')):
        w('inline const FClickCase2 %s = %s;' % (name, clickcase(t42[key])))
    w('')
    w('// 43: and nothing may be LAID ACROSS one.')
    t43 = fx['t43_across_highway']
    w('inline const FClickCase2 T43_WithHighway = %s;' % clickcase(t43['with_highway']))
    w('inline const FClickCase2 T43_Without = %s;' % clickcase(t43['without']))
    w('')
    w('// 44: roads cost money, on a state left at money_start deliberately.')
    t44 = fx['t44_afford']
    c = t44['avenue_refused']
    w('inline constexpr double T44_MoneyStart = %s;' % n(t44['money_start']))
    w('inline const FDrawCase T44_AvenueRefused = { %s, %s, %s, %s, %s, %s, %s, %s };' % (
        n(c['x0']), n(c['y0']), n(c['x1']), n(c['y1']),
        b(c['pins_active']), b(c['ok']), q(c['reason']), segdef(c['road'])))
    w('inline const TCHAR* const T44_AvenueClass = %s;' % q(c['width_class']))
    w('inline constexpr double T44_MoneyAfterRefusal = %s;' % n(t44['refusal_spends_nothing']))
    w('inline const FSegDef T44_DirtStored = %s;' % segdef(t44['dirt']['stored']))
    w('inline constexpr double T44_MoneyAfter = %s;' % n(t44['money_after']))
    w('')
    w('// 45: a narrower road pulls its own frontage line in.')
    t45 = fx['t45_dirt_frontage']
    w('inline const FRectDef T45_DirtRoadRect = { %s, %s, %s, %s };'
      % tuple(n(v) for v in t45['road_rect']))
    w('// 45 draws its OWN road: it places a lot, so it moved north when a lot')
    w('// stopped being allowed to overlap the arterial\'s corridor; 44 is')
    w('// about the price and stayed where it was.')
    w('inline constexpr double T45_Road[4] = { %s };'
      % ', '.join(n(v) for v in t45['road']))
    w('inline constexpr double T45_ClickX = %s;' % n(t45['click'][0]))
    w('inline constexpr double T45_ClickY = %s;' % n(t45['click'][1]))
    l = t45['lot']
    w('inline const FLotDef2 T45_Lot = { %s, %s, %s, %s };'
      % (n(l['x0']), n(l['x1']), q(l['side']), q(l.get('road_id'))))
    w('inline const FRectDef T45_LotRect = { %s, %s, %s, %s };'
      % tuple(n(v) for v in t45['rect']))
    w('')
    w('// 46: the rent multiplier - own type, then the highway proximity bonus,')
    w('// which MULTIPLIES, measured pavement to pad and bounded at 2,000 uu.')
    l = fx['t46_lot']
    w('inline const FLotDef2 T46_Lot = { %s, %s, %s, %s };'
      % (n(l['x0']), n(l['x1']), q(l['side']), q(l['road_id'])))
    w('inline const FRectDef T46_DirtLotRect = { %s, %s, %s, %s };'
      % tuple(n(v) for v in fx['t46_dirt_lot_rect']))
    w('inline constexpr double T46_FarDistance = %s;' % n(fx['t46_far_distance']))
    for c in fx['t46_rent']:
        if c['highway']:
            w('inline const FSegDef T46_%sHighway = %s;'
              % (c['highway'].capitalize(), segdef(c['highway_seg'])))
    w('inline const FRentCase T46_Cases[] = {')
    for c in fx['t46_rent']:
        w('\t{ %s, %s, %s },' % (q(c['own']), q(c['highway']), n(c['mult'])))
    w('};')
    w('inline constexpr int32 T46_CasesNum = %d;' % len(fx['t46_rent']))
    w('')
    w('// 47: an unrecognised type is refused at the boundary, with a reason.')
    c = fx['t47_unknown']
    w('inline const TCHAR* const T47_Class = %s;' % q(c['width_class']))
    w('inline const FDrawCase T47_Unknown = { %s, %s, %s, %s, %s, %s, %s, %s };' % (
        n(c['x0']), n(c['y0']), n(c['x1']), n(c['y1']),
        b(c['pins_active']), b(c['ok']), q(c['reason']), segdef(c['road'])))
    w('')
    w('// 48: _in_crossing measures each road\'s OWN pavement.')
    t48 = fx['t48_in_crossing']
    w('inline constexpr double T48_X = %s;' % n(t48['point'][0]))
    w('inline constexpr double T48_Y = %s;' % n(t48['point'][1]))
    w('inline const FSegDef T48_Segment = %s;' % segdef(t48['segment']))
    w('inline constexpr bool T48_Highway = %s;' % b(t48['highway']))
    w('inline constexpr bool T48_Avenue = %s;' % b(t48['avenue']))
    w('inline constexpr bool T48_BuiltinsAtOrigin = %s;' % b(t48['builtins_at_origin']))
    w('')
    w('// 49: which way the player dragged must not matter. ONE expected answer')
    w('// per case and two drag orders as inputs - a fixture with two answers')
    w('// would be recording the bug rather than the fix.')
    w('struct FDragCase { double FX0; double FY0; double FX1; double FY1;')
    w('                   double ClickX; double ClickY; FSegDef Segment;')
    w('                   FLotDef2 Lot; double Money; };')
    w('inline const FDragCase T49_Drag[] = {')
    for c in fx['t49_drag_direction']:
        l = c['lot']
        w('\t{ %s, %s, %s, %s, %s, %s, %s, %s, %s },' % (
            n(c['forward'][0][0]), n(c['forward'][0][1]),
            n(c['forward'][1][0]), n(c['forward'][1][1]),
            n(c['click'][0]), n(c['click'][1]), segdef(c['segment']),
            lotdef(l), n(c['money'])))
    w('};')
    w('inline constexpr int32 T49_DragNum = %d;' % len(fx['t49_drag_direction']))
    w('')
    w('// ---- ROADS AT ANY DIRECTION, self-tests 50-55 (item 11) --------------')
    w('struct FQuadPair { FLotDef2 A; FLotDef2 B; bool bQuads; bool bRects; };')
    w('struct FProjRow  { double World; double X; double Y; double Along; };')
    w('struct FProjCase { const TCHAR* Road; double S0; double Length;')
    w('                   double Ux; double Uy; double Nx; double Ny;')
    w('                   FProjRow Points[5]; };')
    w('struct FSideRow  { const TCHAR* Label; double StartX; double StartY;')
    w('                   double EndX; double EndY; const TCHAR* Plus;')
    w('                   const TCHAR* Minus; bool bAxisX; double Nx; double Ny; };')
    w('struct FQuadDef  { double X[4]; double Y[4]; };')
    w('')
    c = fx['t32b_diagonal_draws']
    w('// 32b/33b: a diagonal DRAWS now, and is measured along its centreline.')
    w('inline const FDrawCase T32b_Diagonal = { %s, %s, %s, %s, %s, %s, %s, %s };' % (
        n(c['x0']), n(c['y0']), n(c['x1']), n(c['y1']),
        b(c['pins_active']), b(c['ok']), q(c['reason']), segdef(c['road'])))
    c = fx['t33b_diagonal_too_short']
    w('inline const FDrawCase T33b_DiagonalTooShort = { %s, %s, %s, %s, %s, %s, %s, %s };' % (
        n(c['x0']), n(c['y0']), n(c['x1']), n(c['y1']),
        b(c['pins_active']), b(c['ok']), q(c['reason']), segdef(c['road'])))
    w('')
    w('// 50: QuadsOverlap against RectsOverlap on real axis-aligned lot pairs.')
    w('inline const FQuadPair T50_Pairs[] = {')
    for p in fx['t50_quad_vs_rect']:
        w('\t{ %s, %s, %s, %s },' % (lotdef(p['a']), lotdef(p['b']),
                                     b(p['quads']), b(p['rects'])))
    w('};')
    w('inline constexpr int32 T50_PairsNum = %d;' % len(fx['t50_quad_vs_rect']))
    w('')
    w('// 51: the projection identity - S0 + Along IS the world coordinate for')
    w('// both built-ins, which is why no lot already saved changes meaning.')
    w('inline const FProjCase T51_Projection[] = {')
    for pc in fx['t51_projection']:
        rows = ', '.join('{ %s, %s, %s, %s }' % (n(r['world']), n(r['x']),
                                                 n(r['y']), n(r['along']))
                         for r in pc['points'])
        w('\t{ %s, %s, %s, %s, %s, %s, %s, { %s } },' % (
            q(pc['road']), n(pc['s0']), n(pc['length']), n(pc['ux']), n(pc['uy']),
            n(pc['nx']), n(pc['ny']), rows))
    w('};')
    w('inline constexpr int32 T51_ProjectionNum = %d;' % len(fx['t51_projection']))
    w('')
    w('// 52: a lot on a 45 degree road, end to end, priced by its true length.')
    t = fx['t52_diagonal_lot']
    w('inline const FSegDef T52_Segment = %s;' % segdef(t['segment']))
    w('inline constexpr double T52_MoneyBefore = %s;' % n(t['money_before']))
    w('inline constexpr double T52_MoneyAfter = %s;' % n(t['money_after']))
    w('inline constexpr double T52_ClickX = %s;' % n(t['click'][0]))
    w('inline constexpr double T52_ClickY = %s;' % n(t['click'][1]))
    w('inline const FLotDef2 T52_Lot = %s;' % lotdef(t['lot']))
    w('inline const FQuadDef T52_Quad = { { %s }, { %s } };' % (
        ', '.join(n(p[0]) for p in t['quad']), ', '.join(n(p[1]) for p in t['quad'])))
    w('// The far side is off the PLATE, not off the road - the cost of the')
    w('// 2026-09-07 pad rule, emitted as the refusal it now is.')
    w('inline constexpr double T52_OtherX = %s;' % n(t['other_side_click'][0]))
    w('inline constexpr double T52_OtherY = %s;' % n(t['other_side_click'][1]))
    w('inline constexpr bool T52_OtherOk = %s;' % b(t['other_side_ok']))
    w('inline const TCHAR* const T52_OtherReason = %s;' % q(t['other_side_reason']))
    w('inline constexpr bool T52_AgainOk = %s;' % b(t['again_ok']))
    w('inline const TCHAR* const T52_AgainReason = %s;' % q(t['again_reason']))
    w('')
    w('// 53: side names come off the NORMAL, not the dominant axis of the run.')
    w('inline const FSideRow T53_Sides[] = {')
    for r in fx['t53_sides']:
        w('\t{ %s, %s, %s, %s, %s, %s, %s, %s, %s, %s },' % (
            q(r['label']), n(r['start'][0]), n(r['start'][1]),
            n(r['end'][0]), n(r['end'][1]), q(r['side_plus']), q(r['side_minus']),
            b(r['axis'] == 'x'), n(r['nx']), n(r['ny'])))
    w('};')
    w('inline constexpr int32 T53_SidesNum = %d;' % len(fx['t53_sides']))
    w('')
    w('// 54: two lots along one diagonal street - pads apart, boxes overlapping.')
    w('// Both are placed for real, the second click derived one lot-width along')
    w('// the same frame so the spans are adjacent by construction. The plate')
    w('// rule of 2026-09-07 does NOT cost this case; what it costs is a 45')
    w('// degree road with lots on BOTH sides, which is test 52\'s.')
    t = fx['t54_two_lots']
    w('inline const FSegDef T54_Segment = %s;' % segdef(t['segment']))
    w('inline constexpr double T54_Clicks[2][2] = { { %s, %s }, { %s, %s } };' % (
        n(t['clicks'][0][0]), n(t['clicks'][0][1]),
        n(t['clicks'][1][0]), n(t['clicks'][1][1])))
    w('inline const FLotDef2 T54_Lots[2] = { %s, %s };'
      % (lotdef(t['lots'][0]), lotdef(t['lots'][1])))
    w('inline constexpr bool T54_Quads = %s;' % b(t['quads']))
    w('inline constexpr bool T54_Rects = %s;' % b(t['rects']))
    w('')
    w('// 55: the other three scans compare pads too.')
    t = fx['t55_scans']
    rl = t['road_vs_lot']
    w('inline constexpr double T55_RvL_Click[2] = { %s, %s };'
      % (n(rl['lot_click'][0]), n(rl['lot_click'][1])))
    w('inline const FLotDef2 T55_RvL_Lot = %s;' % lotdef(rl['lot']))
    w('inline constexpr double T55_RvL_Draw[4] = { %s };'
      % ', '.join(n(v) for v in rl['draw']))
    w('inline constexpr bool T55_RvL_Quads = %s;' % b(rl['quads']))
    w('inline constexpr bool T55_RvL_Rects = %s;' % b(rl['rects']))
    rr = t['road_vs_road']
    w('inline constexpr double T55_RvR_First[4] = { %s };'
      % ', '.join(n(v) for v in rr['first']))
    w('inline constexpr double T55_RvR_Second[4] = { %s };'
      % ', '.join(n(v) for v in rr['second']))
    w('inline constexpr bool T55_RvR_Quads = %s;' % b(rr['quads']))
    w('inline constexpr bool T55_RvR_Rects = %s;' % b(rr['rects']))
    lh = t['lot_vs_highway']
    w('inline constexpr double T55_LvH_Road[4] = { %s };'
      % ', '.join(n(v) for v in lh['road']))
    w('inline constexpr double T55_LvH_Click[2] = { %s, %s };'
      % (n(lh['click'][0]), n(lh['click'][1])))
    w('inline const FLotDef2 T55_LvH_Lot = %s;' % lotdef(lh['lot']))
    w('inline constexpr double T55_LvH_Highway[4] = { %s };'
      % ', '.join(n(v) for v in lh['highway']))
    w('inline constexpr bool T55_LvH_Quads = %s;' % b(lh['quads']))
    w('inline constexpr bool T55_LvH_Rects = %s;' % b(lh['rects']))
    w('inline constexpr bool T55_LvH_StillPlaces = %s;' % b(lh['still_places']))
    w('')
    w('// ---- CURVED MULTI-NODE ROADS, self-tests 56-60 (item 11) -------------')
    w('struct FNode { double X; double Y; };')
    w('')
    w('// The three nodes every curve case below is drawn through.')
    w('inline const FNode Curve[] = { %s };'
      % ', '.join('{ %s, %s }' % (n(p[0]), n(p[1])) for p in fx['CURVE']))
    w('inline constexpr int32 CurveNum = %d;' % len(fx['CURVE']))
    w('')
    w('// 56: the sampled polyline, vertex for vertex.')
    w('inline const FNode T56_Sampled[] = { %s };'
      % ', '.join('{ %s, %s }' % (n(p[0]), n(p[1])) for p in fx['t56_sampled']))
    w('inline constexpr int32 T56_SampledNum = %d;' % len(fx['t56_sampled']))
    w('inline const FNode T56_StraightNodes[] = { %s };'
      % ', '.join('{ %s, %s }' % (n(p[0]), n(p[1])) for p in fx['t56_straight_nodes']))
    w('inline constexpr int32 T56_StraightNodesNum = %d;' % len(fx['t56_straight_nodes']))
    w('inline const FNode T56_Straight[] = { %s };'
      % ', '.join('{ %s, %s }' % (n(p[0]), n(p[1])) for p in fx['t56_straight']))
    w('inline constexpr int32 T56_StraightNum = %d;' % len(fx['t56_straight']))
    w('')
    w('// 57: one gesture, one road, one price.')
    t = fx['t57_path']
    w('inline constexpr double T57_MoneyBefore = %s;' % n(t['money_before']))
    w('inline constexpr double T57_MoneyAfter = %s;' % n(t['money_after']))
    w('inline const TCHAR* const T57_PathId = %s;' % q(t['path_id']))
    w('inline const TCHAR* const T57_Ids[] = { %s };'
      % ', '.join(q(i) for i in t['ids']))
    w('inline constexpr int32 T57_IdsNum = %d;' % len(t['ids']))
    w('inline const FSegDef T57_Segments[] = {')
    for sg in t['segments']:
        w('\t%s,' % segdef(sg))
    w('};')
    w('')
    w('// 58: joints in more than one CHORD, and a lot that spans them.')
    w('inline const FNode T58_Joints[] = { %s };'
      % ', '.join('{ %s, %s }' % (n(p[0]), n(p[1])) for p in fx['t58_joints']))
    w('inline constexpr int32 T58_JointsNum = %d;' % len(fx['t58_joints']))
    t = fx['t58_lot']
    w('inline constexpr double T58_ClickX = %s;' % n(t['click'][0]))
    w('inline constexpr double T58_ClickY = %s;' % n(t['click'][1]))
    w('inline const FLotDef2 T58_Lot = %s;' % lotdef(t['lot']))
    w('inline constexpr double T58_ChordLength = %s;' % n(t['chord_length']))
    w('inline constexpr double T58_SpanMin = %s;' % n(t['span_min']))
    w('inline constexpr double T58_SpanMax = %s;' % n(t['span_max']))
    w('')
    w('// 59: one decision - any chord failing refuses the whole path.')
    def pathcase(key, name, with_nodes=True):
        c = fx[key]
        if with_nodes and 'nodes' in c:
            w('inline const FNode %s_Nodes[] = { %s };' % (
                name, ', '.join('{ %s, %s }' % (n(p[0]), n(p[1])) for p in c['nodes'])))
            w('inline constexpr int32 %s_NodesNum = %d;' % (name, len(c['nodes'])))
        w('inline constexpr bool %s_Ok = %s;' % (name, b(c['ok'])))
        w('inline const TCHAR* const %s_Reason = %s;' % (name, q(c.get('reason'))))
    pathcase('t59_crosses', 'T59_Crosses')
    w('inline constexpr int32 T59_CrossesSegments = %d;'
      % (0 if fx['t59_crosses']['segments'] is None else len(fx['t59_crosses']['segments'])))
    pathcase('t59_afford', 'T59_Afford')
    t = fx['t59_boundary']
    w('inline constexpr double T59_Cost = %s;' % n(t['cost']))
    w('inline constexpr bool T59_UnderOk = %s;' % b(t['under_ok']))
    w('inline const TCHAR* const T59_UnderReason = %s;' % q(t['under_reason']))
    w('inline constexpr bool T59_ExactOk = %s;' % b(t['exact_ok']))
    pathcase('t59_unknown', 'T59_Unknown')
    pathcase('t59_one_node', 'T59_OneNode')
    pathcase('t59_too_short', 'T59_TooShort')
    t = fx['t59_overshoot']
    w('inline const FNode T59_Overshoot_Nodes[] = { %s };'
      % ', '.join('{ %s, %s }' % (n(p[0]), n(p[1])) for p in t['nodes']))
    w('inline constexpr int32 T59_Overshoot_NodesNum = %d;' % len(t['nodes']))
    w('inline constexpr bool T59_Overshoot_Ok = %s;' % b(t['ok']))
    w('inline const TCHAR* const T59_Overshoot_Reason = %s;' % q(t['reason']))
    w('inline constexpr double T59_Overshoot_MinY = %s;' % n(t['min_y']))
    w('inline constexpr double T59_Overshoot_PlateYMin = %s;' % n(t['plate_y_min']))
    t = fx['t59_lot']
    w('inline constexpr double T59_Lot_ClickX = %s;' % n(t['lot_click'][0]))
    w('inline constexpr double T59_Lot_ClickY = %s;' % n(t['lot_click'][1]))
    w('inline const FLotDef2 T59_Lot_Lot = %s;' % lotdef(t['lot']))
    w('inline const FNode T59_Lot_Nodes[] = { %s };'
      % ', '.join('{ %s, %s }' % (n(p[0]), n(p[1])) for p in t['nodes']))
    w('inline constexpr int32 T59_Lot_NodesNum = %d;' % len(t['nodes']))
    w('inline constexpr bool T59_Lot_Ok = %s;' % b(t['ok']))
    w('inline const TCHAR* const T59_Lot_Reason = %s;' % q(t['reason']))
    t = fx['t59_two_nodes']
    w('inline const FNode T59_Two_Nodes[] = { %s };'
      % ', '.join('{ %s, %s }' % (n(p[0]), n(p[1])) for p in t['nodes']))
    w('inline constexpr int32 T59_Two_NodesNum = %d;' % len(t['nodes']))
    w('inline const TCHAR* const T59_Two_PathId = %s;' % q(t['path_id']))
    w('inline constexpr int32 T59_Two_Count = %d;' % len(t['ids']))
    w('inline const FSegDef T59_Two_Segments[] = {')
    for sg in t['segments']:
        w('\t%s,' % segdef(sg))
    w('};')
    w('')
    w('// 61: a lot may not overlap ANY road\'s corridor - with its own PATH')
    w('// exempt, without which no lot could front a curve at all.')
    t = fx['t61_corridor']
    w('inline constexpr double T61_Road[4] = { %s };'
      % ', '.join(n(v) for v in t['road']))
    w('inline constexpr double T61_ClickX = %s;' % n(t['click'][0]))
    w('inline constexpr double T61_ClickY = %s;' % n(t['click'][1]))
    w('inline constexpr bool T61_Ok = %s;' % b(t['ok']))
    w('inline const TCHAR* const T61_Reason = %s;' % q(t['reason']))
    t = fx['t61_curve']
    w('inline const FNode T61_CurveNodes[] = { %s };'
      % ', '.join('{ %s, %s }' % (n(p[0]), n(p[1])) for p in t['nodes']))
    w('inline constexpr int32 T61_CurveNodesNum = %d;' % len(t['nodes']))
    w('inline constexpr double T61_FrontedX = %s;' % n(t['fronted'][0]['click'][0]))
    w('inline constexpr double T61_FrontedY = %s;' % n(t['fronted'][0]['click'][1]))
    w('inline const FLotDef2 T61_FrontedLot = %s;' % lotdef(t['fronted'][0]['lot']))
    w('')
    w('// 62: a lot\'s PAD may not leave the plate. The witness is a click 779 uu')
    w('// INSIDE the plate\'s north edge whose pad reaches y = 4542; the control is')
    w('// the same 45 degree shape where the board has room. T62_Swept is the')
    w('// REDUCTION: the C++ runs the identical sweep and must reach the same count')
    w('// with every pad inside the plate, so the rule is free for both built-ins by')
    w('// measurement rather than by argument.')
    t = fx['t62_plate']
    w('inline constexpr double T62_Road[4] = { %s };'
      % ', '.join(n(v) for v in t['road']))
    w('inline constexpr double T62_ClickX = %s;' % n(t['click'][0]))
    w('inline constexpr double T62_ClickY = %s;' % n(t['click'][1]))
    w('inline constexpr bool T62_Ok = %s;' % b(t['ok']))
    w('inline const TCHAR* const T62_Reason = %s;' % q(t['reason']))
    w('inline constexpr double T62_PadBox[4] = { %s };'
      % ', '.join(n(v) for v in t['pad_box']))
    w('inline constexpr double T62_RoomRoad[4] = { %s };'
      % ', '.join(n(v) for v in t['room_road']))
    w('inline constexpr double T62_RoomClickX = %s;' % n(t['room_click'][0]))
    w('inline constexpr double T62_RoomClickY = %s;' % n(t['room_click'][1]))
    w('inline const FLotDef2 T62_RoomLot = %s;' % lotdef(t['room_lot']))
    w('inline constexpr double T62_Widths[] = { %s };'
      % ', '.join(n(v) for v in t['widths']))
    w('inline constexpr int32 T62_WidthsNum = %d;' % len(t['widths']))
    w('inline constexpr int32 T62_Swept = %d;' % t['swept'])
    w('// ALL FOUR EDGES: a mutation that dropped the x edges survived the first')
    w('// version of this test, because north and south were the only edges the')
    w('// cases above ever reached.')
    w('struct FEdgeCase { const TCHAR* Edge; double Road[4]; double OutX, OutY;')
    w('\tbool bOutOk; const TCHAR* OutReason; double InX, InY; bool bInOk; };')
    w('inline const FEdgeCase T62_Edges[] = {')
    for r in t['edges']:
        w('\t{ %s, { %s }, %s, %s, %s, %s, %s, %s, %s },' % (
            q(r['edge']), ', '.join(n(v) for v in r['road']),
            n(r['out_click'][0]), n(r['out_click'][1]), b(r['out_ok']),
            q(r['out_reason']), n(r['in_click'][0]), n(r['in_click'][1]),
            b(r['in_ok'])))
    w('};')
    w('inline constexpr int32 T62_EdgesNum = %d;' % len(t['edges']))
    w('// AND THE EDGE ITSELF IS INSIDE: a pad flush with the plate is on it.')
    w('inline constexpr double T62_FlushXClick[2] = { %s, %s };'
      % (n(t['flush_x_click'][0]), n(t['flush_x_click'][1])))
    w('inline const FLotDef2 T62_FlushXLot = %s;' % lotdef(t['flush_x_lot']))
    w('inline constexpr double T62_FlushXBox[4] = { %s };'
      % ', '.join(n(v) for v in t['flush_x_box']))
    w('inline constexpr double T62_FlushYClick[2] = { %s, %s };'
      % (n(t['flush_y_click'][0]), n(t['flush_y_click'][1])))
    w('inline const FLotDef2 T62_FlushYLot = %s;' % lotdef(t['flush_y_lot']))
    w('inline constexpr double T62_FlushYBox[4] = { %s };'
      % ', '.join(n(v) for v in t['flush_y_box']))
    w('')
    w('// 63: a path may not cross itself. CENTRELINES, not corridors - a')
    w('// corridor rule cannot be stated for this at all, because chords two')
    w('// apart on a perfectly STRAIGHT road are T63_StraightChordGap apart')
    w('// against a T63_CorridorWidth corridor. The hairpin is what the exact')
    w('// rule costs: it draws, and its own arms come within T63_HairpinGap.')
    t = fx['t63_self_crossing']
    w('struct FSegPair { const TCHAR* Label; double A0X, A0Y, A1X, A1Y;')
    w('\tdouble B0X, B0Y, B1X, B1Y; bool bCross; };')
    w('inline const FSegPair T63_Pairs[] = {')
    for r in t['pairs']:
        w('\t{ %s, %s, %s, %s, %s, %s, %s, %s, %s, %s },' % (
            q(r['label']), n(r['a0'][0]), n(r['a0'][1]), n(r['a1'][0]), n(r['a1'][1]),
            n(r['b0'][0]), n(r['b0'][1]), n(r['b1'][0]), n(r['b1'][1]), b(r['cross'])))
    w('};')
    w('inline constexpr int32 T63_PairsNum = %d;' % len(t['pairs']))
    w('inline const FNode T63_LoopNodes[] = { %s };'
      % ', '.join('{ %s, %s }' % (n(p[0]), n(p[1])) for p in t['loop_nodes']))
    w('inline constexpr int32 T63_LoopNodesNum = %d;' % len(t['loop_nodes']))
    w('inline constexpr int32 T63_LoopI = %d;' % t['loop_i'])
    w('inline constexpr int32 T63_LoopJ = %d;' % t['loop_j'])
    w('inline constexpr bool T63_LoopOk = %s;' % b(t['loop_ok']))
    w('inline const TCHAR* const T63_LoopReason = %s;' % q(t['loop_reason']))
    w('inline constexpr double T63_LoopMoneyBefore = %s;' % n(t['loop_money_before']))
    w('inline constexpr double T63_LoopMoney = %s;' % n(t['loop_money']))
    w('inline constexpr int32 T63_LoopRoads = %d;' % t['loop_roads'])
    w('inline const FNode T63_OpenNodes[] = { %s };'
      % ', '.join('{ %s, %s }' % (n(p[0]), n(p[1])) for p in t['open_nodes']))
    w('inline constexpr int32 T63_OpenNodesNum = %d;' % len(t['open_nodes']))
    w('inline constexpr bool T63_OpenOk = %s;' % b(t['open_ok']))
    w('inline constexpr int32 T63_OpenChords = %d;' % t['open_chords'])
    w('inline const FNode T63_HairpinNodes[] = { %s };'
      % ', '.join('{ %s, %s }' % (n(p[0]), n(p[1])) for p in t['hairpin_nodes']))
    w('inline constexpr int32 T63_HairpinNodesNum = %d;' % len(t['hairpin_nodes']))
    w('inline constexpr bool T63_HairpinOk = %s;' % b(t['hairpin_ok']))
    w('inline constexpr int32 T63_HairpinChords = %d;' % t['hairpin_chords'])
    w('inline constexpr double T63_HairpinGap = %s;' % n(t['hairpin_gap']))
    w('inline constexpr double T63_StraightChordGap = %s;' % n(t['straight_chord_gap']))
    w('inline constexpr double T63_CorridorWidth = %s;' % n(t['corridor_width']))
    w('')
    w('} // namespace StacktownRoadsOracle')

    with open(OUT, 'w') as f:
        f.write('\n'.join(L) + '\n')
    print('wrote %s (%d lines)' % (os.path.relpath(OUT, ROOT), len(L)))


if __name__ == '__main__':
    main()
