"""Saved/SelfTest/placement_oracle.json -> PlacementOracleFixture.inl.

Same job as emit_fixture_inl.py does for the economy: put the oracle's own
answers in front of the C++ tests so no expectation is ever retyped. In this
module that matters more than usual - placement.py's own test COMMENTS have
drifted from its assertions in at least two places (see the generator's
docstring), so reading numbers off the comments would have imported the drift.

  python3 Tools/oracle/gen_placement_fixture.py
  python3 Tools/oracle/emit_placement_inl.py
"""
import json
import os

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.normpath(os.path.join(HERE, '..', '..'))
SRC = os.path.join(ROOT, 'Saved', 'SelfTest', 'placement_oracle.json')
OUT = os.path.join(ROOT, 'Source', 'StacktownAlpha', 'Private', 'Tests',
                   'PlacementOracleFixture.inl')


def q(s):
    if s is None:
        return 'nullptr'
    return 'TEXT("%s")' % s.replace('\\', '\\\\').replace('"', '\\"')


def n(v):
    return repr(float(v))


def b(v):
    return 'true' if v else 'false'


def lot(l):
    """FLotDef: RoadId nullptr means the key is ABSENT, not 'arterial'."""
    if l is None:
        return '{ 0.0, 0.0, nullptr, nullptr }'
    return '{ %s, %s, %s, %s }' % (n(l['x0']), n(l['x1']), q(l['side']),
                                   q(l.get('road_id')))


def main():
    fx = json.load(open(SRC))
    L = []
    w = L.append

    w('// GENERATED by Tools/oracle/emit_placement_inl.py from the Python oracle.')
    w('// DO NOT HAND-EDIT - regenerate. Covers placement.py self-tests 1-27, the')
    w('// click -> lot -> state contract. Tests 28-39 (drawn roads) are step 4.')
    w('//')
    w('//   python3 Tools/oracle/gen_placement_fixture.py')
    w('//   python3 Tools/oracle/emit_placement_inl.py')
    w('#pragma once')
    w('')
    w('namespace StacktownPlacementOracle')
    w('{')
    w('// A road_id of nullptr means the key is ABSENT from the lot, which is not')
    w('// the same as it being present and equal to "arterial".')
    w('struct FLotDef { double X0; double X1; const TCHAR* Side; const TCHAR* RoadId; };')
    w('struct FRoadDef { const TCHAR* Id; double StartX; double StartY; double EndX;')
    w('                  double EndY; const TCHAR* SidePlus; const TCHAR* SideMinus; bool bAxisX; };')
    w('struct FPinDef { double X0; double X1; const TCHAR* Side; };')
    w('struct FResolveCase { double X; double Y; const TCHAR* Road; double Along;')
    w('                      double Across; const TCHAR* Side; };')
    w('struct FClickCase { double X; double Y; bool bPinsActive; bool bOk;')
    w('                    const TCHAR* Reason; FLotDef Lot; };')
    w('struct FRect { double XMin; double XMax; double YMin; double YMax; };')
    w('')

    c = fx['constants']
    for key, name in (('POSITION_QUANTUM', 'PositionQuantum'), ('V0_WIDTH', 'V0Width'),
                      ('ROAD_HALF', 'RoadHalf'), ('BLOCK_DEPTH', 'BlockDepth'),
                      ('REACH_SLACK', 'ReachSlack'), ('ROAD_MAX_REACH', 'RoadMaxReach'),
                      ('VERGE', 'Verge'),
                      ('PLATE_X_MIN', 'PlateXMin'), ('PLATE_X_MAX', 'PlateXMax'),
                      ('PLATE_Y_MIN', 'PlateYMin'), ('PLATE_Y_MAX', 'PlateYMax'),
                      ('PERFORMANCE_NEUTRAL', 'PerformanceNeutral')):
        w('inline constexpr double %s = %s;' % (name, n(c[key])))
    w('inline constexpr int32 PoolSize = %d;' % c['POOL_SIZE'])
    w('inline const TCHAR* const V0Recipe = %s;' % q(c['V0_RECIPE']))
    w('')

    w('// The two built-in roads, as the oracle declares them.')
    w('inline const FRoadDef Roads[] = {')
    for r in fx['roads']:
        w('\t{ %s, %s, %s, %s, %s, %s, %s, %s },' % (
            q(r['id']), n(r['start'][0]), n(r['start'][1]),
            n(r['end'][0]), n(r['end'][1]),
            q(r['side_plus']), q(r['side_minus']), b(r['axis'] == 'x')))
    w('};')
    w('inline constexpr int32 RoadsNum = %d;' % len(fx['roads']))
    w('')
    w('// PINNED_SPANS, derived at import from citylayout. Injected as data here:')
    w('// porting the layout module is step 3, and this port needs the answers.')
    w('inline const FPinDef PinnedSpans[] = {')
    for (x0, x1, side) in fx['pinned_spans']:
        w('\t{ %s, %s, %s },' % (n(x0), n(x1), q(side)))
    w('};')
    w('inline constexpr int32 PinnedSpansNum = %d;' % len(fx['pinned_spans']))
    w('')
    w('// Test 7: containment, not equality. The plate must be at least as wide as')
    w('// the blocks it contains; its real bounds were MEASURED off the board mesh')
    w('// in the editor and cannot be re-derived here.')
    w('inline constexpr double BlockEnvXMin = %s;' % n(fx['block_env']['x_min']))
    w('inline constexpr double BlockEnvXMax = %s;' % n(fx['block_env']['x_max']))
    w('')

    def place_case(key, name):
        v = fx[key]
        w('// %s' % key)
        w('inline constexpr double %s_X = %s;' % (name, n(v['x'])))
        w('inline constexpr double %s_Y = %s;' % (name, n(v['y'])))
        w('inline constexpr bool   %s_Ok = %s;' % (name, b(v['ok'])))
        w('inline const TCHAR* const %s_Pid = %s;' % (name, q(v['pid'])))
        w('inline const TCHAR* const %s_Reason = %s;' % (name, q(v['reason'])))
        if v['ok'] and v['pid']:
            p = v['parcels'][v['pid']]
            w('inline const FLotDef %s_Lot = %s;' % (name, lot(p['placement'])))
            w('inline const TCHAR* const %s_Rid = %s;' % (name, q(p['rid'])))
            w('inline constexpr int32 %s_Tier = %d;' % (name, p['tier']))
            w('inline constexpr double %s_Width = %s;' % (name, n(p['width'])))
        w('')

    for key, name in (('t1_first_place', 'T1'), ('t2_off_board', 'T2'),
                      ('t3_same_side_overlap', 'T3'), ('t4_opposite_side', 'T4'),
                      ('t5_next_pid', 'T5'), ('t8_pool_exhausted', 'T8'),
                      ('t20_cross_west', 'T20'), ('t21_cross_east', 'T21')):
        place_case(key, name)

    w('// Test 6: place() yields EnsureParcel\'s shape plus exactly one key.')
    w('inline const TCHAR* const T6_ExtraKey = %s;' % q(fx['t6_shape']['extra'][0]))
    w('inline constexpr int32 T6_ExtraCount = %d;' % len(fx['t6_shape']['extra']))
    w('')

    def click_case(key, name):
        v = fx[key]
        w('inline const FClickCase %s = { %s, %s, %s, %s, %s, %s };' % (
            name, n(v['x']), n(v['y']), b(v['pins_active']), b(v['ok']),
            q(v['reason']), lot(v['lot'])))

    for key, name in (('t11_pinned_refuses', 'T11'),
                      ('t11b_empty_mode_accepts', 'T11b'),
                      ('t22_in_road_arterial', 'T22'),
                      ('t23_in_road_cross', 'T23'),
                      ('t27_corner_cross_refused', 'T27Cross'),
                      ('t27_corner_arterial_refused', 'T27Arterial')):
        click_case(key, name)
    w('')
    w('inline const FClickCase T24Crossing[] = {')
    for v in fx['t24_crossing_via_click']:
        w('\t{ %s, %s, %s, %s, %s, %s },' % (n(v['x']), n(v['y']), b(v['pins_active']),
                                             b(v['ok']), q(v['reason']), lot(v['lot'])))
    w('};')
    w('inline constexpr int32 T24CrossingNum = %d;' % len(fx['t24_crossing_via_click']))
    w('')

    def resolve_arr(key, name):
        w('inline const FResolveCase %s[] = {' % name)
        for v in fx[key]:
            w('\t{ %s, %s, %s, %s, %s, %s },' % (
                n(v['x']), n(v['y']), q(v['road']),
                n(v['along'] if v['along'] is not None else 0.0),
                n(v['across'] if v['across'] is not None else 0.0),
                q(v['side'])))
        w('};')
        w('inline constexpr int32 %sNum = %d;' % (name, len(fx[key])))

    resolve_arr('t13_arterial_alone', 'T13ArterialAlone')
    resolve_arr('t14_cross_alone', 'T14CrossAlone')
    resolve_arr('t16_crossing', 'T16Crossing')
    resolve_arr('t19_too_far', 'T19TooFar')
    w('')
    for key, name in (('t15_nearest_wins', 'T15'), ('t17_past_the_band', 'T17'),
                      ('t18_point_to_segment', 'T18')):
        v = fx[key]
        w('inline const FResolveCase %s = { %s, %s, %s, %s, %s, %s };' % (
            name, n(v['x']), n(v['y']), q(v['road']),
            n(v['along'] if v['along'] is not None else 0.0),
            n(v['across'] if v['across'] is not None else 0.0), q(v['side'])))
    w('')

    w('// ADDED BY THE PORT: the snap grid itself. Python\'s round() is')
    w('// half-to-EVEN, and no click coordinate in the 27 lands off the grid, so')
    w('// without these a port that TRUNCATED passed everything.')
    w('struct FSnapCase { double In; double Expected; };')
    w('inline const FSnapCase SnapCases[] = {')
    for c in fx['snap_cases']:
        w('\t{ %s, %s },' % (n(c['in']), n(c['expected'])))
    w('};')
    w('inline constexpr int32 SnapCasesNum = %d;' % len(fx['snap_cases']))
    for key, name in (('snap_through_click', 'SnapClick'),
                      ('snap_through_click_half', 'SnapClickHalf')):
        v = fx[key]
        w('inline const FClickCase %s = { %s, %s, %s, %s, %s, %s };' % (
            name, n(v['x']), n(v['y']), b(v['pins_active']), b(v['ok']),
            q(v['reason']), lot(v['lot'])))
    w('')
    w('// Tests 9, 10, 12: plan_reactivation.')
    for key, name in (('t9_plan_enough', 'T9'), ('t10_plan_too_few', 'T10'),
                      ('t12_plan_generic', 'T12')):
        v = fx[key]
        w('inline const TCHAR* const %s_Pids[] = { %s };' % (
            name, ', '.join(q(p) for p in v['pids'])))
        w('inline constexpr int32 %s_PidsNum = %d;' % (name, len(v['pids'])))
        w('inline const TCHAR* const %s_Labels[] = { %s };' % (
            name, ', '.join(q(p) for p in v['labels'])))
        w('inline constexpr int32 %s_LabelsNum = %d;' % (name, len(v['labels'])))
        w('inline const TCHAR* const %s_PairPids[] = { %s };' % (
            name, ', '.join(q(p[0]) for p in v['pairs']) or 'nullptr'))
        w('inline const TCHAR* const %s_PairLabels[] = { %s };' % (
            name, ', '.join(q(p[1]) for p in v['pairs']) or 'nullptr'))
        w('inline constexpr int32 %s_PairsNum = %d;' % (name, len(v['pairs'])))
        w('inline const TCHAR* const %s_Unmatched[] = { %s };' % (
            name, ', '.join(q(p) for p in v['unmatched']) or 'nullptr'))
        w('inline constexpr int32 %s_UnmatchedNum = %d;' % (name, len(v['unmatched'])))
    w('')

    w('// Test 25: lot_road_id\'s backward-compatible default.')
    w('inline const FLotDef T25_Lots[] = {')
    for c25 in fx['t25_lot_road_id']:
        w('\t%s,' % lot(c25['lot']))
    w('};')
    w('inline const TCHAR* const T25_Expected[] = { %s };' % ', '.join(
        q(c25['expected']) for c25 in fx['t25_lot_road_id']))
    w('inline constexpr int32 T25Num = %d;' % len(fx['t25_lot_road_id']))
    w('')

    w('// Test 26: survives a restart, including a LEGACY lot with no road_id.')
    rt = fx['t26_round_trip']
    for pid, name in (('P1', 'T26_P1'), ('P2', 'T26_P2')):
        before = rt['before']['parcels'][pid]
        w('inline const FLotDef %s_Lot = %s;' % (name, lot(before['placement'])))
        w('inline constexpr int32 %s_Tier = %d;' % (name, before['tier']))
        w('inline constexpr bool %s_Owned = %s;' % (name, b(before['owned'])))
        w('inline constexpr double %s_Accum = %s;' % (name, n(before['accum'])))
    w('inline const TCHAR* const T26_P1_RoadId = %s;' % q(rt['p1_road_id']))
    w('inline constexpr bool T26_P2_HasRoadIdKey = %s;' % b(rt['p2_has_road_id_key']))
    w('inline const TCHAR* const T26_P2_RoadId = %s;' % q(rt['p2_road_id']))
    w('')

    w('// ADDED BY THE PORT: overlap-scan determinism. When two lots both overlap')
    w('// a click, the C++ SORTS and always names the same one; the Python walks')
    w('// insertion order. A refusal that changes between runs is unactionable.')
    oo = fx['overlap_order']
    w('inline const FLotDef OverlapLotA = %s;' % lot(oo['lot_a']))
    w('inline const FLotDef OverlapLotB = %s;' % lot(oo['lot_b']))
    for key, name in (('a_only', 'OverlapAOnly'), ('b_only', 'OverlapBOnly')):
        v = oo[key]
        w('inline const FClickCase %s = { %s, %s, %s, %s, %s, %s };' % (
            name, n(v['x']), n(v['y']), b(v['pins_active']), b(v['ok']),
            q(v['reason']), lot(v['lot'])))
    w('')
    w('// Test 27: the corner - world footprints, not per-road spans.')
    for i, c27 in enumerate(fx['t27_lot_rects']):
        w('inline const FLotDef T27_Lot%d = %s;' % (i, lot(c27['lot'])))
        w('inline const FRect T27_Rect%d = { %s, %s, %s, %s };' % (
            i, n(c27['rect'][0]), n(c27['rect'][1]),
            n(c27['rect'][2]), n(c27['rect'][3])))
    w('')
    w('} // namespace StacktownPlacementOracle')

    with open(OUT, 'w') as f:
        f.write('\n'.join(L) + '\n')
    print('wrote %s (%d lines)' % (os.path.relpath(OUT, ROOT), len(L)))


if __name__ == '__main__':
    main()
