"""Turn Saved/SelfTest/econ_oracle.json into a C++ header the tests include.

Why this exists: the ported tests must assert what the ORACLE returned, not what
a porter re-typed while reading it. A transcription error in a test expectation
is the exact failure shape HANDOFF section 5 calls the most expensive category -
a check that asks the wrong question and answers "ok". Generating the
expectations removes the typing step entirely.

  python3 Tools/oracle/gen_econ_fixture.py     # run the oracle, write the JSON
  python3 Tools/oracle/emit_fixture_inl.py     # JSON -> EconOracleFixture.inl

The .inl is COMMITTED so the Mac build needs no Python at build time, and so a
reviewer can diff what the oracle said against what the tests assert.
"""
import json
import os

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.normpath(os.path.join(HERE, '..', '..'))
SRC = os.path.join(ROOT, 'Saved', 'SelfTest', 'econ_oracle.json')
OUT = os.path.join(ROOT, 'Source', 'StacktownAlpha', 'Private', 'Tests',
                   'EconOracleFixture.inl')


def cxx_str(s):
    return 'TEXT("%s")' % s.replace('\\', '\\\\').replace('"', '\\"')


def cxx_num(v):
    if isinstance(v, bool):
        return 'true' if v else 'false'
    return repr(float(v))


def main():
    fx = json.load(open(SRC))
    r = fx['rules']
    L = []
    w = L.append

    w('// GENERATED by Tools/oracle/emit_fixture_inl.py from the Python oracle.')
    w('// DO NOT HAND-EDIT - regenerate. Every value below is what')
    w('// Content/Python/econrules.py and citytick.py actually returned when run,')
    w('// not a number transcribed from a comment. See the generator for why.')
    w('//')
    w('// Regenerate:')
    w('//   python3 Tools/oracle/gen_econ_fixture.py')
    w('//   python3 Tools/oracle/emit_fixture_inl.py')
    w('#pragma once')
    w('')
    w('namespace StacktownOracle')
    w('{')

    w('// --- econrules.json, as the oracle read it -------------------------------')
    for key, name in (('money_start', 'MoneyStart'), ('price_base', 'PriceBase'),
                      ('price_per_100uu', 'PricePer100uu'),
                      ('price_per_tier', 'PricePerTier'),
                      ('rent_per_tier', 'RentPerTier'),
                      ('growth_threshold', 'GrowthThreshold'),
                      ('demand_default', 'DemandDefault'),
                      ('demand_gain', 'DemandGain'),
                      ('demand_loss', 'DemandLoss'),
                      ('demand_rate', 'DemandRate'),
                      ('demand_min', 'DemandMin'),
                      ('demand_max', 'DemandMax'),
                      ('wear_ticks_per_tier', 'WearTicksPerTier'),
                      ('trade_credit_amount', 'TradeCreditAmount'),
                      ('trade_bonus_per_win', 'TradeBonusPerWin')):
        w('inline constexpr double %s = %s;' % (name, cxx_num(r[key])))
    w('inline constexpr int32 TradeCreditsPerN = %d;' % r['trade_credits_per_n'])
    w('')
    w('// ROAD TYPES (MONDAY_DECISIONS section 2), read straight out of')
    w('// econrules.json by the oracle. OracleRules() builds FEconRules::RoadTypes')
    w('// from these, so a placement test measures the owner\'s table and not the')
    w('// table the C++ happens to have compiled in - and')
    w('// Stacktown.Roads.TypeRulesMatchOracle compares the two, which is what')
    w('// keeps that compiled default from quietly drifting.')
    w('struct FRoadTypeRow { const TCHAR* Type; double CostPer100uu; double RentMult;')
    w('                      double Width; bool bFrontage; };')
    w('inline const FRoadTypeRow RoadTypeRows[] = {')
    for t in ('dirt', 'avenue', 'boulevard', 'highway'):
        w('\t{ TEXT("%s"), %s, %s, %s, %s },' % (
            t, cxx_num(r['road_cost_per_100uu_%s' % t]),
            cxx_num(r['road_rent_mult_%s' % t]),
            cxx_num(r['road_width_%s' % t]),
            'true' if r['road_frontage_%s' % t] else 'false'))
    w('};')
    w('inline constexpr int32 RoadTypeRowsNum = 4;')
    w('inline constexpr double RoadHighwayReach = %s;' % cxx_num(r['road_highway_reach']))
    w('')

    w('// --- the catalogue surface the economy asks about ------------------------')
    tc = fx['catalogue']['tier_count']
    for rid in sorted(tc):
        w('inline constexpr int32 TierCount_%s = %d;' % (rid, tc[rid]))
    an = fx['catalogue']['asset_name']
    for k in sorted(an):
        w('inline const TCHAR* const AssetName_%s = %s;' % (k, cxx_str(an[k])))
    ae = fx['catalogue']['asset_exists']
    for k in sorted(ae):
        w('inline constexpr bool AssetExists_%s = %s;' % (k, cxx_num(ae[k])))
    baked = fx['catalogue']['baked_for_tests']
    w('// Every baked mesh the ported tests can reach, as the oracle saw it.')
    w('inline const TCHAR* const BakedForTests[] = {')
    for name in baked:
        w('\t%s,' % cxx_str(name))
    w('};')
    w('inline constexpr int32 BakedForTestsNum = %d;' % len(baked))
    w('')

    w('struct FTierWidthCase { int32 Tier; double Width; double Expected; };')
    w('inline const FTierWidthCase PriceCases[] = {')
    for c in fx['price']:
        w('\t{ %d, %s, %s },' % (c['tier'], cxx_num(c['width']), cxx_num(c['expected'])))
    w('};')
    w('')
    w('struct FTierDemandCase { int32 Tier; double Demand; double Expected; };')
    w('inline const FTierDemandCase RentCases[] = {')
    for c in fx['rent']:
        w('\t{ %d, %s, %s },' % (c['tier'], cxx_num(c['demand']), cxx_num(c['expected'])))
    w('};')
    w('')
    w('struct FIntCase { int32 In; int32 Expected; };')
    w('inline const FIntCase ClimbCases[] = {')
    for c in fx['climb']:
        w('\t{ %d, %d },' % (c['tier'], c['expected']))
    w('};')
    w('')
    w('struct FDoubleCase { double In; double Expected; };')
    w('inline const FDoubleCase PremiumCases[] = {')
    for c in fx['premium']:
        w('\t{ %s, %s },' % (cxx_num(c['performance']), cxx_num(c['expected'])))
    w('};')
    w('')
    w('struct FTierPerfCase { int32 Tier; double Performance; double Expected; };')
    w('inline const FTierPerfCase UpgradePriceCases[] = {')
    for c in fx['upgrade_price']:
        w('\t{ %d, %s, %s },' % (c['tier'], cxx_num(c['performance']), cxx_num(c['expected'])))
    w('};')
    w('')
    w('inline const FIntCase RepairPriceCases[] = {')
    for c in fx['repair_price']:
        w('\t{ %d, %d },' % (c['tier'], int(c['expected'])))
    w('};')
    w('')

    w('// --- tier_up_allowed: exact reason strings -------------------------------')
    w('struct FLadderCase { const TCHAR* Rid; int32 Tier; double Width; bool bOk; const TCHAR* Reason; };')
    w('inline const FLadderCase LadderCases[] = {')
    for c in fx['tier_up_allowed']:
        w('\t{ %s, %d, %s, %s, %s },' % (cxx_str(c['rid']), c['tier'],
                                         cxx_num(c['width']), cxx_num(c['ok']),
                                         cxx_str(c['reason'])))
    w('};')
    w('')

    w('// --- verb refusals: exact reason strings ---------------------------------')
    for group in ('buy', 'upgrade', 'repair'):
        for key in sorted(fx[group]):
            c = fx[group][key]
            w('inline const TCHAR* const %s_%s_Reason = %s;' % (
                group.capitalize(), key, cxx_str(c['reason'])))
            w('inline constexpr bool %s_%s_Ok = %s;' % (
                group.capitalize(), key, cxx_num(c['ok'])))
    w('')

    w('// --- tick ----------------------------------------------------------------')
    b = fx['buy_then_tick_10']
    w('inline constexpr double BuyThenTick10_AfterBuyMoney = %s;' % cxx_num(b['after_buy_money']))
    w('inline constexpr double BuyThenTick10_Money = %s;' % cxx_num(b['final']['money']))
    w('inline constexpr double BuyThenTick10_Accum = %s;' % cxx_num(b['final']['parcels']['P1']['accum']))
    w('inline constexpr int32  BuyThenTick10_Tier  = %d;' % b['final']['parcels']['P1']['tier'])
    w('inline constexpr int32  BuyThenTick10_Events = %d;' % len(b['events']))
    t = fx['tick_1000']
    w('inline constexpr double Tick1000_Money = %s;' % cxx_num(t['final']['money']))
    w('inline constexpr double Tick1000_Accum = %s;' % cxx_num(t['final']['parcels']['P1']['accum']))
    w('inline constexpr int32  Tick1000_Tier  = %d;' % t['final']['parcels']['P1']['tier'])
    w('inline constexpr int32  Tick1000_Events = %d;' % len(t['events']))
    g = fx['tick_retired_growth']
    w('inline constexpr double TickRetired_Money = %s;' % cxx_num(g['final']['money']))
    w('inline constexpr double TickRetired_Accum = %s;' % cxx_num(g['final']['parcels']['OF']['accum']))
    w('inline constexpr int32  TickRetired_Tier  = %d;' % g['final']['parcels']['OF']['tier'])
    w('inline constexpr int32  TickRetired_Events = %d;' % len(g['events']))
    m = fx['tick_multi']
    w('inline constexpr double TickMulti_DemandStart = %s;' % cxx_num(m['start_demand']))
    w('inline constexpr double TickMulti_Demand = %s;' % cxx_num(m['final']['demand']))
    w('inline constexpr double TickMulti_Money = %s;' % cxx_num(m['final']['money']))
    for pid in sorted(m['final']['parcels']):
        w('inline constexpr double TickMulti_Accum_%s = %s;'
          % (pid, cxx_num(m['final']['parcels'][pid]['accum'])))
    w('')

    w('// --- verb happy paths ----------------------------------------------------')
    w('inline constexpr double UpgradeHappy_Money = %s;'
      % cxx_num(fx['upgrade']['HAPPY']['final']['money']))
    w('inline constexpr int32  UpgradeHappy_Tier = %d;'
      % fx['upgrade']['HAPPY']['final']['parcels']['P1']['tier'])
    w('inline constexpr double UpgradeWorst_Money = %s;'
      % cxx_num(fx['upgrade']['WORST_AFFORDS']['final']['money']))
    w('inline constexpr int32  UpgradeWorst_Tier = %d;'
      % fx['upgrade']['WORST_AFFORDS']['final']['parcels']['P2']['tier'])
    w('inline constexpr double RepairHappy_Money = %s;'
      % cxx_num(fx['repair']['HAPPY']['final']['money']))
    w('inline constexpr bool   RepairHappy_Failed = %s;'
      % cxx_num(fx['repair']['HAPPY']['final']['parcels']['P1']['failed']))
    w('')

    w('// --- trade ledger --------------------------------------------------------')
    w('struct FPnlCase { double Pnl; bool bExpected; };')
    w('inline const FPnlCase IsWinCases[] = {')
    for c in fx['is_win']:
        w('\t{ %s, %s },' % (cxx_num(c['pnl']), cxx_num(c['expected'])))
    w('};')
    w('')
    w('struct FCountRewardCase { int32 Before; int32 New; int32 PerN; double Amount; double Expected; };')
    w('inline const FCountRewardCase CountRewardCases[] = {')
    for c in fx['trade_count_reward']:
        w('\t{ %d, %d, %d, %s, %s },' % (c['before'], c['new'], c['per_n'],
                                         cxx_num(c['amount']), cxx_num(c['expected'])))
    w('};')
    w('')
    lg = fx['apply_trade_ledger']
    w('inline const double LedgerPnls[] = { %s };'
      % ', '.join(cxx_num(p) for p in lg['ledger']))
    w('inline constexpr int32 LedgerPnlsNum = %d;' % len(lg['ledger']))
    w('inline const double LedgerPnlsLonger[] = { %s };'
      % ', '.join(cxx_num(p) for p in lg['longer_ledger']['pnls']))
    w('inline constexpr int32 LedgerPnlsLongerNum = %d;'
      % len(lg['longer_ledger']['pnls']))
    w('inline constexpr double Ledger_Money = %s;' % cxx_num(lg['first']['final']['money']))
    w('inline constexpr int32  Ledger_Processed = %d;'
      % lg['first']['final']['trades_processed'])
    for name, ev in (('First', lg['first']['events']),
                     ('Replay', lg['idempotent_replay']['events']),
                     ('Longer', lg['longer_ledger']['events'])):
        w('inline constexpr int32 LedgerEvents_%s_Num = %d;' % (name, len(ev)))
        for i, (kind, amt) in enumerate(ev):
            w('inline const TCHAR* const LedgerEvents_%s_%d_Kind = %s;'
              % (name, i, cxx_str(kind)))
            w('inline constexpr double LedgerEvents_%s_%d_Amount = %s;'
              % (name, i, cxx_num(amt)))
    w('inline constexpr double LedgerLonger_Money = %s;'
      % cxx_num(lg['longer_ledger']['final']['money']))
    w('inline constexpr int32  LedgerLonger_Processed = %d;'
      % lg['longer_ledger']['final']['trades_processed'])
    w('')

    w('// --- citytick seed -------------------------------------------------------')
    seed = fx['seed_state']
    w('inline constexpr double Seed_Money = %s;' % cxx_num(seed['money']))
    w('inline constexpr double Seed_Demand = %s;' % cxx_num(seed['demand']))
    w('inline constexpr int32  Seed_ParcelCount = %d;' % len(seed['parcels']))
    w('inline const TCHAR* const Seed_RoadsJson = %s;' % cxx_str(json.dumps(seed['roads'], separators=(',', ':'))))
    w('')
    w('} // namespace StacktownOracle')

    os.makedirs(os.path.dirname(OUT), exist_ok=True)
    with open(OUT, 'w') as f:
        f.write('\n'.join(L) + '\n')
    print('wrote %s (%d lines)' % (os.path.relpath(OUT, ROOT), len(L)))


if __name__ == '__main__':
    main()
