"""Saved/SelfTest/roads_oracle.json -> RoadsOracleFixture.inl (step 4)."""
import json
import os

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.normpath(os.path.join(HERE, '..', '..'))
SRC = os.path.join(ROOT, 'Saved', 'SelfTest', 'roads_oracle.json')
OUT = os.path.join(ROOT, 'Source', 'StacktownAlpha', 'Private', 'Tests',
                   'RoadsOracleFixture.inl')


def q(s):
    if s is None:
        return 'nullptr'
    return 'TEXT("%s")' % s.replace('\\', '\\\\').replace('"', '\\"')


def n(v):
    return repr(float(v))


def b(v):
    return 'true' if v else 'false'


def segdef(s):
    if s is None:
        return '{ nullptr, 0.0, 0.0, 0.0, 0.0, nullptr }'
    return '{ %s, %s, %s, %s, %s, %s }' % (
        q(s['id']), n(s['start'][0]), n(s['start'][1]),
        n(s['end'][0]), n(s['end'][1]), q(s['width_class']))


def main():
    fx = json.load(open(SRC))
    L = []
    w = L.append
    w('// GENERATED by Tools/oracle/emit_roads_inl.py from the Python oracle.')
    w('// DO NOT HAND-EDIT - regenerate. Covers placement.py self-tests 28-39,')
    w('// the drawn-road half (Phase 1 step 4).')
    w('//')
    w('//   python3 Tools/oracle/gen_roads_fixture.py')
    w('//   python3 Tools/oracle/emit_roads_inl.py')
    w('#pragma once')
    w('')
    w('namespace StacktownRoadsOracle')
    w('{')
    w('struct FSegDef { const TCHAR* Id; double StartX; double StartY;')
    w('                 double EndX; double EndY; const TCHAR* WidthClass; };')
    w('struct FDrawCase { double X0; double Y0; double X1; double Y1;')
    w('                   bool bPinsActive; bool bOk; const TCHAR* Reason; FSegDef Road; };')
    w('struct FRectDef { double XMin; double XMax; double YMin; double YMax; };')
    w('struct FLotDef2 { double X0; double X1; const TCHAR* Side; const TCHAR* RoadId; };')
    w('')
    w('inline constexpr double MinRoadLength = %s;' % n(fx['MIN_ROAD_LENGTH']))
    w('')

    w('// 28: lot_rect reduces to the old hard-coded constants for both built-ins.')
    for i, c in enumerate(fx['t28_lot_rect']):
        l = c['lot']
        w('inline const FLotDef2 T28_Lot%d = { %s, %s, %s, %s };' % (
            i, n(l['x0']), n(l['x1']), q(l['side']), q(l.get('road_id'))))
        w('inline const FRectDef T28_Rect%d = { %s, %s, %s, %s };' % (
            i, n(c['rect'][0]), n(c['rect'][1]), n(c['rect'][2]), n(c['rect'][3])))
    w('')

    w('// 29: side conventions READ OFF the segment geometry, not stored.')
    w('struct FOrientCase { FSegDef Seg; const TCHAR* SidePlus; const TCHAR* SideMinus; bool bAxisX; };')
    w('inline const FOrientCase T29Orientation[] = {')
    for c in fx['t29_road_dict']:
        w('\t{ %s, %s, %s, %s },' % (segdef(c['segment']), q(c['side_plus']),
                                     q(c['side_minus']), b(c['axis'] == 'x')))
    w('};')
    w('inline constexpr int32 T29OrientationNum = %d;' % len(fx['t29_road_dict']))
    w('')

    w('// 30: the built-ins, plus whatever has been drawn.')
    t30 = fx['t30_all_roads']
    w('inline const TCHAR* const T30_Before[] = { %s };'
      % ', '.join(q(i) for i in t30['before']))
    w('inline constexpr int32 T30_BeforeNum = %d;' % len(t30['before']))
    w('inline const TCHAR* const T30_After[] = { %s };'
      % ', '.join(q(i) for i in t30['after']))
    w('inline constexpr int32 T30_AfterNum = %d;' % len(t30['after']))
    w('inline const FSegDef T30_Drawn = %s;' % segdef(t30['drawn']))
    w('')

    w('// 31-37: every accept and every named refusal.')
    for key, name in (('t31_happy_horizontal', 'T31'), ('t32_too_diagonal', 'T32'),
                      ('t33_too_short', 'T33'), ('t34_off_board', 'T34'),
                      ('t35_crosses_builtin', 'T35'), ('t36_crosses_pin', 'T36'),
                      ('t36b_empty_mode', 'T36b'), ('t37_happy_vertical', 'T37')):
        c = fx[key]
        w('inline const FDrawCase %s = { %s, %s, %s, %s, %s, %s, %s, %s };' % (
            name, n(c['x0']), n(c['y0']), n(c['x1']), n(c['y1']),
            b(c['pins_active']), b(c['ok']), q(c['reason']), segdef(c['road'])))
    w('')

    w('// ADDED BY THE PORT: a near-axis drag snaps its minor coordinate to the')
    w('// START point. Every accepted road in 28-39 has equal ends, so nothing')
    w('// there separates start from end.')
    for key, name in (('near_horizontal', 'NearHorizontal'), ('near_vertical', 'NearVertical')):
        c = fx[key]
        w('inline const FDrawCase %s = { %s, %s, %s, %s, %s, %s, %s, %s };' % (
            name, n(c['x0']), n(c['y0']), n(c['x1']), n(c['y1']),
            b(c['pins_active']), b(c['ok']), q(c['reason']), segdef(c['road'])))
    w('')
    w('// 38: draw_road end to end, R1 then R2, and a refusal naming R1 itself.')
    t38 = fx['t38_draw_road']
    w('inline const TCHAR* const T38_FirstId = %s;' % q(t38['first']['id']))
    w('inline const FSegDef T38_FirstStored = %s;' % segdef(t38['first']['stored']))
    w('inline const TCHAR* const T38_SecondId = %s;' % q(t38['second']['id']))
    w('inline const FSegDef T38_SecondStored = %s;' % segdef(t38['second']['stored']))
    cr = t38['crosses_r1']
    w('inline const FDrawCase T38_CrossesR1 = { %s, %s, %s, %s, %s, %s, %s, %s };' % (
        n(cr['x0']), n(cr['y0']), n(cr['x1']), n(cr['y1']),
        b(cr['pins_active']), b(cr['ok']), q(cr['reason']), segdef(cr['road'])))
    w('inline const TCHAR* const T38_Ids[] = { %s };'
      % ', '.join(q(i) for i in t38['ids']))
    w('inline constexpr int32 T38_IdsNum = %d;' % len(t38['ids']))
    w('')

    w('// 39: a lot placed AGAINST a drawn road, through place() itself.')
    t39 = fx['t39_place_against_drawn']
    w('inline const FSegDef T39_Drawn = %s;' % segdef(t39['drawn']))
    w('inline constexpr double T39_ClickX = %s;' % n(t39['click'][0]))
    w('inline constexpr double T39_ClickY = %s;' % n(t39['click'][1]))
    w('inline const TCHAR* const T39_Pid = %s;' % q(t39['pid']))
    w('inline constexpr bool T39_Ok = %s;' % b(t39['ok']))
    l = t39['lot']
    w('inline const FLotDef2 T39_Lot = { %s, %s, %s, %s };' % (
        n(l['x0']), n(l['x1']), q(l['side']), q(l.get('road_id'))))
    w('inline const FRectDef T39_Rect = { %s, %s, %s, %s };' % (
        n(t39['rect'][0]), n(t39['rect'][1]), n(t39['rect'][2]), n(t39['rect'][3])))
    w('')
    w('} // namespace StacktownRoadsOracle')

    with open(OUT, 'w') as f:
        f.write('\n'.join(L) + '\n')
    print('wrote %s (%d lines)' % (os.path.relpath(OUT, ROOT), len(L)))


if __name__ == '__main__':
    main()
