"""Golden oracle fixture for the C++ road port (Phase 1 step 4).

placement.py self-tests 28-39: the drawn-road half. Same discipline as the other
two generators - run the oracle over the exact scenarios the C++ replays and
record what it returned, so no expectation is ever retyped.

  python3 Tools/oracle/gen_roads_fixture.py
Writes Saved/SelfTest/roads_oracle.json. Never touches citystate.json.
"""
import json
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.normpath(os.path.join(HERE, '..', '..'))
sys.path.insert(0, os.path.join(ROOT, 'Content', 'Python'))

import citytick        # noqa: E402
import econrules       # noqa: E402
import placement as P  # noqa: E402

OUT_DIR = os.path.join(ROOT, 'Saved', 'SelfTest')
OUT_PATH = os.path.join(OUT_DIR, 'roads_oracle.json')


def seg(d):
    if d is None:
        return None
    return {'id': d['id'], 'start': list(d['start']), 'end': list(d['end']),
            'width_class': d['width_class'], 'path': d.get('path', '')}


def cap_draw(state, x0, y0, x1, y1, pins_active=True, width_class='avenue'):
    ok, reason, road = P.resolve_road_draw(state, x0, y0, x1, y1, width_class,
                                           pins_active=pins_active)
    return {'x0': x0, 'y0': y0, 'x1': x1, 'y1': y1, 'width_class': width_class,
            'pins_active': pins_active, 'ok': ok, 'reason': reason,
            'road': seg(road)}


def cap_click(state, x, y, pins_active=True):
    ok, reason, lot = P.resolve_click(state, x, y, pins_active=pins_active)
    return {'x': x, 'y': y, 'pins_active': pins_active, 'ok': ok,
            'reason': reason, 'lot': lot}


GEOMETRY_MONEY = 1000.0


def funded():
    """seed_state with a balance the geometry cases cannot fail on.

    Roads cost money since road types (2026-09-06) and a 1400 uu avenue is $140
    against the $100 a fresh city starts with - so every case here that is about
    GEOMETRY is given a balance that cannot be the reason it refuses. The price
    itself is captured on its own, on a state left at money_start deliberately
    (t44 below). Mirrors placement.py's own funding note at self-test 31."""
    s = citytick.seed_state()
    s['money'] = GEOMETRY_MONEY
    return s


def main():
    fx = {
        '_': 'GENERATED by Tools/oracle/gen_roads_fixture.py from the Python '
             'oracle. Do not hand-edit: regenerate. Covers placement.py '
             'self-tests 28-48: the drawn-road half (step 4) and road '
             'types as mechanics (2026-09-06, MONDAY_DECISIONS section 2).',
        'MIN_ROAD_LENGTH': P.MIN_ROAD_LENGTH,
        'GEOMETRY_MONEY': GEOMETRY_MONEY,
    }

    # --- 28: lot_rect reduces to today's math for both built-ins -------------
    fx['t28_lot_rect'] = [
        {'lot': l, 'rect': list(P.lot_rect(l))}
        for l in ({'x0': 100.0, 'x1': 500.0, 'side': 'north', 'road_id': 'arterial'},
                  {'x0': 200.0, 'x1': 600.0, 'side': 'west', 'road_id': 'cross'})
    ]

    # --- 29: orientation is READ OFF the segment's own geometry --------------
    horiz = {'id': 'H', 'start': (0.0, 100.0), 'end': (500.0, 100.0),
             'width_class': 'avenue'}
    vert = {'id': 'V', 'start': (300.0, 0.0), 'end': (300.0, 900.0),
            'width_class': 'avenue'}
    fx['t29_road_dict'] = []
    for s in (horiz, vert):
        d = P._road_dict(s)
        fx['t29_road_dict'].append(
            {'segment': seg(s), 'side_plus': d['side_plus'],
             'side_minus': d['side_minus'], 'axis': d['axis']})

    # --- 30: _all_roads is the built-ins plus whatever has been drawn --------
    s30 = citytick.seed_state()
    before = [r['id'] for r in P._all_roads(s30)]
    s30['roads']['R1'] = {'id': 'R1', 'start': (0.0, 100.0),
                          'end': (500.0, 100.0), 'width_class': 'avenue'}
    after = [r['id'] for r in P._all_roads(s30)]
    fx['t30_all_roads'] = {'before': before, 'after': after,
                           'drawn': seg(s30['roads']['R1'])}

    # --- 31-37: every accept and every named refusal -------------------------
    s = funded()
    fx['t31_happy_horizontal'] = cap_draw(s, 6200.0, 3000.0, 7600.0, 3000.0)
    fx['t32_too_diagonal']     = cap_draw(s, 0.0, 3000.0, 1000.0, 3800.0)
    fx['t33_too_short']        = cap_draw(s, 6200.0, 3000.0, 6700.0, 3000.0)
    fx['t34_off_board']        = cap_draw(s, 7000.0, 3000.0, 8000.0, 3000.0)
    fx['t35_crosses_builtin']  = cap_draw(s, 6200.0, 0.0, 7600.0, 0.0)
    fx['t36_crosses_pin']      = cap_draw(s, 2000.0, 2900.0, 3000.0, 2900.0)
    fx['t36b_empty_mode']      = cap_draw(s, 2000.0, 2900.0, 3000.0, 2900.0,
                                          pins_active=False)
    fx['t37_happy_vertical']   = cap_draw(s, 3000.0, 3400.0, 3000.0, 4230.0)

    # --- ADDED BY THE PORT: the minor coordinate comes from the START --------
    # Every accepted road in cases 28-39 is drawn with its minor coordinate
    # already equal at both ends, so taking it from the END instead of the start
    # is invisible to all of them - a mutation proving that survived until this
    # existed. A near-horizontal drag is the case that separates them: dx=1400,
    # dy=50, so the horizontal rule wins and y must snap to the START's 3000,
    # not the end's 3050.
    fx['near_horizontal'] = cap_draw(s, 6200.0, 3000.0, 7600.0, 3050.0)
    fx['near_vertical']   = cap_draw(s, 3000.0, 3400.0, 3050.0, 4230.0)

    # --- 38: draw_road end to end, and R1/R2 sequencing ----------------------
    s38 = funded()
    s38, rid1, ok1, reason1 = P.draw_road(s38, 6200.0, 3000.0, 7600.0, 3000.0)
    crosses_r1 = cap_draw(s38, 6900.0, 2000.0, 6900.0, 4230.0)
    s38, rid2, ok2, reason2 = P.draw_road(s38, 3000.0, 3400.0, 3000.0, 4230.0)
    fx['t38_draw_road'] = {
        'first':  {'id': rid1, 'ok': ok1, 'reason': reason1,
                   'stored': seg(s38['roads'][rid1])},
        'crosses_r1': crosses_r1,
        'second': {'id': rid2, 'ok': ok2, 'reason': reason2,
                   'stored': seg(s38['roads'][rid2])},
        'ids': sorted(s38['roads'].keys()),
    }

    # --- 39: a lot placed AGAINST a drawn road, end to end -------------------
    # RELOCATED 2026-09-07 with the oracle's own test 39: at y=3000 this road's
    # south frontage band ran 760 uu into the arterial's pavement, which a lot
    # may no longer do.
    s39 = funded()
    s39, _, _, _ = P.draw_road(s39, 6200.0, 3800.0, 7600.0, 3800.0)
    s39, pid39, ok39, reason39 = P.place(s39, 6900.0, 2500.0)
    lot39 = s39['parcels'][pid39]['placement'] if ok39 else None
    fx['t39_place_against_drawn'] = {
        'drawn': seg(s39['roads']['R1']),
        'click': [6900.0, 2500.0],
        'pid': pid39, 'ok': ok39, 'reason': reason39, 'lot': lot39,
        'rect': list(P.lot_rect(lot39, P._all_roads(s39))) if ok39 else None,
    }

    # ---- ROAD TYPES AS MECHANICS, self-tests 40-48 -------------------------
    # MONDAY_DECISIONS section 2's four types. Every value below comes OUT of
    # the oracle running the same scenarios the C++ replays; nothing is retyped.
    R = econrules.rules()
    fx['VERGE'] = P.VERGE
    fx['ROAD_TYPES'] = list(P.ROAD_TYPES)
    fx['DEFAULT_ROAD_TYPE'] = P.DEFAULT_ROAD_TYPE
    fx['road_highway_reach'] = R['road_highway_reach']

    # 40/41: the per-type table, as the oracle computes it - half, reach, cost
    # of a 1400 uu road, material name, and the four raw rules values.
    fx['t40_types'] = []
    for t in P.ROAD_TYPES:
        probe = {'id': 'X', 'start': (0.0, 0.0), 'end': (1400.0, 0.0),
                 'width_class': t}
        fx['t40_types'].append({
            'type': t,
            'cost_per_100uu': R['road_cost_per_100uu_%s' % t],
            'rent_mult': R['road_rent_mult_%s' % t],
            'width': R['road_width_%s' % t],
            'frontage': bool(R['road_frontage_%s' % t]),
            'half': P.road_half(probe, R),
            'max_reach': P.road_max_reach(probe, R),
            'cost_1400': P.road_cost(probe, R),
            'material': P.road_material_name(probe),
        })
    # A road with NO width class at all - both built-ins - is the avenue.
    fx['t40_untyped_half'] = P.road_half(P.ARTERIAL, R)
    fx['t40_untyped_reach'] = P.road_max_reach(P.ARTERIAL, R)
    fx['t41_length'] = [
        {'seg': seg({'id': 'X', 'start': (0.0, 100.0), 'end': (0.0, 1500.0),
                     'width_class': 'avenue'}),
         'length': P.road_length({'start': (0.0, 100.0), 'end': (0.0, 1500.0)})},
        {'seg': seg({'id': 'X', 'start': (0.0, 0.0), 'end': (700.0, 0.0),
                     'width_class': 'dirt'}),
         'length': 700.0,
         'cost': P.road_cost({'start': (0.0, 0.0), 'end': (700.0, 0.0),
                              'width_class': 'dirt'}, R)},
    ]

    # 42: the highway refuses frontage. The SAME segment drawn twice - as a
    # highway a click 2300 uu west of it is refused with a reason a player can
    # act on; as an avenue the identical click places a lot on its west side.
    HW = (7500.0, 1500.0, 7500.0, 4230.0)
    s42 = funded()
    s42, hid42, ok42, r42 = P.draw_road(s42, *HW, width_class='highway')
    s42c = funded()
    s42c, _, ok42c, _ = P.draw_road(s42c, *HW, width_class='avenue')
    fx['t42_frontage'] = {
        'segment': list(HW),
        'highway_drawn': {'id': hid42, 'ok': ok42, 'reason': r42,
                          'stored': seg(s42['roads'][hid42]) if ok42 else None,
                          'money_after': s42['money']},
        'avenue_drawn_ok': ok42c,
        'click_beside_highway': cap_click(s42, 5200.0, 3800.0),
        'click_beside_avenue': cap_click(s42c, 5200.0, 3800.0),
        'far_from_everything': cap_click(s42, -7000.0, -4000.0),
    }

    # 43: and nothing may be laid ACROSS one. An arterial north lot at x=7000
    # genuinely intersects that highway's corridor; the same click on a board
    # with no highway places normally.
    fx['t43_across_highway'] = {
        'with_highway': cap_click(s42, 7000.0, 1500.0),
        'without': cap_click(citytick.seed_state(), 7000.0, 1500.0),
    }

    # 44: roads cost money, on a state left at money_start deliberately.
    s44 = citytick.seed_state()
    money_before = s44['money']
    refuse44 = cap_draw(s44, 6200.0, 3000.0, 7600.0, 3000.0, width_class='avenue')
    s44, rid44a, ok44a, reason44a = P.draw_road(s44, 6200.0, 3000.0, 7600.0,
                                                3000.0, 'avenue')
    money_after_refusal = s44['money']
    s44, rid44, ok44, reason44 = P.draw_road(s44, 6200.0, 3000.0, 7600.0,
                                             3000.0, 'dirt')
    fx['t44_afford'] = {
        'money_start': money_before,
        'avenue_refused': refuse44,
        'refusal_spends_nothing': money_after_refusal,
        'dirt': {'id': rid44, 'ok': ok44, 'reason': reason44,
                 'stored': seg(s44['roads'][rid44]) if ok44 else None},
        'money_after': s44['money'],
    }

    # 45: a narrower road pulls its own frontage line in - the dirt road's
    # footprint and a lot on its south side, against the avenue's own numbers.
    fx['t45_dirt_frontage'] = {}
    s45 = funded()
    # ITS OWN ROAD, carried in the fixture rather than borrowed from 44's: 45
    # places a lot and so had to move north on 2026-09-07, while 44 is about
    # the price and did not.
    road45 = [6200.0, 3800.0, 7600.0, 3800.0]
    s45, _, ok45, reason45 = P.draw_road(s45, road45[0], road45[1], road45[2],
                                         road45[3], 'dirt')
    # 1000 uu off the centreline: inside an avenue's corridor and outside a
    # dirt track's, so this click is the one the two halves disagree about.
    s45, pid45, ok45b, reason45b = P.place(s45, 6900.0, 2800.0)
    fx['t45_dirt_frontage'].update({
        'road': road45,
        'road_rect': list(P.road_rect(P._road_dict(s45['roads']['R1']), R)),
        'click': [6900.0, 2800.0], 'pid': pid45, 'ok': ok45b,
        'reason': reason45b,
        'lot': s45['parcels'][pid45]['placement'] if ok45b else None,
        'rect': list(P.lot_rect(s45['parcels'][pid45]['placement'],
                                P._all_roads(s45), R)) if ok45b else None,
    })

    # 46: the rent multiplier. Synthetic states: the function is pure over
    # (state, lot), and hand-built adjacency is the only way to hit the 2,000 uu
    # edge from both sides.
    lot46 = {'x0': 6490.0, 'x1': 7310.0, 'side': 'south', 'road_id': 'D'}
    near_hw = {'id': 'HW', 'start': (7500.0, 1500.0), 'end': (7500.0, 4230.0),
               'width_class': 'highway'}
    far_hw = {'id': 'HW', 'start': (7500.0, -4230.0), 'end': (7500.0, -1500.0),
              'width_class': 'highway'}

    def s46(own_type, extra=None):
        roads = {'D': {'id': 'D', 'start': (6200.0, 3000.0),
                       'end': (7600.0, 3000.0), 'width_class': own_type}}
        if extra:
            roads['HW'] = dict(extra)
        return {'money': 0.0, 'parcels': {}, 'roads': roads}

    fx['t46_rent'] = []
    for own in P.ROAD_TYPES[:3]:
        fx['t46_rent'].append({'own': own, 'highway': None,
                               'mult': P.road_rent_multiplier(s46(own), lot46, R)})
    for label, hw in (('near', near_hw), ('far', far_hw)):
        fx['t46_rent'].append({
            'own': 'dirt', 'highway': label, 'highway_seg': seg(hw),
            'mult': P.road_rent_multiplier(s46('dirt', hw), lot46, R)})
    fx['t46_lot'] = lot46
    fx['t46_dirt_lot_rect'] = list(P.lot_rect(lot46, P._all_roads(s46('dirt')), R))
    fx['t46_far_distance'] = P._rect_distance(
        tuple(fx['t46_dirt_lot_rect']), P.road_rect(P._road_dict(far_hw), R))

    # 47: an unrecognised type is REFUSED at the boundary, with a reason.
    fx['t47_unknown'] = cap_draw(funded(), 6200.0, 3000.0, 7600.0, 3000.0,
                                 width_class='motorway')

    # 48: _in_crossing measures each road's OWN pavement. Direct, because no
    # state reachable through draw_road can have two corridors sharing ground -
    # see placement.py's own note at self-test 48 for why that is still right.
    cross_hw = P._road_dict({'id': 'HW', 'start': (7500.0, -4230.0),
                             'end': (7500.0, 4230.0), 'width_class': 'highway'})
    cross_av = dict(cross_hw, width_class='avenue')
    fx['t48_in_crossing'] = {
        'point': [6200.0, 500.0],
        'highway': P._in_crossing([P.ARTERIAL, cross_hw], 6200.0, 500.0, R),
        'avenue': P._in_crossing([P.ARTERIAL, cross_av], 6200.0, 500.0, R),
        'builtins_at_origin': P._in_crossing([P.ARTERIAL, P.CROSS_STREET],
                                             0.0, 0.0, R),
        'segment': seg({'id': 'HW', 'start': (7500.0, -4230.0),
                        'end': (7500.0, 4230.0), 'width_class': 'highway'}),
    }

    # 49: WHICH WAY THE PLAYER DRAGGED MUST NOT MATTER. A bug fix, not a new
    # feature: a road drawn right to left mirrored every lot placed on it about
    # its start point and flipped its side name. Captured as the ONE answer both
    # drag orders must produce, plus the two orders as inputs - a fixture with
    # two expected answers would be recording the bug.
    fx['t49_drag_direction'] = []
    for c0, c1, click in (((6200.0, 3800.0), (7600.0, 3800.0), (6900.0, 2500.0)),
                          ((7300.0, -4230.0), (7300.0, -3000.0), (5500.0, -3600.0))):
        seen = []
        for a, b in ((c0, c1), (c1, c0)):
            st = funded()
            st, rid, ok, why = P.draw_road(st, a[0], a[1], b[0], b[1])
            assert ok, (a, b, why)
            st, pid, ok2, why2 = P.place(st, click[0], click[1])
            assert ok2, (a, b, why2)
            seen.append((seg(st['roads'][rid]), st['parcels'][pid]['placement'],
                         st['money']))
        assert seen[0] == seen[1], seen
        fx['t49_drag_direction'].append({
            'forward': [list(c0), list(c1)], 'reversed': [list(c1), list(c0)],
            'click': list(click), 'segment': seen[0][0], 'lot': seen[0][1],
            'money': seen[0][2],
        })

    # ---- ROADS AT ANY DIRECTION, self-tests 50-55 (item 11, first half) ----
    # The resolver, the lot frame and every overlap scan generalize off the
    # road's own unit direction. The axis-aligned cases above are the same
    # numbers they always were - that reduction is the thing worth checking,
    # and it is captured here rather than argued.
    fx['t32b_diagonal_draws'] = cap_draw(funded(), 6200.0, 2500.0, 7200.0, 3500.0)
    fx['t33b_diagonal_too_short'] = cap_draw(funded(), 6200.0, 3000.0, 6700.0, 3500.0)

    # 50: quads_overlap against rects_overlap on real axis-aligned lot pairs -
    # an overlapping pair, a pair that only TOUCHES (a miss, because a lot sits
    # exactly on its own road's frontage line), opposite sides, and the corner.
    _r50 = P._all_roads(citytick.seed_state())
    fx['t50_quad_vs_rect'] = []
    for a, b in (
            ({'x0': 100.0, 'x1': 900.0, 'side': 'north', 'road_id': 'arterial'},
             {'x0': 500.0, 'x1': 1300.0, 'side': 'north', 'road_id': 'arterial'}),
            ({'x0': 100.0, 'x1': 900.0, 'side': 'north', 'road_id': 'arterial'},
             {'x0': 900.0, 'x1': 1700.0, 'side': 'north', 'road_id': 'arterial'}),
            ({'x0': 100.0, 'x1': 900.0, 'side': 'north', 'road_id': 'arterial'},
             {'x0': 100.0, 'x1': 900.0, 'side': 'south', 'road_id': 'arterial'}),
            ({'x0': 1640.0, 'x1': 2460.0, 'side': 'north', 'road_id': 'arterial'},
             {'x0': 1130.0, 'x1': 2630.0, 'side': 'west', 'road_id': 'cross'})):
        qa, qb = P.lot_quad(a, _r50), P.lot_quad(b, _r50)
        fx['t50_quad_vs_rect'].append({
            'a': a, 'b': b, 'quads': P.quads_overlap(qa, qb),
            'rects': P.rects_overlap(P.lot_rect(a, _r50), P.lot_rect(b, _r50))})

    # 51: the projection identity - s0 + along IS the world coordinate for both
    # built-ins, which is why no lot already saved changes meaning.
    fx['t51_projection'] = []
    for road, pts in ((P.ARTERIAL, (-7000.0, -410.0, 0.0, 2350.0, 7000.0)),
                      (P.CROSS_STREET, (-4000.0, -410.0, 0.0, 1500.0, 4000.0))):
        f = P.road_frame(road)
        idx = 0 if road['axis'] == 'x' else 1
        rows = []
        for w in pts:
            pt = (w, 3000.0) if idx == 0 else (3000.0, w)
            along, _across, _len = P._project_to_road(road, pt[0], pt[1])
            rows.append({'world': w, 'x': pt[0], 'y': pt[1], 'along': along})
        fx['t51_projection'].append({
            'road': road['id'], 's0': f[7], 'length': f[6],
            'ux': f[2], 'uy': f[3], 'nx': f[4], 'ny': f[5], 'points': rows})

    # 52: a lot on a 45 degree road, end to end, priced by its true length.
    s52 = citytick.seed_state()
    s52['money'] = 5000.0
    s52, rid52, ok52, why52 = P.draw_road(s52, 6200.0, 2500.0, 7200.0, 3500.0)
    assert ok52, why52
    s52, pid52, okl52, whyl52 = P.place(s52, 5639.4, 4060.6)
    assert okl52, whyl52
    lot52 = s52['parcels'][pid52]['placement']
    s52b, pid52b, oks52, _ = P.place(json.loads(json.dumps(s52)), 7760.6, 1939.4)
    _, _, again52, why52c = P.place(json.loads(json.dumps(s52)), 5639.4, 4060.6)
    fx['t52_diagonal_lot'] = {
        'money_before': 5000.0, 'money_after': s52['money'],
        'segment': seg(s52['roads'][rid52]),
        'click': [5639.4, 4060.6], 'pid': pid52, 'lot': lot52,
        'quad': [list(pt) for pt in P.lot_quad(lot52, P._all_roads(s52))],
        'other_side_click': [7760.6, 1939.4], 'other_side_ok': oks52,
        'other_side_lot': s52b['parcels'][pid52b]['placement'] if oks52 else None,
        'again_ok': again52, 'again_reason': why52c,
    }

    # 53: side names come off the NORMAL. The discriminating case runs down and
    # to the right at 2:1 - Y-dominant, so a dominant-axis rule would say
    # 'west', and the normal points east. Plus the reversed segments, which the
    # draw path can no longer produce but _road_dict must still answer.
    s53 = citytick.seed_state()
    s53['money'] = 5000.0
    s53, rid53, ok53, why53 = P.draw_road(s53, 6800.0, 4230.0, 7650.0, 2530.0)
    assert ok53, why53
    fx['t53_sides'] = []
    for label, sg in (('drawn-2to1', s53['roads'][rid53]),
                      ('reversed-diagonal',
                       {'id': 'X', 'start': (7200.0, 3500.0),
                        'end': (6200.0, 2500.0), 'width_class': 'avenue'}),
                      ('reversed-vertical',
                       {'id': 'X', 'start': (3000.0, 4230.0),
                        'end': (3000.0, 2000.0), 'width_class': 'avenue'}),
                      ('arterial', P.ARTERIAL), ('cross', P.CROSS_STREET)):
        d = P._road_dict(sg)
        f = P.road_frame(d)
        fx['t53_sides'].append({
            'label': label, 'segment': seg(sg) if 'width_class' in sg else None,
            'start': list(sg['start']), 'end': list(sg['end']),
            'side_plus': d['side_plus'], 'side_minus': d['side_minus'],
            'axis': d['axis'], 'nx': f[4], 'ny': f[5]})

    # 54: two houses along one diagonal street - pads apart, boxes overlapping.
    s54 = citytick.seed_state()
    s54['money'] = 9000.0
    s54, rid54, ok54, why54 = P.draw_road(s54, 5700.0, 2000.0, 7650.0, 3950.0,
                                          pins_active=False)
    assert ok54, why54
    f54 = P.road_frame(P._road_dict(s54['roads'][rid54]))
    clicks54, lots54 = [], []
    for t in (0.20, 0.80):
        al = f54[6] * t
        px = f54[0] + f54[2] * al + f54[4] * 1500.0
        py = f54[1] + f54[3] * al + f54[5] * 1500.0
        s54, pid, okp, whyp = P.place(s54, px, py, pins_active=False)
        assert okp, whyp
        clicks54.append([px, py])
        lots54.append(s54['parcels'][pid]['placement'])
    qa54 = P.lot_quad(lots54[0], P._all_roads(s54))
    qb54 = P.lot_quad(lots54[1], P._all_roads(s54))
    fx['t54_two_lots'] = {
        'segment': seg(s54['roads'][rid54]), 'clicks': clicks54, 'lots': lots54,
        'quads': P.quads_overlap(qa54, qb54),
        'rects': P.rects_overlap(P.quad_rect(qa54), P.quad_rect(qb54))}

    # 55: the other three scans compare pads too - something axis-aligned
    # standing in one of a diagonal's empty box corners.
    a55 = citytick.seed_state(); a55['money'] = 40000.0
    a55, pa55, oka55, whya55 = P.place(a55, 7000.0, 1500.0, pins_active=False)
    assert oka55, whya55
    lota55 = a55['parcels'][pa55]['placement']
    oka55, whya55, roada55 = P.resolve_road_draw(a55, 4400.0, 3600.0, 5900.0,
                                                 2100.0, pins_active=False)
    assert oka55, whya55
    qra55 = P.road_quad(P._road_dict(roada55))
    qla55 = P.lot_quad(lota55, P._all_roads(a55))

    b55 = citytick.seed_state(); b55['money'] = 40000.0
    b55, rb55, okb55, whyb55 = P.draw_road(b55, 4400.0, 3600.0, 5900.0, 2100.0,
                                           pins_active=False)
    assert okb55, whyb55
    okb55, whyb55, roadb55 = P.resolve_road_draw(b55, 2500.0, 1200.0, 2500.0,
                                                 2100.0, pins_active=False)
    assert okb55, whyb55
    qab55 = P.road_quad(P._road_dict(b55['roads'][rb55]))
    qbb55 = P.road_quad(P._road_dict(roadb55))

    c55 = citytick.seed_state(); c55['money'] = 40000.0
    c55, rc55, okc55, whyc55 = P.draw_road(c55, 5700.0, 2000.0, 7650.0, 3950.0,
                                           pins_active=False)
    assert okc55, whyc55
    f55 = P.road_frame(P._road_dict(c55['roads'][rc55]))
    al55 = f55[6] * 0.20
    px55 = f55[0] + f55[2] * al55 + f55[4] * 1500.0
    py55 = f55[1] + f55[3] * al55 + f55[5] * 1500.0
    okc55, whyc55, lotc55 = P.resolve_click(c55, px55, py55, pins_active=False)
    assert okc55, whyc55
    c55, rh55, okh55, whyh55 = P.draw_road(c55, 2600.0, 1800.0, 2600.0, 3000.0,
                                           'highway', pins_active=False)
    assert okh55, whyh55
    qh55 = P.road_quad(P._road_dict(c55['roads'][rh55]))
    ql55 = P.lot_quad(lotc55, P._all_roads(c55))
    fx['t55_scans'] = {
        'road_vs_lot': {
            'lot_click': [7000.0, 1500.0], 'lot': lota55,
            'draw': [4400.0, 3600.0, 5900.0, 2100.0],
            'quads': P.quads_overlap(qra55, qla55),
            'rects': P.rects_overlap(P.quad_rect(qra55), P.quad_rect(qla55))},
        'road_vs_road': {
            'first': [4400.0, 3600.0, 5900.0, 2100.0],
            'second': [2500.0, 1200.0, 2500.0, 2100.0],
            'quads': P.quads_overlap(qab55, qbb55),
            'rects': P.rects_overlap(P.quad_rect(qab55), P.quad_rect(qbb55))},
        'lot_vs_highway': {
            'road': [5700.0, 2000.0, 7650.0, 3950.0],
            'click': [px55, py55], 'lot': lotc55,
            'highway': [2600.0, 1800.0, 2600.0, 3000.0],
            'quads': P.quads_overlap(ql55, qh55),
            'rects': P.rects_overlap(P.quad_rect(ql55), P.quad_rect(qh55)),
            'still_places': P.resolve_click(c55, px55, py55,
                                            pins_active=False)[0]},
    }

    # ---- CURVED MULTI-NODE ROADS, self-tests 56-60 (item 11, second half) --
    CURVE = [(2000.0, -4000.0), (4000.0, -2600.0), (6000.0, -4000.0)]
    fx['CURVE'] = [list(n) for n in CURVE]
    fx['t56_sampled'] = [list(p) for p in P.sample_path(CURVE)]
    fx['t56_straight_nodes'] = [[0.0, 0.0], [1000.0, 0.0]]
    fx['t56_straight'] = [list(p) for p in P.sample_path(
        [tuple(n) for n in fx['t56_straight_nodes']])]

    s57 = citytick.seed_state()
    s57['money'] = 40000.0
    s57, path57, ids57, ok57, why57 = P.draw_road_path(s57, CURVE,
                                                       pins_active=False)
    assert ok57, why57
    fx['t57_path'] = {
        'money_before': 40000.0, 'money_after': s57['money'],
        'path_id': path57, 'ids': ids57,
        'segments': [seg(s57['roads'][i]) for i in ids57],
        'paths': [s57['roads'][i]['path'] for i in ids57],
    }

    # 58: joints where more than one CHORD claims the point, and _in_crossing
    # false at every one of them because they are one PATH.
    roads58 = P._all_roads(s57)

    def chords_at(x, y):
        n = 0
        for rd in roads58:
            al, ac, ln = P._project_to_road(rd, x, y)
            if 0.0 <= al <= ln and abs(ac) < P.road_half(rd):
                n += 1
        return n
    joints = [list(s57['roads'][i]['end']) for i in ids57[:-1]
              if chords_at(*s57['roads'][i]['end']) > 1]
    assert joints, 'no joint sits in more than one chord'
    fx['t58_joints'] = joints
    lot58 = None
    for k in range(len(ids57)):
        f = P.road_frame(P._road_dict(s57['roads'][ids57[k]]))
        mx = f[0] + f[2] * f[6] * 0.5
        my = f[1] + f[3] * f[6] * 0.5
        st, lp, okl, whyl = P.place(s57, mx + f[4] * 1500.0, my + f[5] * 1500.0,
                                    pins_active=False)
        if okl and st['parcels'][lp]['placement']['road_id'] in ids57:
            lot58 = {'click': [mx + f[4] * 1500.0, my + f[5] * 1500.0],
                     'lot': st['parcels'][lp]['placement']}
            break
    assert lot58 is not None, 'no lot could front any chord of the curve'
    seg58 = P._road_dict(s57['roads'][lot58['lot']['road_id']])
    lo58, hi58 = P.path_span(roads58, seg58)
    fx['t58_lot'] = dict(lot58, chord_length=P.road_frame(seg58)[6],
                         span_min=lo58, span_max=hi58)

    # 59: one decision - any chord failing refuses the whole path.
    s59 = citytick.seed_state()
    s59['money'] = 40000.0
    hits = [(2000.0, -3300.0), (4000.0, -2100.0), (6000.0, -3300.0)]
    ok59, why59, segs59 = P.resolve_road_path(s59, hits, pins_active=False)
    fx['t59_crosses'] = {'nodes': [list(n) for n in hits], 'ok': ok59,
                         'reason': why59, 'segments': segs59}
    ok59b, why59b, _ = P.resolve_road_path(citytick.seed_state(), CURVE,
                                           pins_active=False)
    fx['t59_afford'] = {'ok': ok59b, 'reason': why59b}
    cost59 = 10.0 * sum(P.road_length(s57['roads'][i]) for i in ids57) / 100.0
    sb = citytick.seed_state(); sb['money'] = cost59 - 1.0
    okb, whyb, _ = P.resolve_road_path(sb, CURVE, pins_active=False)
    se = citytick.seed_state(); se['money'] = cost59
    oke, whye, _ = P.resolve_road_path(se, CURVE, pins_active=False)
    fx['t59_boundary'] = {'cost': cost59, 'under_ok': okb, 'under_reason': whyb,
                          'exact_ok': oke}
    okc, whyc, _ = P.resolve_road_path(s57, CURVE, 'motorway', pins_active=False)
    fx['t59_unknown'] = {'ok': okc, 'reason': whyc}
    okd, whyd, _ = P.resolve_road_path(s57, [(0.0, 0.0)], pins_active=False)
    fx['t59_one_node'] = {'ok': okd, 'reason': whyd}
    oki, whyi, _ = P.resolve_road_path(
        s57, [(3000.0, -4000.0), (3300.0, -3800.0)], pins_active=False)
    fx['t59_too_short'] = {'nodes': [[3000.0, -4000.0], [3300.0, -3800.0]],
                           'ok': oki, 'reason': whyi}
    off_nodes = [(2000.0, -4000.0), (2600.0, -4229.0), (5000.0, -3200.0)]
    sk = citytick.seed_state(); sk['money'] = 40000.0
    okk, whyk, _ = P.resolve_road_path(sk, off_nodes, pins_active=False)
    fx['t59_overshoot'] = {
        'nodes': [list(n) for n in off_nodes], 'ok': okk, 'reason': whyk,
        'min_y': min(p[1] for p in P.sample_path(off_nodes)),
        'plate_y_min': P.PLATE_Y_MIN,
    }
    sl = citytick.seed_state(); sl['money'] = 40000.0
    sl, pl59, ol59, wl59 = P.place(sl, 4000.0, -2000.0, pins_active=False)
    assert ol59, wl59
    okl59, whyl59, _ = P.resolve_road_path(
        sl, [(3000.0, -3000.0), (4000.0, -2400.0), (5000.0, -3000.0)],
        pins_active=False)
    fx['t59_lot'] = {'lot_click': [4000.0, -2000.0],
                     'lot': sl['parcels'][pl59]['placement'],
                     'nodes': [[3000.0, -3000.0], [4000.0, -2400.0],
                               [5000.0, -3000.0]],
                     'ok': okl59, 'reason': whyl59}
    sf = citytick.seed_state(); sf['money'] = 40000.0
    sf, pf, idsf, okf, whyf = P.draw_road_path(
        sf, [(2000.0, -4000.0), (5000.0, -4000.0)], pins_active=False)
    assert okf, whyf
    fx['t59_two_nodes'] = {'nodes': [[2000.0, -4000.0], [5000.0, -4000.0]],
                           'path_id': pf, 'ids': idsf,
                           'segments': [seg(sf['roads'][i]) for i in idsf]}

    # ---- the frontage-corridor gap closed, self-test 61 (2026-09-07) -------
    # A lot may not overlap ANY road's corridor, not only one that refuses
    # frontage. The case is the one test 39 used to be, and the exemption for
    # the lot's OWN PATH is what keeps a curve buildable.
    s61 = funded()
    s61, _r61, ok61, why61 = P.draw_road(s61, 6200.0, 3000.0, 7600.0, 3000.0)
    assert ok61, why61
    ok61b, why61b, _lot61 = P.resolve_click(s61, 6900.0, 1700.0)
    fx['t61_corridor'] = {
        'road': [6200.0, 3000.0, 7600.0, 3000.0],
        'click': [6900.0, 1700.0], 'ok': ok61b, 'reason': why61b,
    }
    s61c = citytick.seed_state()
    s61c['money'] = 40000.0
    s61c, path61, ids61, ok61c, why61c = P.draw_road_path(
        s61c, [(2000.0, -4000.0), (4000.0, -2600.0), (6000.0, -4000.0)],
        pins_active=False)
    assert ok61c, why61c
    fronted = []
    for k in range(len(ids61)):
        f = P.road_frame(P._road_dict(s61c['roads'][ids61[k]]))
        m = (f[0] + f[2] * f[6] * 0.5, f[1] + f[3] * f[6] * 0.5)
        for sg in (1.0, -1.0):
            st, lp, o61, w61 = P.place(s61c, m[0] + f[4] * 1500.0 * sg,
                                       m[1] + f[5] * 1500.0 * sg,
                                       pins_active=False)
            if o61 and st['parcels'][lp]['placement']['road_id'] in ids61:
                fronted.append({'click': [m[0] + f[4] * 1500.0 * sg,
                                          m[1] + f[5] * 1500.0 * sg],
                                'lot': st['parcels'][lp]['placement']})
    assert fronted, 'the corridor rule must not make a curve unbuildable'
    fx['t61_curve'] = {'nodes': [[2000.0, -4000.0], [4000.0, -2600.0],
                                 [6000.0, -4000.0]],
                       'fronted': fronted[:1], 'fronted_count': len(fronted)}

    os.makedirs(OUT_DIR, exist_ok=True)
    with open(OUT_PATH, 'w') as f:
        json.dump(fx, f, indent=2, sort_keys=True)
    print('wrote %s' % os.path.relpath(OUT_PATH, ROOT))
    return fx


if __name__ == '__main__':
    main()
