"""Generate the runtime placement board from citylayout (board factory, item 1).

Unlike the other generators in this directory, this one emits PRODUCTION data,
not a test fixture: FPlacementBoard::Default() is what the live C++ game stands
on. It is generated for the same reason the tests are - the two built-in roads
and the fourteen pinned spans are derived at import from citylayout, which pulls
in city and parcelmeta, and porting that whole module is not this seat's job.
The board asks citylayout for the answers once, here, and they are compiled in.

THE SPANS CARRY THEIR KEYS. placement.PINNED_SPANS drops them - it only ever
needed (x0, x1, side) to answer "does this click cross a pin". Posing a pinned
lot needs the other direction, label -> span, so the keys come from
citylayout.lots directly.

Writes:
  Saved/SelfTest/board_data.json                      the record
  Source/StacktownAlpha/Private/StacktownBoardData.inl compiled into the game

  python3 Tools/oracle/gen_board_data.py
"""
import json
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.normpath(os.path.join(HERE, '..', '..'))
sys.path.insert(0, os.path.join(ROOT, 'Content', 'Python'))

import citylayout       # noqa: E402
import placement as P   # noqa: E402

JSON_OUT = os.path.join(ROOT, 'Saved', 'SelfTest', 'board_data.json')
INL_OUT = os.path.join(ROOT, 'Source', 'StacktownAlpha', 'Private',
                       'StacktownBoardData.inl')


def q(s):
    return 'TEXT("%s")' % s.replace('\\', '\\\\').replace('"', '\\"')


def n(v):
    return repr(float(v))


def main():
    # side comes from the block name's first letter, exactly as placement.py
    # derives it: NE/NW are north, SE/SW are south.
    spans = []
    for block in sorted(citylayout.blocks()):
        side = 'north' if block[0] == 'N' else 'south'
        for key, x0, x1, _corner in citylayout.lots(block):
            spans.append({'key': key, 'x0': x0, 'x1': x1, 'side': side})
    spans.sort(key=lambda s: s['key'])

    # CROSS-CHECK against placement.PINNED_SPANS, which is what the ported
    # refusal logic was tested against. If these two ever disagree the board the
    # game stands on is not the board the tests proved.
    mine = sorted((s['x0'], s['x1'], s['side']) for s in spans)
    theirs = sorted((a, b, c) for a, b, c in P.PINNED_SPANS)
    assert mine == theirs, ('keyed spans disagree with placement.PINNED_SPANS',
                            mine, theirs)

    data = {
        '_': 'GENERATED by Tools/oracle/gen_board_data.py from citylayout. '
             'Cross-checked against placement.PINNED_SPANS.',
        'roads': [dict(r) for r in P.ROADS],
        'pinned_spans': spans,
        'plate': {'x_min': P.PLATE_X_MIN, 'x_max': P.PLATE_X_MAX,
                  'y_min': P.PLATE_Y_MIN, 'y_max': P.PLATE_Y_MAX},
        'rules': {'position_quantum': P.POSITION_QUANTUM, 'v0_width': P.V0_WIDTH,
                  'v0_recipe': P.V0_RECIPE, 'pool_size': P.POOL_SIZE,
                  'road_half': P.ROAD_HALF, 'block_depth': P.BLOCK_DEPTH,
                  'road_max_reach': P.ROAD_MAX_REACH},
    }
    os.makedirs(os.path.dirname(JSON_OUT), exist_ok=True)
    with open(JSON_OUT, 'w') as f:
        json.dump(data, f, indent=2, sort_keys=True)

    L = []
    w = L.append
    w('// GENERATED by Tools/oracle/gen_board_data.py from Content/Python/citylayout.py.')
    w('// DO NOT HAND-EDIT - regenerate. This is PRODUCTION data: the board the live')
    w('// game stands on. Cross-checked at generation time against')
    w('// placement.PINNED_SPANS, so the board the game uses is the board the ported')
    w('// refusal logic was tested against.')
    w('//')
    w('//   python3 Tools/oracle/gen_board_data.py')
    w('#pragma once')
    w('')
    w('namespace Stacktown')
    w('{')
    w('namespace BoardData')
    w('{')
    w('struct FRoadRow { const TCHAR* Id; double StartX; double StartY; double EndX;')
    w('                  double EndY; const TCHAR* SidePlus; const TCHAR* SideMinus; bool bAxisX; };')
    w('struct FPinRow  { const TCHAR* Key; double X0; double X1; const TCHAR* Side; };')
    w('')
    w('inline const FRoadRow Roads[] = {')
    for r in data['roads']:
        w('\t{ %s, %s, %s, %s, %s, %s, %s, %s },' % (
            q(r['id']), n(r['start'][0]), n(r['start'][1]),
            n(r['end'][0]), n(r['end'][1]),
            q(r['side_plus']), q(r['side_minus']),
            'true' if r['axis'] == 'x' else 'false'))
    w('};')
    w('inline constexpr int32 RoadsNum = %d;' % len(data['roads']))
    w('')
    w('// The fourteen pinned lots, WITH their citylayout keys - the keys are what')
    w('// lets a pinned parcel find its own span and therefore its pose.')
    w('inline const FPinRow PinnedSpans[] = {')
    for s in spans:
        w('\t{ %s, %s, %s, %s },' % (q(s['key']), n(s['x0']), n(s['x1']), q(s['side'])))
    w('};')
    w('inline constexpr int32 PinnedSpansNum = %d;' % len(spans))
    w('')
    pl = data['plate']
    for key, name in (('x_min', 'PlateXMin'), ('x_max', 'PlateXMax'),
                      ('y_min', 'PlateYMin'), ('y_max', 'PlateYMax')):
        w('inline constexpr double %s = %s;' % (name, n(pl[key])))
    ru = data['rules']
    for key, name in (('position_quantum', 'PositionQuantum'), ('v0_width', 'V0Width'),
                      ('road_half', 'RoadHalf'), ('block_depth', 'BlockDepth'),
                      ('road_max_reach', 'RoadMaxReach')):
        w('inline constexpr double %s = %s;' % (name, n(ru[key])))
    w('inline constexpr int32 PoolSize = %d;' % ru['pool_size'])
    w('inline const TCHAR* const V0Recipe = %s;' % q(ru['v0_recipe']))
    w('')
    w('} // namespace BoardData')
    w('} // namespace Stacktown')

    with open(INL_OUT, 'w') as f:
        f.write('\n'.join(L) + '\n')
    print('wrote %s' % os.path.relpath(JSON_OUT, ROOT))
    print('wrote %s (%d spans, %d roads)'
          % (os.path.relpath(INL_OUT, ROOT), len(spans), len(data['roads'])))


if __name__ == '__main__':
    main()
