"""Golden oracle fixture for the C++ road port (Phase 1 step 4).

placement.py self-tests 28-39: the drawn-road half. Same discipline as the other
two generators - run the oracle over the exact scenarios the C++ replays and
record what it returned, so no expectation is ever retyped.

  python3 Tools/oracle/gen_roads_fixture.py
Writes Saved/SelfTest/roads_oracle.json. Never touches citystate.json.
"""
import json
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.normpath(os.path.join(HERE, '..', '..'))
sys.path.insert(0, os.path.join(ROOT, 'Content', 'Python'))

import citytick        # noqa: E402
import econrules       # noqa: E402
import placement as P  # noqa: E402

OUT_DIR = os.path.join(ROOT, 'Saved', 'SelfTest')
OUT_PATH = os.path.join(OUT_DIR, 'roads_oracle.json')


def seg(d):
    if d is None:
        return None
    return {'id': d['id'], 'start': list(d['start']), 'end': list(d['end']),
            'width_class': d['width_class']}


def cap_draw(state, x0, y0, x1, y1, pins_active=True, width_class='avenue'):
    ok, reason, road = P.resolve_road_draw(state, x0, y0, x1, y1, width_class,
                                           pins_active=pins_active)
    return {'x0': x0, 'y0': y0, 'x1': x1, 'y1': y1, 'width_class': width_class,
            'pins_active': pins_active, 'ok': ok, 'reason': reason,
            'road': seg(road)}


def cap_click(state, x, y, pins_active=True):
    ok, reason, lot = P.resolve_click(state, x, y, pins_active=pins_active)
    return {'x': x, 'y': y, 'pins_active': pins_active, 'ok': ok,
            'reason': reason, 'lot': lot}


GEOMETRY_MONEY = 1000.0


def funded():
    """seed_state with a balance the geometry cases cannot fail on.

    Roads cost money since road types (2026-09-06) and a 1400 uu avenue is $140
    against the $100 a fresh city starts with - so every case here that is about
    GEOMETRY is given a balance that cannot be the reason it refuses. The price
    itself is captured on its own, on a state left at money_start deliberately
    (t44 below). Mirrors placement.py's own funding note at self-test 31."""
    s = citytick.seed_state()
    s['money'] = GEOMETRY_MONEY
    return s


def main():
    fx = {
        '_': 'GENERATED by Tools/oracle/gen_roads_fixture.py from the Python '
             'oracle. Do not hand-edit: regenerate. Covers placement.py '
             'self-tests 28-48: the drawn-road half (step 4) and road '
             'types as mechanics (2026-09-06, MONDAY_DECISIONS section 2).',
        'MIN_ROAD_LENGTH': P.MIN_ROAD_LENGTH,
        'GEOMETRY_MONEY': GEOMETRY_MONEY,
    }

    # --- 28: lot_rect reduces to today's math for both built-ins -------------
    fx['t28_lot_rect'] = [
        {'lot': l, 'rect': list(P.lot_rect(l))}
        for l in ({'x0': 100.0, 'x1': 500.0, 'side': 'north', 'road_id': 'arterial'},
                  {'x0': 200.0, 'x1': 600.0, 'side': 'west', 'road_id': 'cross'})
    ]

    # --- 29: orientation is READ OFF the segment's own geometry --------------
    horiz = {'id': 'H', 'start': (0.0, 100.0), 'end': (500.0, 100.0),
             'width_class': 'avenue'}
    vert = {'id': 'V', 'start': (300.0, 0.0), 'end': (300.0, 900.0),
            'width_class': 'avenue'}
    fx['t29_road_dict'] = []
    for s in (horiz, vert):
        d = P._road_dict(s)
        fx['t29_road_dict'].append(
            {'segment': seg(s), 'side_plus': d['side_plus'],
             'side_minus': d['side_minus'], 'axis': d['axis']})

    # --- 30: _all_roads is the built-ins plus whatever has been drawn --------
    s30 = citytick.seed_state()
    before = [r['id'] for r in P._all_roads(s30)]
    s30['roads']['R1'] = {'id': 'R1', 'start': (0.0, 100.0),
                          'end': (500.0, 100.0), 'width_class': 'avenue'}
    after = [r['id'] for r in P._all_roads(s30)]
    fx['t30_all_roads'] = {'before': before, 'after': after,
                           'drawn': seg(s30['roads']['R1'])}

    # --- 31-37: every accept and every named refusal -------------------------
    s = funded()
    fx['t31_happy_horizontal'] = cap_draw(s, 6200.0, 3000.0, 7600.0, 3000.0)
    fx['t32_too_diagonal']     = cap_draw(s, 0.0, 3000.0, 1000.0, 3800.0)
    fx['t33_too_short']        = cap_draw(s, 6200.0, 3000.0, 6700.0, 3000.0)
    fx['t34_off_board']        = cap_draw(s, 7000.0, 3000.0, 8000.0, 3000.0)
    fx['t35_crosses_builtin']  = cap_draw(s, 6200.0, 0.0, 7600.0, 0.0)
    fx['t36_crosses_pin']      = cap_draw(s, 2000.0, 2900.0, 3000.0, 2900.0)
    fx['t36b_empty_mode']      = cap_draw(s, 2000.0, 2900.0, 3000.0, 2900.0,
                                          pins_active=False)
    fx['t37_happy_vertical']   = cap_draw(s, 3000.0, 3400.0, 3000.0, 4230.0)

    # --- ADDED BY THE PORT: the minor coordinate comes from the START --------
    # Every accepted road in cases 28-39 is drawn with its minor coordinate
    # already equal at both ends, so taking it from the END instead of the start
    # is invisible to all of them - a mutation proving that survived until this
    # existed. A near-horizontal drag is the case that separates them: dx=1400,
    # dy=50, so the horizontal rule wins and y must snap to the START's 3000,
    # not the end's 3050.
    fx['near_horizontal'] = cap_draw(s, 6200.0, 3000.0, 7600.0, 3050.0)
    fx['near_vertical']   = cap_draw(s, 3000.0, 3400.0, 3050.0, 4230.0)

    # --- 38: draw_road end to end, and R1/R2 sequencing ----------------------
    s38 = funded()
    s38, rid1, ok1, reason1 = P.draw_road(s38, 6200.0, 3000.0, 7600.0, 3000.0)
    crosses_r1 = cap_draw(s38, 6900.0, 2000.0, 6900.0, 4230.0)
    s38, rid2, ok2, reason2 = P.draw_road(s38, 3000.0, 3400.0, 3000.0, 4230.0)
    fx['t38_draw_road'] = {
        'first':  {'id': rid1, 'ok': ok1, 'reason': reason1,
                   'stored': seg(s38['roads'][rid1])},
        'crosses_r1': crosses_r1,
        'second': {'id': rid2, 'ok': ok2, 'reason': reason2,
                   'stored': seg(s38['roads'][rid2])},
        'ids': sorted(s38['roads'].keys()),
    }

    # --- 39: a lot placed AGAINST a drawn road, end to end -------------------
    s39 = funded()
    s39, _, _, _ = P.draw_road(s39, 6200.0, 3000.0, 7600.0, 3000.0)
    s39, pid39, ok39, reason39 = P.place(s39, 6900.0, 1700.0)
    lot39 = s39['parcels'][pid39]['placement'] if ok39 else None
    fx['t39_place_against_drawn'] = {
        'drawn': seg(s39['roads']['R1']),
        'click': [6900.0, 1700.0],
        'pid': pid39, 'ok': ok39, 'reason': reason39, 'lot': lot39,
        'rect': list(P.lot_rect(lot39, P._all_roads(s39))) if ok39 else None,
    }

    # ---- ROAD TYPES AS MECHANICS, self-tests 40-48 -------------------------
    # MONDAY_DECISIONS section 2's four types. Every value below comes OUT of
    # the oracle running the same scenarios the C++ replays; nothing is retyped.
    R = econrules.rules()
    fx['VERGE'] = P.VERGE
    fx['ROAD_TYPES'] = list(P.ROAD_TYPES)
    fx['DEFAULT_ROAD_TYPE'] = P.DEFAULT_ROAD_TYPE
    fx['road_highway_reach'] = R['road_highway_reach']

    # 40/41: the per-type table, as the oracle computes it - half, reach, cost
    # of a 1400 uu road, material name, and the four raw rules values.
    fx['t40_types'] = []
    for t in P.ROAD_TYPES:
        probe = {'id': 'X', 'start': (0.0, 0.0), 'end': (1400.0, 0.0),
                 'width_class': t}
        fx['t40_types'].append({
            'type': t,
            'cost_per_100uu': R['road_cost_per_100uu_%s' % t],
            'rent_mult': R['road_rent_mult_%s' % t],
            'width': R['road_width_%s' % t],
            'frontage': bool(R['road_frontage_%s' % t]),
            'half': P.road_half(probe, R),
            'max_reach': P.road_max_reach(probe, R),
            'cost_1400': P.road_cost(probe, R),
            'material': P.road_material_name(probe),
        })
    # A road with NO width class at all - both built-ins - is the avenue.
    fx['t40_untyped_half'] = P.road_half(P.ARTERIAL, R)
    fx['t40_untyped_reach'] = P.road_max_reach(P.ARTERIAL, R)
    fx['t41_length'] = [
        {'seg': seg({'id': 'X', 'start': (0.0, 100.0), 'end': (0.0, 1500.0),
                     'width_class': 'avenue'}),
         'length': P.road_length({'start': (0.0, 100.0), 'end': (0.0, 1500.0)})},
        {'seg': seg({'id': 'X', 'start': (0.0, 0.0), 'end': (700.0, 0.0),
                     'width_class': 'dirt'}),
         'length': 700.0,
         'cost': P.road_cost({'start': (0.0, 0.0), 'end': (700.0, 0.0),
                              'width_class': 'dirt'}, R)},
    ]

    # 42: the highway refuses frontage. The SAME segment drawn twice - as a
    # highway a click 2300 uu west of it is refused with a reason a player can
    # act on; as an avenue the identical click places a lot on its west side.
    HW = (7500.0, 1500.0, 7500.0, 4230.0)
    s42 = funded()
    s42, hid42, ok42, r42 = P.draw_road(s42, *HW, width_class='highway')
    s42c = funded()
    s42c, _, ok42c, _ = P.draw_road(s42c, *HW, width_class='avenue')
    fx['t42_frontage'] = {
        'segment': list(HW),
        'highway_drawn': {'id': hid42, 'ok': ok42, 'reason': r42,
                          'stored': seg(s42['roads'][hid42]) if ok42 else None,
                          'money_after': s42['money']},
        'avenue_drawn_ok': ok42c,
        'click_beside_highway': cap_click(s42, 5200.0, 3800.0),
        'click_beside_avenue': cap_click(s42c, 5200.0, 3800.0),
        'far_from_everything': cap_click(s42, -7000.0, -4000.0),
    }

    # 43: and nothing may be laid ACROSS one. An arterial north lot at x=7000
    # genuinely intersects that highway's corridor; the same click on a board
    # with no highway places normally.
    fx['t43_across_highway'] = {
        'with_highway': cap_click(s42, 7000.0, 1500.0),
        'without': cap_click(citytick.seed_state(), 7000.0, 1500.0),
    }

    # 44: roads cost money, on a state left at money_start deliberately.
    s44 = citytick.seed_state()
    money_before = s44['money']
    refuse44 = cap_draw(s44, 6200.0, 3000.0, 7600.0, 3000.0, width_class='avenue')
    s44, rid44a, ok44a, reason44a = P.draw_road(s44, 6200.0, 3000.0, 7600.0,
                                                3000.0, 'avenue')
    money_after_refusal = s44['money']
    s44, rid44, ok44, reason44 = P.draw_road(s44, 6200.0, 3000.0, 7600.0,
                                             3000.0, 'dirt')
    fx['t44_afford'] = {
        'money_start': money_before,
        'avenue_refused': refuse44,
        'refusal_spends_nothing': money_after_refusal,
        'dirt': {'id': rid44, 'ok': ok44, 'reason': reason44,
                 'stored': seg(s44['roads'][rid44]) if ok44 else None},
        'money_after': s44['money'],
    }

    # 45: a narrower road pulls its own frontage line in - the dirt road's
    # footprint and a lot on its south side, against the avenue's own numbers.
    fx['t45_dirt_frontage'] = {'road_rect': list(P.road_rect(
        P._road_dict(s44['roads'][rid44]), R))}
    s45 = funded()
    s45, _, ok45, reason45 = P.draw_road(s45, 6200.0, 3000.0, 7600.0, 3000.0,
                                         'dirt')
    s45, pid45, ok45b, reason45b = P.place(s45, 6900.0, 2000.0)
    fx['t45_dirt_frontage'].update({
        'click': [6900.0, 2000.0], 'pid': pid45, 'ok': ok45b,
        'reason': reason45b,
        'lot': s45['parcels'][pid45]['placement'] if ok45b else None,
        'rect': list(P.lot_rect(s45['parcels'][pid45]['placement'],
                                P._all_roads(s45), R)) if ok45b else None,
    })

    # 46: the rent multiplier. Synthetic states: the function is pure over
    # (state, lot), and hand-built adjacency is the only way to hit the 2,000 uu
    # edge from both sides.
    lot46 = {'x0': 6490.0, 'x1': 7310.0, 'side': 'south', 'road_id': 'D'}
    near_hw = {'id': 'HW', 'start': (7500.0, 1500.0), 'end': (7500.0, 4230.0),
               'width_class': 'highway'}
    far_hw = {'id': 'HW', 'start': (7500.0, -4230.0), 'end': (7500.0, -1500.0),
              'width_class': 'highway'}

    def s46(own_type, extra=None):
        roads = {'D': {'id': 'D', 'start': (6200.0, 3000.0),
                       'end': (7600.0, 3000.0), 'width_class': own_type}}
        if extra:
            roads['HW'] = dict(extra)
        return {'money': 0.0, 'parcels': {}, 'roads': roads}

    fx['t46_rent'] = []
    for own in P.ROAD_TYPES[:3]:
        fx['t46_rent'].append({'own': own, 'highway': None,
                               'mult': P.road_rent_multiplier(s46(own), lot46, R)})
    for label, hw in (('near', near_hw), ('far', far_hw)):
        fx['t46_rent'].append({
            'own': 'dirt', 'highway': label, 'highway_seg': seg(hw),
            'mult': P.road_rent_multiplier(s46('dirt', hw), lot46, R)})
    fx['t46_lot'] = lot46
    fx['t46_dirt_lot_rect'] = list(P.lot_rect(lot46, P._all_roads(s46('dirt')), R))
    fx['t46_far_distance'] = P._rect_distance(
        tuple(fx['t46_dirt_lot_rect']), P.road_rect(P._road_dict(far_hw), R))

    # 47: an unrecognised type is REFUSED at the boundary, with a reason.
    fx['t47_unknown'] = cap_draw(funded(), 6200.0, 3000.0, 7600.0, 3000.0,
                                 width_class='motorway')

    # 48: _in_crossing measures each road's OWN pavement. Direct, because no
    # state reachable through draw_road can have two corridors sharing ground -
    # see placement.py's own note at self-test 48 for why that is still right.
    cross_hw = P._road_dict({'id': 'HW', 'start': (7500.0, -4230.0),
                             'end': (7500.0, 4230.0), 'width_class': 'highway'})
    cross_av = dict(cross_hw, width_class='avenue')
    fx['t48_in_crossing'] = {
        'point': [6200.0, 500.0],
        'highway': P._in_crossing([P.ARTERIAL, cross_hw], 6200.0, 500.0, R),
        'avenue': P._in_crossing([P.ARTERIAL, cross_av], 6200.0, 500.0, R),
        'builtins_at_origin': P._in_crossing([P.ARTERIAL, P.CROSS_STREET],
                                             0.0, 0.0, R),
        'segment': seg({'id': 'HW', 'start': (7500.0, -4230.0),
                        'end': (7500.0, 4230.0), 'width_class': 'highway'}),
    }

    os.makedirs(OUT_DIR, exist_ok=True)
    with open(OUT_PATH, 'w') as f:
        json.dump(fx, f, indent=2, sort_keys=True)
    print('wrote %s' % os.path.relpath(OUT_PATH, ROOT))
    return fx


if __name__ == '__main__':
    main()
