"""Golden oracle fixture for the C++ road port (Phase 1 step 4).

placement.py self-tests 28-39: the drawn-road half. Same discipline as the other
two generators - run the oracle over the exact scenarios the C++ replays and
record what it returned, so no expectation is ever retyped.

  python3 Tools/oracle/gen_roads_fixture.py
Writes Saved/SelfTest/roads_oracle.json. Never touches citystate.json.
"""
import json
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.normpath(os.path.join(HERE, '..', '..'))
sys.path.insert(0, os.path.join(ROOT, 'Content', 'Python'))

import citytick        # noqa: E402
import placement as P  # noqa: E402

OUT_DIR = os.path.join(ROOT, 'Saved', 'SelfTest')
OUT_PATH = os.path.join(OUT_DIR, 'roads_oracle.json')


def seg(d):
    if d is None:
        return None
    return {'id': d['id'], 'start': list(d['start']), 'end': list(d['end']),
            'width_class': d['width_class']}


def cap_draw(state, x0, y0, x1, y1, pins_active=True, width_class='avenue'):
    ok, reason, road = P.resolve_road_draw(state, x0, y0, x1, y1, width_class,
                                           pins_active=pins_active)
    return {'x0': x0, 'y0': y0, 'x1': x1, 'y1': y1,
            'pins_active': pins_active, 'ok': ok, 'reason': reason,
            'road': seg(road)}


def main():
    fx = {
        '_': 'GENERATED by Tools/oracle/gen_roads_fixture.py from the Python '
             'oracle. Do not hand-edit: regenerate. Covers placement.py '
             'self-tests 28-39, the drawn-road half (step 4).',
        'MIN_ROAD_LENGTH': P.MIN_ROAD_LENGTH,
    }

    # --- 28: lot_rect reduces to today's math for both built-ins -------------
    fx['t28_lot_rect'] = [
        {'lot': l, 'rect': list(P.lot_rect(l))}
        for l in ({'x0': 100.0, 'x1': 500.0, 'side': 'north', 'road_id': 'arterial'},
                  {'x0': 200.0, 'x1': 600.0, 'side': 'west', 'road_id': 'cross'})
    ]

    # --- 29: orientation is READ OFF the segment's own geometry --------------
    horiz = {'id': 'H', 'start': (0.0, 100.0), 'end': (500.0, 100.0),
             'width_class': 'avenue'}
    vert = {'id': 'V', 'start': (300.0, 0.0), 'end': (300.0, 900.0),
            'width_class': 'avenue'}
    fx['t29_road_dict'] = []
    for s in (horiz, vert):
        d = P._road_dict(s)
        fx['t29_road_dict'].append(
            {'segment': seg(s), 'side_plus': d['side_plus'],
             'side_minus': d['side_minus'], 'axis': d['axis']})

    # --- 30: _all_roads is the built-ins plus whatever has been drawn --------
    s30 = citytick.seed_state()
    before = [r['id'] for r in P._all_roads(s30)]
    s30['roads']['R1'] = {'id': 'R1', 'start': (0.0, 100.0),
                          'end': (500.0, 100.0), 'width_class': 'avenue'}
    after = [r['id'] for r in P._all_roads(s30)]
    fx['t30_all_roads'] = {'before': before, 'after': after,
                           'drawn': seg(s30['roads']['R1'])}

    # --- 31-37: every accept and every named refusal -------------------------
    s = citytick.seed_state()
    fx['t31_happy_horizontal'] = cap_draw(s, 6200.0, 3000.0, 7600.0, 3000.0)
    fx['t32_too_diagonal']     = cap_draw(s, 0.0, 3000.0, 1000.0, 3800.0)
    fx['t33_too_short']        = cap_draw(s, 6200.0, 3000.0, 6700.0, 3000.0)
    fx['t34_off_board']        = cap_draw(s, 7000.0, 3000.0, 8000.0, 3000.0)
    fx['t35_crosses_builtin']  = cap_draw(s, 6200.0, 0.0, 7600.0, 0.0)
    fx['t36_crosses_pin']      = cap_draw(s, 2000.0, 2900.0, 3000.0, 2900.0)
    fx['t36b_empty_mode']      = cap_draw(s, 2000.0, 2900.0, 3000.0, 2900.0,
                                          pins_active=False)
    fx['t37_happy_vertical']   = cap_draw(s, 3000.0, 3400.0, 3000.0, 4230.0)

    # --- ADDED BY THE PORT: the minor coordinate comes from the START --------
    # Every accepted road in cases 28-39 is drawn with its minor coordinate
    # already equal at both ends, so taking it from the END instead of the start
    # is invisible to all of them - a mutation proving that survived until this
    # existed. A near-horizontal drag is the case that separates them: dx=1400,
    # dy=50, so the horizontal rule wins and y must snap to the START's 3000,
    # not the end's 3050.
    fx['near_horizontal'] = cap_draw(s, 6200.0, 3000.0, 7600.0, 3050.0)
    fx['near_vertical']   = cap_draw(s, 3000.0, 3400.0, 3050.0, 4230.0)

    # --- 38: draw_road end to end, and R1/R2 sequencing ----------------------
    s38 = citytick.seed_state()
    s38, rid1, ok1, reason1 = P.draw_road(s38, 6200.0, 3000.0, 7600.0, 3000.0)
    crosses_r1 = cap_draw(s38, 6900.0, 2000.0, 6900.0, 4230.0)
    s38, rid2, ok2, reason2 = P.draw_road(s38, 3000.0, 3400.0, 3000.0, 4230.0)
    fx['t38_draw_road'] = {
        'first':  {'id': rid1, 'ok': ok1, 'reason': reason1,
                   'stored': seg(s38['roads'][rid1])},
        'crosses_r1': crosses_r1,
        'second': {'id': rid2, 'ok': ok2, 'reason': reason2,
                   'stored': seg(s38['roads'][rid2])},
        'ids': sorted(s38['roads'].keys()),
    }

    # --- 39: a lot placed AGAINST a drawn road, end to end -------------------
    s39 = citytick.seed_state()
    s39, _, _, _ = P.draw_road(s39, 6200.0, 3000.0, 7600.0, 3000.0)
    s39, pid39, ok39, reason39 = P.place(s39, 6900.0, 1700.0)
    lot39 = s39['parcels'][pid39]['placement'] if ok39 else None
    fx['t39_place_against_drawn'] = {
        'drawn': seg(s39['roads']['R1']),
        'click': [6900.0, 1700.0],
        'pid': pid39, 'ok': ok39, 'reason': reason39, 'lot': lot39,
        'rect': list(P.lot_rect(lot39, P._all_roads(s39))) if ok39 else None,
    }

    os.makedirs(OUT_DIR, exist_ok=True)
    with open(OUT_PATH, 'w') as f:
        json.dump(fx, f, indent=2, sort_keys=True)
    print('wrote %s' % os.path.relpath(OUT_PATH, ROOT))
    return fx


if __name__ == '__main__':
    main()
