"""Generate the golden oracle fixture the C++ economy tests assert against.

ENGINEERING lane, Phase 1 step 1 (Docs/PLAN_CPP_PORT.md). The charter's step 4
is "compare with the Python oracle on the same saved state before you ask for
the Python side to be switched off". This script IS that comparison's input: it
runs econrules.py/citytick.py - the spec and oracle, unmodified - over the exact
scenarios the ported C++ tests replay, and writes what the oracle actually
returned.

The C++ tests therefore assert against numbers the ORACLE produced, not numbers
a porter re-typed from a comment. That is the difference between a port that is
checked and a port that agrees with its own arithmetic. Two of this project's
documented scars (HANDOFF section 5, "Measurement") are a check that asked the
wrong question and returned ok; a hand-copied expectation is exactly that shape.

Run from anywhere:  python3 Tools/oracle/gen_econ_fixture.py
Writes:             Saved/SelfTest/econ_oracle.json

Reads nothing under Content/ but the Python drivers and econrules.json, writes
nothing under Content/ at all (a JSON under Content/ triggers the editor's
auto-reimport - ENGINEERING_LANE.md), and never touches citystate.json.
"""
import json
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.normpath(os.path.join(HERE, '..', '..'))
sys.path.insert(0, os.path.join(ROOT, 'Content', 'Python'))

import econrules  # noqa: E402
import recipes    # noqa: E402

OUT_DIR = os.path.join(ROOT, 'Saved', 'SelfTest')
OUT_PATH = os.path.join(OUT_DIR, 'econ_oracle.json')


def parcel(rid, tier, width, owned=False, accum=0.0, failed=False,
           performance=econrules.PERFORMANCE_NEUTRAL):
    return {'rid': rid, 'tier': tier, 'width': width, 'owned': owned,
            'accum': accum, 'failed': failed, 'performance': performance}


def main():
    r = econrules.rules()
    fx = {
        '_': 'GENERATED by Tools/oracle/gen_econ_fixture.py from the Python '
             'oracle. Do not hand-edit: regenerate. Every number below is what '
             'econrules.py/citytick.py actually returned, not a transcription.',
        'rules': r,
    }

    # --- the catalogue surface the economy actually asks about ----------------
    # The economy only ever asks three questions of recipes.py. The C++ port
    # takes them through an injected catalogue interface rather than reaching
    # into a 1300-line catalogue it does not own (that is step 3's to port).
    fx['catalogue'] = {
        'tier_count': {rid: recipes.tier_count(rid)
                       for rid in ('vernacular', 'office', 'tower')},
        'asset_name': {
            'office_t0_w2050': recipes.asset_name('office', 0, 2050.0),
            'office_t1_w2050': recipes.asset_name('office', 1, 2050.0),
            'vernacular_t0_w1230': recipes.asset_name('vernacular', 0, 1230.0),
        },
        'asset_exists': {
            'office_t0_w2050': econrules.asset_exists('office', 0, 2050.0),
            'office_t1_w2050': econrules.asset_exists('office', 1, 2050.0),
        },
        # Exactly the baked meshes the ported tests can reach, asked of the
        # oracle rather than eyeballed off a directory listing. A test catalogue
        # built from this list answers every ladder question the way the real
        # Baked/ directory answered it on the day the fixture was generated -
        # and, unlike a directory scan, keeps answering that way after someone
        # bakes office_t1, which is the fragility the Python's own test 5
        # flagged in its comment and could not fix from where it stood.
        'baked_for_tests': sorted(
            recipes.asset_name(rid, t, w)
            for (rid, w) in (('vernacular', 1230.0), ('office', 2050.0))
            for t in range(recipes.tier_count(rid))
            if econrules.asset_exists(rid, t, w)),
    }

    # --- pure pricing functions ----------------------------------------------
    fx['price'] = [
        {'tier': t, 'width': w, 'expected': econrules.price('vernacular', t, w)}
        for (t, w) in ((0, 1230.0), (2, 1230.0), (0, 2050.0), (5, 860.0))
    ]
    fx['rent'] = [
        {'tier': t, 'demand': d, 'expected': econrules.rent('vernacular', t, d)}
        for (t, d) in ((2, 2.0), (0, 1.0), (3, 0.5), (0, 0.0))
    ]
    fx['climb'] = [{'tier': t, 'expected': econrules.climb(t)}
                   for t in (0, 1, 2, 3, 9)]
    fx['premium'] = [{'performance': p, 'expected': econrules.premium(p)}
                     for p in (0.0, 1.0, -0.5, -1.0, 0.25)]
    fx['upgrade_price'] = [
        {'tier': t, 'performance': p,
         'expected': econrules.upgrade_price('vernacular', t, p)}
        for (t, p) in ((0, 0.0), (1, 0.0), (3, 0.0), (0, -1.0), (2, -0.5))
    ]
    fx['repair_price'] = [{'tier': t, 'expected': econrules.repair_price(t)}
                          for t in (0, 1, 3)]

    # --- tier_up_allowed: every distinct refusal, by exact reason string ------
    fx['tier_up_allowed'] = []
    for (rid, tier, width) in (('office', 3, 2050.0), ('office', 0, 2050.0),
                               ('vernacular', 0, 1230.0), ('vernacular', 5, 1230.0)):
        ok, why = econrules.tier_up_allowed(rid, tier, width)
        fx['tier_up_allowed'].append(
            {'rid': rid, 'tier': tier, 'width': width, 'ok': ok, 'reason': why})

    # --- tick: the retirement claim, at 10 ticks and at 1000 -----------------
    def run_ticks(state, n):
        evs = []
        for _ in range(n):
            state, e = econrules.tick(state)
            evs += e
        return state, evs

    buy_start = {'money': 100.0, 'demand': 1.0,
                 'parcels': {'P1': parcel('vernacular', 0, 1230.0)}}
    bought, ok, why = econrules.buy(buy_start, 'P1')
    assert ok, why
    after10, evs10 = run_ticks(bought, 10)
    fx['buy_then_tick_10'] = {'after_buy_money': bought['money'],
                              'final': after10, 'events': evs10}

    st1000 = {'money': 0.0, 'demand': 1.0,
              'parcels': {'P1': parcel('vernacular', 0, 1230.0, owned=True)}}
    after1000, evs1000 = run_ticks(st1000, 1000)
    fx['tick_1000'] = {'final': after1000, 'events': evs1000}

    # the case that used to fire GROWTH_BLOCKED loudest: accum past the retired
    # threshold, next tier unbaked. One tick must now do nothing tier-related.
    st_of = {'money': 0.0, 'demand': 1.0,
             'parcels': {'OF': parcel('office', 0, 2050.0, owned=True, accum=39.9)}}
    of_after, of_evs = econrules.tick(st_of)
    fx['tick_retired_growth'] = {'final': of_after, 'events': of_evs}

    # multi-parcel tick: proves the sum and the deterministic iteration order.
    st_multi = {'money': 0.0, 'demand': 1.5, 'parcels': {
        'C': parcel('vernacular', 2, 1230.0, owned=True),
        'A': parcel('vernacular', 0, 1230.0, owned=True),
        'B': parcel('office', 1, 2050.0, owned=False),   # unowned: earns nothing
    }}
    multi_after, multi_evs = econrules.tick(st_multi)
    fx['tick_multi'] = {'final': multi_after, 'events': multi_evs}

    # --- the verbs: happy paths and every named refusal ----------------------
    def verb(fn, state, pid):
        s, ok, why = fn(json.loads(json.dumps(state)), pid)
        return {'ok': ok, 'reason': why, 'final': s}

    fx['buy'] = {
        'insufficient': verb(econrules.buy,
                             {'money': 1.0, 'demand': 1.0,
                              'parcels': {'P': parcel('vernacular', 0, 1230.0)}}, 'P'),
        'missing': verb(econrules.buy,
                        {'money': 100.0, 'demand': 1.0, 'parcels': {}}, 'NOPE'),
        'already': verb(econrules.buy,
                        {'money': 100.0, 'demand': 1.0,
                         'parcels': {'P': parcel('vernacular', 0, 1230.0, owned=True)}}, 'P'),
    }

    up_state = {'money': 1000.0, 'demand': 1.0, 'parcels': {
        'UNOWNED': parcel('vernacular', 0, 1230.0),
        'FAILED': parcel('vernacular', 0, 1230.0, owned=True, failed=True),
        'TOPPED': parcel('office', 3, 2050.0, owned=True),
        'UNBAKED': parcel('office', 0, 2050.0, owned=True),
        'WORST': parcel('vernacular', 0, 1230.0, owned=True, performance=-1.0),
    }}
    fx['upgrade'] = {k: verb(econrules.upgrade, up_state, k) for k in
                     ('UNOWNED', 'FAILED', 'TOPPED', 'UNBAKED', 'WORST', 'NOPE')}
    happy = {'money': 100.0, 'demand': 1.0,
             'parcels': {'P1': parcel('vernacular', 0, 1230.0, owned=True)}}
    fx['upgrade']['HAPPY'] = verb(econrules.upgrade, happy, 'P1')
    # climbed once, cannot afford the second (proves climb() multiplies)
    once, _, _ = econrules.upgrade(happy, 'P1')
    fx['upgrade']['CLIMB_REFUSES'] = verb(econrules.upgrade, once, 'P1')
    worst = {'money': 100.0, 'demand': 1.0,
             'parcels': {'P2': parcel('vernacular', 0, 1230.0, owned=True,
                                      performance=-1.0)}}
    fx['upgrade']['WORST_AFFORDS'] = verb(econrules.upgrade, worst, 'P2')

    rp_state = {'money': 1.0, 'demand': 1.0, 'parcels': {
        'UNOWNED': parcel('vernacular', 0, 1230.0),
        'FINE': parcel('vernacular', 0, 1230.0, owned=True),
        'POOR': parcel('vernacular', 0, 1230.0, owned=True, failed=True),
    }}
    fx['repair'] = {k: verb(econrules.repair, rp_state, k) for k in
                    ('UNOWNED', 'FINE', 'POOR', 'NOPE')}
    rp_happy = {'money': 150.0, 'demand': 1.0,
                'parcels': {'P1': parcel('vernacular', 1, 1230.0, owned=True,
                                         failed=True)}}
    fx['repair']['HAPPY'] = verb(econrules.repair, rp_happy, 'P1')

    # --- trade ledger --------------------------------------------------------
    fx['is_win'] = [{'pnl': p, 'expected': econrules.is_win({'pnl': p})}
                    for p in (5.0, -3.0, 0.0, 0.0001, -0.0001)]
    fx['trade_count_reward'] = [
        {'before': b, 'new': n, 'per_n': 10, 'amount': 20,
         'expected': econrules.trade_count_reward(b, n, 10, 20)}
        for (b, n) in ((0, 10), (9, 1), (5, 10), (0, 25), (10, 0), (0, 9), (0, 100))
    ]
    three = [{'pnl': 5.0}, {'pnl': -2.0}, {'pnl': 10.0}]
    fx['trade_outcome_bonus'] = [
        {'pnls': [t['pnl'] for t in three], 'bonus_per_win': 5,
         'expected': econrules.trade_outcome_bonus(three, 5)},
        {'pnls': [], 'bonus_per_win': 5,
         'expected': econrules.trade_outcome_bonus([], 5)},
    ]
    ledger = [{'pnl': p} for p in (10, -5, 3, -1, 8, -2, 0, 15, -3, 6, -4, 9)]
    s17 = {'money': 0.0, 'demand': 1.0, 'parcels': {}}
    s17, e17 = econrules.apply_trade_ledger(s17, ledger)
    s17b, e17b = econrules.apply_trade_ledger(json.loads(json.dumps(s17)), ledger)
    longer = ledger + [{'pnl': p} for p in (2, -1, 7)]
    s17c, e17c = econrules.apply_trade_ledger(json.loads(json.dumps(s17)), longer)
    fx['apply_trade_ledger'] = {
        'ledger': [t['pnl'] for t in ledger],
        'first': {'final': s17, 'events': e17},
        'idempotent_replay': {'final': s17b, 'events': e17b},
        'longer_ledger': {'pnls': [t['pnl'] for t in longer],
                          'final': s17c, 'events': e17c},
    }

    # --- citytick: the persistence boundary (the 9) --------------------------
    import citytick
    fx['seed_state'] = citytick.seed_state()

    os.makedirs(OUT_DIR, exist_ok=True)
    with open(OUT_PATH, 'w') as f:
        json.dump(fx, f, indent=2, sort_keys=True)
    print('wrote %s' % os.path.relpath(OUT_PATH, ROOT))
    return fx


if __name__ == '__main__':
    main()
