"""Generate the golden oracle fixture for the C++ placement port (Phase 1 step 2).

Same discipline as gen_econ_fixture.py: run Content/Python/placement.py - the
spec and oracle - over the exact scenarios the ported C++ tests replay, and
record what it actually returned. The C++ then asserts oracle output, not
numbers a porter retyped.

That is not a theoretical concern in this module. placement.py's own test
comments have drifted from its assertions twice: test 3 says "P1 spans
[-7380, -6560]" while test 1 asserts [-7410, -6590] (stale from the 410-snap
era), and test 20 says "x0=snap(2500-410)=snap(2090)=2050" while asserting
2090. The assertions are right and the comments are stale - which is exactly
why expectations get generated rather than read off a comment.

SCOPE: tests 1-27, the click -> lot -> state contract. Tests 28-39 (drawn
roads: _road_dict, resolve_road_draw, draw_road) belong to PLAN_CPP_PORT.md
step 4, not step 2, and are deliberately not captured here.

  python3 Tools/oracle/gen_placement_fixture.py
Writes Saved/SelfTest/placement_oracle.json. Reads Content/Python; writes
nothing there, and never touches citystate.json.
"""
import json
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.normpath(os.path.join(HERE, '..', '..'))
sys.path.insert(0, os.path.join(ROOT, 'Content', 'Python'))

import citylayout   # noqa: E402
import citytick     # noqa: E402
import econrules    # noqa: E402
import placement as P  # noqa: E402

OUT_DIR = os.path.join(ROOT, 'Saved', 'SelfTest')
OUT_PATH = os.path.join(OUT_DIR, 'placement_oracle.json')


def road_name(road):
    if road is None:
        return None
    return road['id']


def cap_resolve_road(roads, x, y):
    road, local = P.resolve_road(roads, x, y)
    return {'x': x, 'y': y, 'road': road_name(road),
            'along': None if local is None else local['along'],
            'across': None if local is None else local['across'],
            'side': None if local is None else local['side']}


def cap_click(state, x, y, pins_active=True, width=P.V0_WIDTH):
    ok, reason, lot = P.resolve_click(state, x, y, pins_active=pins_active,
                                      width=width)
    return {'x': x, 'y': y, 'pins_active': pins_active, 'width': width,
            'ok': ok, 'reason': reason, 'lot': lot}


def cap_place(state, x, y, pins_active=True, width=P.V0_WIDTH):
    st, pid, ok, reason = P.place(state, x, y, pins_active=pins_active,
                                  width=width)
    return st, {'x': x, 'y': y, 'pid': pid, 'ok': ok, 'reason': reason,
                'parcels': st['parcels']}


def main():
    fx = {
        '_': 'GENERATED by Tools/oracle/gen_placement_fixture.py from the '
             'Python oracle. Do not hand-edit: regenerate. Covers placement.py '
             'self-tests 1-27 (the click->lot->state contract). Tests 28-39 '
             '(drawn roads) are PLAN_CPP_PORT.md step 4, not step 2.',
    }

    # --- the board: constants and injected geometry -------------------------
    # PINNED_SPANS is derived at import from citylayout, which pulls in city
    # and parcelmeta. The economy port took the same shape for recipes: the
    # placement port needs the ANSWERS, not a second copy of the layout
    # module, so they are generated here and injected as data.
    fx['constants'] = {
        'WIDTH_QUANTUM': P.WIDTH_QUANTUM, 'POSITION_QUANTUM': P.POSITION_QUANTUM,
        'PLATE_X_MIN': P.PLATE_X_MIN, 'PLATE_X_MAX': P.PLATE_X_MAX,
        'PLATE_Y_MIN': P.PLATE_Y_MIN, 'PLATE_Y_MAX': P.PLATE_Y_MAX,
        'V0_WIDTH': P.V0_WIDTH, 'V0_RECIPE': P.V0_RECIPE,
        'POOL_SIZE': P.POOL_SIZE, 'ROAD_HALF': P.ROAD_HALF,
        'BLOCK_DEPTH': P.BLOCK_DEPTH, 'REACH_SLACK': P.REACH_SLACK,
        'VERGE': P.VERGE,
        'ROAD_MAX_REACH': P.ROAD_MAX_REACH,
        'PERFORMANCE_NEUTRAL': econrules.PERFORMANCE_NEUTRAL,
    }
    fx['roads'] = [dict(r) for r in P.ROADS]
    fx['pinned_spans'] = [list(s) for s in P.PINNED_SPANS]

    # test 7: containment, not equality - the plate must be at least as wide
    # as the blocks it contains. The board mesh's real bounds were measured in
    # the editor and cannot be re-derived here; this is the weaker honest check.
    xs = []
    for b in citylayout.blocks().values():
        x0, _y0, x1, _y1 = b['env']
        xs += [x0, x1]
    fx['block_env'] = {'x_min': min(xs), 'x_max': max(xs)}

    # --- 1-5: the placement sequence, carried state ------------------------
    s = citytick.seed_state()
    s, t1 = cap_place(s, -7000.0, 1500.0)
    fx['t1_first_place'] = t1
    _, t2 = cap_place(json.loads(json.dumps(s)), 8000.0, 0.0)
    fx['t2_off_board'] = t2
    _, t3 = cap_place(json.loads(json.dumps(s)), -7050.0, 1500.0)
    fx['t3_same_side_overlap'] = t3
    s4, t4 = cap_place(json.loads(json.dumps(s)), -7000.0, -1500.0)
    fx['t4_opposite_side'] = t4
    _, t5 = cap_place(json.loads(json.dumps(s4)), 7000.0, 1500.0)
    fx['t5_next_pid'] = t5

    # --- 6: place() produces ensure_parcel's shape plus exactly 'placement'
    pinned_state, _ = citytick.ensure_parcel(
        citytick.seed_state(), 'SW9', P.V0_RECIPE, 820,
        os.path.join(OUT_DIR, '_gen_throwaway.json'))
    fx['t6_shape'] = {
        'pinned_keys': sorted(pinned_state['parcels']['SW9']),
        'placed_keys': sorted(s['parcels']['P1']),
        'extra': sorted(set(s['parcels']['P1']) - set(pinned_state['parcels']['SW9'])),
    }
    throwaway = os.path.join(OUT_DIR, '_gen_throwaway.json')
    if os.path.exists(throwaway):
        os.remove(throwaway)

    # --- 8: pool exhaustion beats geometry ---------------------------------
    full = citytick.seed_state()
    for i in range(P.POOL_SIZE):
        full['parcels']['ZZ%d' % i] = {
            'rid': P.V0_RECIPE, 'tier': 0, 'width': P.V0_WIDTH, 'owned': False,
            'accum': 0.0,
            'placement': {'x0': 0.0, 'x1': 0.0, 'side': 'north'}}
    _, t8 = cap_place(full, 0.0, 1500.0)
    fx['t8_pool_exhausted'] = t8

    # --- the snap grid itself ----------------------------------------------
    # ADDED BY THE PORT, not one of the 27. Every click coordinate the Python's
    # own tests use happens to land on the 10 uu grid already, so a port that
    # TRUNCATED instead of rounding passed all 27 - the mutation proving that
    # survived until this was added. Python's round() is half-to-EVEN and the
    # snap is what fixes lot spans in JSON, so the tie-breaking rule is part of
    # the contract, not an implementation detail.
    fx['snap_cases'] = [{'in': v, 'expected': P._snap(v)} for v in
                        (2085.0, 2095.0, -2085.0, -2095.0, 5.0, 15.0, -5.0,
                         -15.0, 2091.0, 2099.0, -7413.0, -7415.0, 0.0)]
    # And the same rule reached through a real click, not just the helper: an
    # x whose half-width offset does NOT land on the grid.
    fx['snap_through_click'] = cap_click(citytick.seed_state(), -7003.0, 1500.0)
    fx['snap_through_click_half'] = cap_click(citytick.seed_state(), -7005.0, 1500.0)

    # --- 9, 10, 12: plan_reactivation --------------------------------------
    def cap_plan(pids, labels):
        # INPUTS ARE EMITTED IN THE ORDER GIVEN, deliberately unsorted. An
        # earlier version of this generator sorted them first, which handed the
        # C++ pre-sorted input and made plan_reactivation's own sort untestable -
        # deleting that sort survived every mutation. The Python's test passes a
        # SET here precisely because the ordering must not matter to the caller.
        pairs, unmatched = P.plan_reactivation(pids, labels)
        return {'pids': list(pids), 'labels': list(labels),
                'pairs': [list(p) for p in pairs], 'unmatched': unmatched}

    fx['t9_plan_enough'] = cap_plan(
        ['P1', 'P2', 'P3'],
        ['POOL_04', 'POOL_00', 'POOL_02', 'POOL_01', 'POOL_03'])
    fx['t10_plan_too_few'] = cap_plan(['P1', 'P2', 'P3'], ['POOL_00', 'POOL_01'])
    fx['t12_plan_generic'] = cap_plan(
        ['NE0', 'NE1', 'SW3'],
        ['POOL_PIN_NE0', 'POOL_PIN_NE1', 'POOL_PIN_SW3'])

    # --- 11 / 11b: the pinned-span check, and its mode gate ----------------
    fresh = citytick.seed_state()
    fx['t11_pinned_refuses'] = cap_click(fresh, 2360.0, 1500.0, pins_active=True)
    fx['t11b_empty_mode_accepts'] = cap_click(fresh, 2360.0, 1500.0, pins_active=False)

    # --- 13, 14: resolve_road reduces to today's math on each road alone ---
    fx['t13_arterial_alone'] = [
        cap_resolve_road([P.ARTERIAL], x, y)
        for (x, y) in ((-410.0, 1500.0), (-410.0, -1500.0),
                       (2360.0, 1500.0), (0.0, 50.0))]
    fx['t14_cross_alone'] = [
        cap_resolve_road([P.CROSS_STREET], x, y)
        for (x, y) in ((1500.0, -410.0), (-1500.0, -410.0), (1500.0, 2360.0))]

    # --- 15-19: nearest road, the crossing band, point-to-segment, reach ---
    fx['t15_nearest_wins'] = cap_resolve_road(P.ROADS, -410.0, 1500.0)
    fx['t16_crossing'] = [cap_resolve_road(P.ROADS, x, y) for (x, y) in
                          ((0.0, 0.0), (100.0, 100.0), (500.0, 500.0), (1000.0, 1000.0))]
    fx['t17_past_the_band'] = cap_resolve_road(P.ROADS, 2000.0, 2000.0)
    fx['t18_point_to_segment'] = cap_resolve_road(
        [P.ARTERIAL], P.PLATE_X_MAX + 5000.0, 0.0)
    fx['t19_too_far'] = [cap_resolve_road(P.ROADS, x, y) for (x, y) in
                         ((4671.0, 6954.0), (100000.0, 100000.0))]

    # --- 20, 21: the cross street's two sides ------------------------------
    s20 = citytick.seed_state()
    s20, t20 = cap_place(s20, -1500.0, 2500.0)
    fx['t20_cross_west'] = t20
    _, t21 = cap_place(json.loads(json.dumps(s20)), 1500.0, 2500.0)
    fx['t21_cross_east'] = t21

    # --- 22, 23, 24: in-the-road, per winning road, and the crossing -------
    fx['t22_in_road_arterial'] = cap_click(citytick.seed_state(), 3000.0, 500.0)
    fx['t23_in_road_cross'] = cap_click(citytick.seed_state(), 200.0, 3000.0)
    fx['t24_crossing_via_click'] = [
        cap_click(citytick.seed_state(), x, y) for (x, y) in
        ((0.0, 0.0), (100.0, 100.0), (500.0, 500.0), (1000.0, 1000.0))]

    # --- 25: lot_road_id's backward-compat default -------------------------
    fx['t25_lot_road_id'] = [
        {'lot': {'x0': 0.0, 'x1': 820.0, 'side': 'north'},
         'expected': P.lot_road_id({'x0': 0.0, 'x1': 820.0, 'side': 'north'})},
        {'lot': {'x0': 0.0, 'x1': 820.0, 'side': 'north', 'road_id': 'arterial'},
         'expected': P.lot_road_id({'x0': 0.0, 'x1': 820.0, 'side': 'north',
                                    'road_id': 'arterial'})},
        {'lot': {'x0': 0.0, 'x1': 820.0, 'side': 'west', 'road_id': 'cross'},
         'expected': P.lot_road_id({'x0': 0.0, 'x1': 820.0, 'side': 'west',
                                    'road_id': 'cross'})},
    ]

    # --- 26: survives a restart, legacy no-road_id lot included ------------
    s26 = citytick.seed_state()
    s26['parcels']['P1'] = {
        'rid': P.V0_RECIPE, 'tier': 2, 'width': P.V0_WIDTH, 'owned': True,
        'accum': 12.5,
        'placement': {'x0': 2050.0, 'x1': 2870.0, 'side': 'west',
                      'road_id': 'cross'}}
    s26['parcels']['P2'] = {
        'rid': P.V0_RECIPE, 'tier': 0, 'width': P.V0_WIDTH, 'owned': False,
        'accum': 0.0,
        'placement': {'x0': -7380.0, 'x1': -6560.0, 'side': 'north'}}
    rt_path = os.path.join(OUT_DIR, '_gen_roundtrip.json')
    citytick.save_state(s26, rt_path)
    loaded26 = citytick.load_state(rt_path)
    os.remove(rt_path)
    fx['t26_round_trip'] = {
        'before': s26,
        'after': loaded26,
        'p1_road_id': P.lot_road_id(loaded26['parcels']['P1']['placement']),
        'p2_has_road_id_key': 'road_id' in loaded26['parcels']['P2']['placement'],
        'p2_road_id': P.lot_road_id(loaded26['parcels']['P2']['placement']),
    }

    # --- overlap-scan determinism (ADDED BY THE PORT) -----------------------
    # The coordinator asked for a test that would catch an unsorted walk. In
    # tick() it cannot exist: rent is RentPerTier * (tier+1) * demand, the tier
    # spread is at most 7x, every value is exactly representable, and all 5040
    # orderings of the seven possible rents sum to exactly 21.0 - checked. So
    # tick()'s sort is defensive, not observable, and claiming a test proves it
    # would be false.
    #
    # The overlap scan IS observable: when TWO existing lots both overlap a
    # click, whichever is visited first is the one the refusal names. The Python
    # walks a dict in insertion order, so its message depends on the order lots
    # were added; the C++ sorts, so it always names the same one. That is a
    # deliberate divergence - a message that changes between runs is a message
    # nobody can act on. Captured here one lot at a time, so the expected
    # message is the oracle's own for whichever lot sorts first.
    def one_lot_state(pid, l):
        st = citytick.seed_state()
        st['parcels'][pid] = {
            'rid': P.V0_RECIPE, 'tier': 0, 'width': P.V0_WIDTH, 'owned': False,
            'placement': l}
        return st

    lot_a = {'x0': 1640.0, 'x1': 2460.0, 'side': 'north', 'road_id': 'arterial'}
    lot_b = {'x0': 1700.0, 'x1': 2520.0, 'side': 'north', 'road_id': 'arterial'}
    fx['overlap_order'] = {
        'lot_a': lot_a, 'lot_b': lot_b,
        'a_only': cap_click(one_lot_state('A', lot_a), 2000.0, 1500.0, pins_active=False),
        'b_only': cap_click(one_lot_state('B', lot_b), 2000.0, 1500.0, pins_active=False),
    }

    # --- 27: THE CORNER - world footprints, not per-road spans -------------
    s27 = citytick.seed_state()
    s27['parcels']['A'] = {
        'rid': P.V0_RECIPE, 'tier': 0, 'width': P.V0_WIDTH, 'owned': False,
        'placement': {'x0': 1640.0, 'x1': 2460.0, 'side': 'south',
                      'road_id': 'arterial'}}
    fx['t27_corner_cross_refused'] = cap_click(
        s27, 1500.0, -1900.0, pins_active=False)
    s27b = citytick.seed_state()
    s27b['parcels']['C'] = {
        'rid': P.V0_RECIPE, 'tier': 0, 'width': P.V0_WIDTH, 'owned': False,
        'placement': {'x0': -2460.0, 'x1': -1640.0, 'side': 'east',
                      'road_id': 'cross'}}
    fx['t27_corner_arterial_refused'] = cap_click(
        s27b, 1900.0, -1500.0, pins_active=False)
    fx['t27_lot_rects'] = [
        {'lot': s27['parcels']['A']['placement'],
         'rect': list(P.lot_rect(s27['parcels']['A']['placement']))},
        {'lot': s27b['parcels']['C']['placement'],
         'rect': list(P.lot_rect(s27b['parcels']['C']['placement']))},
    ]

    os.makedirs(OUT_DIR, exist_ok=True)
    with open(OUT_PATH, 'w') as f:
        json.dump(fx, f, indent=2, sort_keys=True)
    print('wrote %s' % os.path.relpath(OUT_PATH, ROOT))
    return fx


if __name__ == '__main__':
    main()
