// GENERATED by Tools/oracle/emit_fixture_inl.py from the Python oracle.
// DO NOT HAND-EDIT - regenerate. Every value below is what
// Content/Python/econrules.py and citytick.py actually returned when run,
// not a number transcribed from a comment. See the generator for why.
//
// Regenerate:
//   python3 Tools/oracle/gen_econ_fixture.py
//   python3 Tools/oracle/emit_fixture_inl.py
#pragma once

namespace StacktownOracle
{
// --- econrules.json, as the oracle read it -------------------------------
inline constexpr double MoneyStart = 100.0;
inline constexpr double PriceBase = 50.0;
inline constexpr double PricePer100uu = 2.0;
inline constexpr double PricePerTier = 25.0;
inline constexpr double RentPerTier = 0.75;
inline constexpr double GrowthThreshold = 40.0;
inline constexpr double DemandDefault = 1.0;
inline constexpr double DemandGain = 0.05;
inline constexpr double DemandLoss = 0.05;
inline constexpr double DemandRate = 0.1;
inline constexpr double DemandMin = 0.5;
inline constexpr double DemandMax = 2.0;
inline constexpr double WearTicksPerTier = 150.0;
inline constexpr double TradeCreditAmount = 20.0;
inline constexpr double TradeBonusPerWin = 5.0;
inline constexpr int32 TradeCreditsPerN = 10;

// --- the catalogue surface the economy asks about ------------------------
inline constexpr int32 TierCount_office = 4;
inline constexpr int32 TierCount_tower = 7;
inline constexpr int32 TierCount_vernacular = 6;
inline const TCHAR* const AssetName_office_t0_w2050 = TEXT("SM_Bld_office_t0_w2050");
inline const TCHAR* const AssetName_office_t1_w2050 = TEXT("SM_Bld_office_t1_w2050");
inline const TCHAR* const AssetName_vernacular_t0_w1230 = TEXT("SM_Bld_vernacular_t0_w1230");
inline constexpr bool AssetExists_office_t0_w2050 = true;
inline constexpr bool AssetExists_office_t1_w2050 = false;
// Every baked mesh the ported tests can reach, as the oracle saw it.
inline const TCHAR* const BakedForTests[] = {
	TEXT("SM_Bld_office_t0_w2050"),
	TEXT("SM_Bld_vernacular_t0_w1230"),
	TEXT("SM_Bld_vernacular_t1_w1230"),
	TEXT("SM_Bld_vernacular_t2_w1230"),
	TEXT("SM_Bld_vernacular_t3_w1230"),
	TEXT("SM_Bld_vernacular_t4_w1230"),
	TEXT("SM_Bld_vernacular_t5_w1230"),
};
inline constexpr int32 BakedForTestsNum = 7;

struct FTierWidthCase { int32 Tier; double Width; double Expected; };
inline const FTierWidthCase PriceCases[] = {
	{ 0, 1230.0, 74.6 },
	{ 2, 1230.0, 124.6 },
	{ 0, 2050.0, 91.0 },
	{ 5, 860.0, 192.2 },
};

struct FTierDemandCase { int32 Tier; double Demand; double Expected; };
inline const FTierDemandCase RentCases[] = {
	{ 2, 2.0, 4.5 },
	{ 0, 1.0, 0.75 },
	{ 3, 0.5, 1.5 },
	{ 0, 0.0, 0.0 },
};

struct FIntCase { int32 In; int32 Expected; };
inline const FIntCase ClimbCases[] = {
	{ 0, 1 },
	{ 1, 2 },
	{ 2, 3 },
	{ 3, 4 },
	{ 9, 10 },
};

struct FDoubleCase { double In; double Expected; };
inline const FDoubleCase PremiumCases[] = {
	{ 0.0, 1.0 },
	{ 1.0, 1.0 },
	{ -0.5, 1.5 },
	{ -1.0, 2.0 },
	{ 0.25, 1.0 },
};

struct FTierPerfCase { int32 Tier; double Performance; double Expected; };
inline const FTierPerfCase UpgradePriceCases[] = {
	{ 0, 0.0, 50.0 },
	{ 1, 0.0, 100.0 },
	{ 3, 0.0, 200.0 },
	{ 0, -1.0, 100.0 },
	{ 2, -0.5, 225.0 },
};

inline const FIntCase RepairPriceCases[] = {
	{ 0, 50 },
	{ 1, 100 },
	{ 3, 200 },
};

// --- tier_up_allowed: exact reason strings -------------------------------
struct FLadderCase { const TCHAR* Rid; int32 Tier; double Width; bool bOk; const TCHAR* Reason; };
inline const FLadderCase LadderCases[] = {
	{ TEXT("office"), 3, 2050.0, false, TEXT("top of ladder (office has 4 tiers)") },
	{ TEXT("office"), 0, 2050.0, false, TEXT("GROWTH BLOCKED: SM_Bld_office_t1_w2050 not baked") },
	{ TEXT("vernacular"), 0, 1230.0, true, TEXT("") },
	{ TEXT("vernacular"), 5, 1230.0, false, TEXT("top of ladder (vernacular has 6 tiers)") },
};

// --- verb refusals: exact reason strings ---------------------------------
inline const TCHAR* const Buy_already_Reason = TEXT("already owned");
inline constexpr bool Buy_already_Ok = false;
inline const TCHAR* const Buy_insufficient_Reason = TEXT("insufficient funds (1 < 75)");
inline constexpr bool Buy_insufficient_Ok = false;
inline const TCHAR* const Buy_missing_Reason = TEXT("no such parcel");
inline constexpr bool Buy_missing_Ok = false;
inline const TCHAR* const Upgrade_CLIMB_REFUSES_Reason = TEXT("insufficient funds (50 < 100)");
inline constexpr bool Upgrade_CLIMB_REFUSES_Ok = false;
inline const TCHAR* const Upgrade_FAILED_Reason = TEXT("failed: repair before upgrading");
inline constexpr bool Upgrade_FAILED_Ok = false;
inline const TCHAR* const Upgrade_HAPPY_Reason = TEXT("");
inline constexpr bool Upgrade_HAPPY_Ok = true;
inline const TCHAR* const Upgrade_NOPE_Reason = TEXT("no such parcel");
inline constexpr bool Upgrade_NOPE_Ok = false;
inline const TCHAR* const Upgrade_TOPPED_Reason = TEXT("top of ladder (office has 4 tiers)");
inline constexpr bool Upgrade_TOPPED_Ok = false;
inline const TCHAR* const Upgrade_UNBAKED_Reason = TEXT("GROWTH BLOCKED: SM_Bld_office_t1_w2050 not baked");
inline constexpr bool Upgrade_UNBAKED_Ok = false;
inline const TCHAR* const Upgrade_UNOWNED_Reason = TEXT("not owned");
inline constexpr bool Upgrade_UNOWNED_Ok = false;
inline const TCHAR* const Upgrade_WORST_Reason = TEXT("");
inline constexpr bool Upgrade_WORST_Ok = true;
inline const TCHAR* const Upgrade_WORST_AFFORDS_Reason = TEXT("");
inline constexpr bool Upgrade_WORST_AFFORDS_Ok = true;
inline const TCHAR* const Repair_FINE_Reason = TEXT("not failed");
inline constexpr bool Repair_FINE_Ok = false;
inline const TCHAR* const Repair_HAPPY_Reason = TEXT("");
inline constexpr bool Repair_HAPPY_Ok = true;
inline const TCHAR* const Repair_NOPE_Reason = TEXT("no such parcel");
inline constexpr bool Repair_NOPE_Ok = false;
inline const TCHAR* const Repair_POOR_Reason = TEXT("insufficient funds (1 < 50)");
inline constexpr bool Repair_POOR_Ok = false;
inline const TCHAR* const Repair_UNOWNED_Reason = TEXT("not owned");
inline constexpr bool Repair_UNOWNED_Ok = false;

// --- tick ----------------------------------------------------------------
inline constexpr double BuyThenTick10_AfterBuyMoney = 25.400000000000006;
inline constexpr double BuyThenTick10_Money = 33.03075441503751;
inline constexpr double BuyThenTick10_Accum = 7.630754415037499;
inline constexpr int32  BuyThenTick10_Tier  = 0;
inline constexpr int32  BuyThenTick10_Events = 0;
inline constexpr double Tick1000_Money = 117.75000005133431;
inline constexpr double Tick1000_Accum = 117.75000005133431;
inline constexpr int32  Tick1000_Tier  = 0;
inline constexpr int32  Tick1000_Events = 1;
inline constexpr double TickRetired_Money = 0.75;
inline constexpr double TickRetired_Accum = 40.65;
inline constexpr int32  TickRetired_Tier  = 0;
inline constexpr int32  TickRetired_Events = 0;
inline constexpr double TickMulti_DemandStart = 1.5;
inline constexpr double TickMulti_Demand = 1.455;
inline constexpr double TickMulti_Money = 4.5;
inline constexpr double TickMulti_Accum_A = 1.125;
inline constexpr double TickMulti_Accum_B = 0.0;
inline constexpr double TickMulti_Accum_C = 3.375;

// --- verb happy paths ----------------------------------------------------
inline constexpr double UpgradeHappy_Money = 50.0;
inline constexpr int32  UpgradeHappy_Tier = 1;
inline constexpr double UpgradeWorst_Money = 0.0;
inline constexpr int32  UpgradeWorst_Tier = 1;
inline constexpr double RepairHappy_Money = 50.0;
inline constexpr bool   RepairHappy_Failed = false;

// --- trade ledger --------------------------------------------------------
struct FPnlCase { double Pnl; bool bExpected; };
inline const FPnlCase IsWinCases[] = {
	{ 5.0, true },
	{ -3.0, false },
	{ 0.0, false },
	{ 0.0001, true },
	{ -0.0001, false },
};

struct FCountRewardCase { int32 Before; int32 New; int32 PerN; double Amount; double Expected; };
inline const FCountRewardCase CountRewardCases[] = {
	{ 0, 10, 10, 20.0, 20.0 },
	{ 9, 1, 10, 20.0, 20.0 },
	{ 5, 10, 10, 20.0, 20.0 },
	{ 0, 25, 10, 20.0, 40.0 },
	{ 10, 0, 10, 20.0, 0.0 },
	{ 0, 9, 10, 20.0, 0.0 },
	{ 0, 100, 10, 20.0, 200.0 },
};

inline const double LedgerPnls[] = { 10.0, -5.0, 3.0, -1.0, 8.0, -2.0, 0.0, 15.0, -3.0, 6.0, -4.0, 9.0 };
inline constexpr int32 LedgerPnlsNum = 12;
inline const double LedgerPnlsLonger[] = { 10.0, -5.0, 3.0, -1.0, 8.0, -2.0, 0.0, 15.0, -3.0, 6.0, -4.0, 9.0, 2.0, -1.0, 7.0 };
inline constexpr int32 LedgerPnlsLongerNum = 15;
inline constexpr double Ledger_Money = 50.0;
inline constexpr int32  Ledger_Processed = 12;
inline constexpr int32 LedgerEvents_First_Num = 2;
inline const TCHAR* const LedgerEvents_First_0_Kind = TEXT("TRADE_CREDITS");
inline constexpr double LedgerEvents_First_0_Amount = 20.0;
inline const TCHAR* const LedgerEvents_First_1_Kind = TEXT("TRADE_BONUS");
inline constexpr double LedgerEvents_First_1_Amount = 30.0;
inline constexpr int32 LedgerEvents_Replay_Num = 0;
inline constexpr int32 LedgerEvents_Longer_Num = 1;
inline const TCHAR* const LedgerEvents_Longer_0_Kind = TEXT("TRADE_BONUS");
inline constexpr double LedgerEvents_Longer_0_Amount = 10.0;
inline constexpr double LedgerLonger_Money = 60.0;
inline constexpr int32  LedgerLonger_Processed = 15;

// --- citytick seed -------------------------------------------------------
inline constexpr double Seed_Money = 100.0;
inline constexpr double Seed_Demand = 1.0;
inline constexpr int32  Seed_ParcelCount = 0;
inline const TCHAR* const Seed_RoadsJson = TEXT("{}");

} // namespace StacktownOracle
