// GENERATED by Tools/oracle/emit_placement_inl.py from the Python oracle.
// DO NOT HAND-EDIT - regenerate. Covers placement.py self-tests 1-27, the
// click -> lot -> state contract. Tests 28-39 (drawn roads) are step 4.
//
//   python3 Tools/oracle/gen_placement_fixture.py
//   python3 Tools/oracle/emit_placement_inl.py
#pragma once

namespace StacktownPlacementOracle
{
// A road_id of nullptr means the key is ABSENT from the lot, which is not
// the same as it being present and equal to "arterial".
struct FLotDef { double X0; double X1; const TCHAR* Side; const TCHAR* RoadId; };
struct FRoadDef { const TCHAR* Id; double StartX; double StartY; double EndX;
                  double EndY; const TCHAR* SidePlus; const TCHAR* SideMinus; bool bAxisX; };
struct FPinDef { double X0; double X1; const TCHAR* Side; };
struct FResolveCase { double X; double Y; const TCHAR* Road; double Along;
                      double Across; const TCHAR* Side; };
struct FClickCase { double X; double Y; bool bPinsActive; bool bOk;
                    const TCHAR* Reason; FLotDef Lot; };
struct FRect { double XMin; double XMax; double YMin; double YMax; };

inline constexpr double PositionQuantum = 10.0;
inline constexpr double V0Width = 820.0;
inline constexpr double WidthQuantum = 410.0;
inline constexpr double RoadHalf = 1130.0;
inline constexpr double BlockDepth = 1500.0;
inline constexpr double ReachSlack = 600.0;
inline constexpr double RoadMaxReach = 3230.0;
inline constexpr double Verge = 430.0;
inline constexpr double PlateXMin = -7650.0;
inline constexpr double PlateXMax = 7650.0;
inline constexpr double PlateYMin = -4230.0;
inline constexpr double PlateYMax = 4230.0;
inline constexpr double PerformanceNeutral = 0.0;
inline constexpr int32 PoolSize = 30;
inline const TCHAR* const V0Recipe = TEXT("vernacular");

// The two built-in roads, as the oracle declares them.
inline const FRoadDef Roads[] = {
	{ TEXT("arterial"), -7650.0, 0.0, 7650.0, 0.0, TEXT("north"), TEXT("south"), true },
	{ TEXT("cross"), 0.0, -4230.0, 0.0, 4230.0, TEXT("west"), TEXT("east"), false },
};
inline constexpr int32 RoadsNum = 2;

// PINNED_SPANS, derived at import from citylayout. Injected as data here:
// porting the layout module is step 3, and this port needs the answers.
inline const FPinDef PinnedSpans[] = {
	{ 1130.0, 3590.0, TEXT("north") },
	{ 3590.0, 4410.0, TEXT("north") },
	{ 4410.0, 6050.0, TEXT("north") },
	{ -6050.0, -4820.0, TEXT("north") },
	{ -4820.0, -3590.0, TEXT("north") },
	{ -3590.0, -2360.0, TEXT("north") },
	{ -2360.0, -1130.0, TEXT("north") },
	{ 1130.0, 3180.0, TEXT("south") },
	{ 3180.0, 4820.0, TEXT("south") },
	{ 4820.0, 6050.0, TEXT("south") },
	{ -6050.0, -4820.0, TEXT("south") },
	{ -4820.0, -4000.0, TEXT("south") },
	{ -4000.0, -2770.0, TEXT("south") },
	{ -2770.0, -1130.0, TEXT("south") },
};
inline constexpr int32 PinnedSpansNum = 14;

// Test 7: containment, not equality. The plate must be at least as wide as
// the blocks it contains; its real bounds were MEASURED off the board mesh
// in the editor and cannot be re-derived here.
inline constexpr double BlockEnvXMin = -6050.0;
inline constexpr double BlockEnvXMax = 6050.0;

// t1_first_place
inline constexpr double T1_X = -7000.0;
inline constexpr double T1_Y = 1500.0;
inline constexpr bool   T1_Ok = true;
inline const TCHAR* const T1_Pid = TEXT("P1");
inline const TCHAR* const T1_Reason = TEXT("");
inline const FLotDef T1_Lot = { -7410.0, -6590.0, TEXT("north"), TEXT("arterial") };
inline const TCHAR* const T1_Rid = TEXT("vernacular");
inline constexpr int32 T1_Tier = 0;
inline constexpr double T1_Width = 820.0;

// t2_off_board
inline constexpr double T2_X = 8000.0;
inline constexpr double T2_Y = 0.0;
inline constexpr bool   T2_Ok = false;
inline const TCHAR* const T2_Pid = nullptr;
inline const TCHAR* const T2_Reason = TEXT("off-board: snapped span [7590.0, 8410.0] exceeds the arterial road");

// t3_same_side_overlap
inline constexpr double T3_X = -7050.0;
inline constexpr double T3_Y = 1500.0;
inline constexpr bool   T3_Ok = false;
inline const TCHAR* const T3_Pid = nullptr;
inline const TCHAR* const T3_Reason = TEXT("overlap: [-7460.0, -6640.0] on the arterial crosses an existing lot at [-7410.0, -6590.0] on the arterial");

// t4_opposite_side
inline constexpr double T4_X = -7000.0;
inline constexpr double T4_Y = -1500.0;
inline constexpr bool   T4_Ok = true;
inline const TCHAR* const T4_Pid = TEXT("P2");
inline const TCHAR* const T4_Reason = TEXT("");
inline const FLotDef T4_Lot = { -7410.0, -6590.0, TEXT("south"), TEXT("arterial") };
inline const TCHAR* const T4_Rid = TEXT("vernacular");
inline constexpr int32 T4_Tier = 0;
inline constexpr double T4_Width = 820.0;

// t5_next_pid
inline constexpr double T5_X = 7000.0;
inline constexpr double T5_Y = 1500.0;
inline constexpr bool   T5_Ok = true;
inline const TCHAR* const T5_Pid = TEXT("P3");
inline const TCHAR* const T5_Reason = TEXT("");
inline const FLotDef T5_Lot = { 6590.0, 7410.0, TEXT("north"), TEXT("arterial") };
inline const TCHAR* const T5_Rid = TEXT("vernacular");
inline constexpr int32 T5_Tier = 0;
inline constexpr double T5_Width = 820.0;

// t8_pool_exhausted
inline constexpr double T8_X = 0.0;
inline constexpr double T8_Y = 1500.0;
inline constexpr bool   T8_Ok = false;
inline const TCHAR* const T8_Pid = nullptr;
inline const TCHAR* const T8_Reason = TEXT("pool exhausted: 30/30 placed lots already active");

// t20_cross_west
inline constexpr double T20_X = -1500.0;
inline constexpr double T20_Y = 2500.0;
inline constexpr bool   T20_Ok = true;
inline const TCHAR* const T20_Pid = TEXT("P1");
inline const TCHAR* const T20_Reason = TEXT("");
inline const FLotDef T20_Lot = { 2090.0, 2910.0, TEXT("west"), TEXT("cross") };
inline const TCHAR* const T20_Rid = TEXT("vernacular");
inline constexpr int32 T20_Tier = 0;
inline constexpr double T20_Width = 820.0;

// t21_cross_east
inline constexpr double T21_X = 1500.0;
inline constexpr double T21_Y = 2500.0;
inline constexpr bool   T21_Ok = true;
inline const TCHAR* const T21_Pid = TEXT("P2");
inline const TCHAR* const T21_Reason = TEXT("");
inline const FLotDef T21_Lot = { 2090.0, 2910.0, TEXT("east"), TEXT("cross") };
inline const TCHAR* const T21_Rid = TEXT("vernacular");
inline constexpr int32 T21_Tier = 0;
inline constexpr double T21_Width = 820.0;

// Test 6: place() yields EnsureParcel's shape plus exactly one key.
inline const TCHAR* const T6_ExtraKey = TEXT("placement");
inline constexpr int32 T6_ExtraCount = 1;

inline const FClickCase T11 = { 2360.0, 1500.0, true, false, TEXT("overlap: [1950.0, 2770.0] crosses a pinned lot at [1130.0, 3590.0]"), { 0.0, 0.0, nullptr, nullptr } };
inline const FClickCase T11b = { 2360.0, 1500.0, false, true, TEXT(""), { 1950.0, 2770.0, TEXT("north"), TEXT("arterial") } };
inline const FClickCase T22 = { 3000.0, 500.0, true, false, TEXT("in the road: |across|=500 is inside the arterial corridor (half 1130)"), { 0.0, 0.0, nullptr, nullptr } };
inline const FClickCase T23 = { 200.0, 3000.0, true, false, TEXT("in the road: |across|=200 is inside the cross corridor (half 1130)"), { 0.0, 0.0, nullptr, nullptr } };
inline const FClickCase T27Cross = { 1500.0, -1900.0, false, false, TEXT("overlap: [-2310.0, -1490.0] on the cross crosses an existing lot at [1640.0, 2460.0] on the arterial"), { 0.0, 0.0, nullptr, nullptr } };
inline const FClickCase T27Arterial = { 1900.0, -1500.0, false, false, TEXT("overlap: [1490.0, 2310.0] on the arterial crosses an existing lot at [-2460.0, -1640.0] on the cross"), { 0.0, 0.0, nullptr, nullptr } };

inline const FClickCase T24Crossing[] = {
	{ 0.0, 0.0, true, false, TEXT("in the crossing: (0.0, 0.0) is pavement shared by more than one road"), { 0.0, 0.0, nullptr, nullptr } },
	{ 100.0, 100.0, true, false, TEXT("in the crossing: (100.0, 100.0) is pavement shared by more than one road"), { 0.0, 0.0, nullptr, nullptr } },
	{ 500.0, 500.0, true, false, TEXT("in the crossing: (500.0, 500.0) is pavement shared by more than one road"), { 0.0, 0.0, nullptr, nullptr } },
	{ 1000.0, 1000.0, true, false, TEXT("in the crossing: (1000.0, 1000.0) is pavement shared by more than one road"), { 0.0, 0.0, nullptr, nullptr } },
};
inline constexpr int32 T24CrossingNum = 4;

inline const FResolveCase T13ArterialAlone[] = {
	{ -410.0, 1500.0, TEXT("arterial"), 7240.0, 1500.0, TEXT("north") },
	{ -410.0, -1500.0, TEXT("arterial"), 7240.0, -1500.0, TEXT("south") },
	{ 2360.0, 1500.0, TEXT("arterial"), 10010.0, 1500.0, TEXT("north") },
	{ 0.0, 50.0, TEXT("arterial"), 7650.0, 50.0, TEXT("north") },
};
inline constexpr int32 T13ArterialAloneNum = 4;
inline const FResolveCase T14CrossAlone[] = {
	{ 1500.0, -410.0, TEXT("cross"), 3820.0, -1500.0, TEXT("east") },
	{ -1500.0, -410.0, TEXT("cross"), 3820.0, 1500.0, TEXT("west") },
	{ 1500.0, 2360.0, TEXT("cross"), 6590.0, -1500.0, TEXT("east") },
};
inline constexpr int32 T14CrossAloneNum = 3;
inline const FResolveCase T16Crossing[] = {
	{ 0.0, 0.0, nullptr, 0.0, 0.0, nullptr },
	{ 100.0, 100.0, nullptr, 0.0, 0.0, nullptr },
	{ 500.0, 500.0, nullptr, 0.0, 0.0, nullptr },
	{ 1000.0, 1000.0, nullptr, 0.0, 0.0, nullptr },
};
inline constexpr int32 T16CrossingNum = 4;
inline const FResolveCase T19TooFar[] = {
	{ 4671.0, 6954.0, nullptr, 0.0, 0.0, nullptr },
	{ 100000.0, 100000.0, nullptr, 0.0, 0.0, nullptr },
};
inline constexpr int32 T19TooFarNum = 2;

inline const FResolveCase T15 = { -410.0, 1500.0, TEXT("cross"), 5730.0, 410.0, TEXT("west") };
inline const FResolveCase T17 = { 2000.0, 2000.0, TEXT("arterial"), 9650.0, 2000.0, TEXT("north") };
inline const FResolveCase T18 = { 12650.0, 0.0, nullptr, 0.0, 0.0, nullptr };

// ADDED BY THE PORT: the snap grid itself. Python's round() is
// half-to-EVEN, and no click coordinate in the 27 lands off the grid, so
// without these a port that TRUNCATED passed everything.
struct FSnapCase { double In; double Expected; };
inline const FSnapCase SnapCases[] = {
	{ 2085.0, 2080.0 },
	{ 2095.0, 2100.0 },
	{ -2085.0, -2080.0 },
	{ -2095.0, -2100.0 },
	{ 5.0, 0.0 },
	{ 15.0, 20.0 },
	{ -5.0, 0.0 },
	{ -15.0, -20.0 },
	{ 2091.0, 2090.0 },
	{ 2099.0, 2100.0 },
	{ -7413.0, -7410.0 },
	{ -7415.0, -7420.0 },
	{ 0.0, 0.0 },
};
inline constexpr int32 SnapCasesNum = 13;
inline const FClickCase SnapClick = { -7003.0, 1500.0, true, true, TEXT(""), { -7410.0, -6590.0, TEXT("north"), TEXT("arterial") } };
inline const FClickCase SnapClickHalf = { -7005.0, 1500.0, true, true, TEXT(""), { -7420.0, -6600.0, TEXT("north"), TEXT("arterial") } };

// Tests 9, 10, 12: plan_reactivation.
inline const TCHAR* const T9_Pids[] = { TEXT("P1"), TEXT("P2"), TEXT("P3") };
inline constexpr int32 T9_PidsNum = 3;
inline const TCHAR* const T9_Labels[] = { TEXT("POOL_04"), TEXT("POOL_00"), TEXT("POOL_02"), TEXT("POOL_01"), TEXT("POOL_03") };
inline constexpr int32 T9_LabelsNum = 5;
inline const TCHAR* const T9_PairPids[] = { TEXT("P1"), TEXT("P2"), TEXT("P3") };
inline const TCHAR* const T9_PairLabels[] = { TEXT("POOL_00"), TEXT("POOL_01"), TEXT("POOL_02") };
inline constexpr int32 T9_PairsNum = 3;
inline const TCHAR* const T9_Unmatched[] = { nullptr };
inline constexpr int32 T9_UnmatchedNum = 0;
inline const TCHAR* const T10_Pids[] = { TEXT("P1"), TEXT("P2"), TEXT("P3") };
inline constexpr int32 T10_PidsNum = 3;
inline const TCHAR* const T10_Labels[] = { TEXT("POOL_00"), TEXT("POOL_01") };
inline constexpr int32 T10_LabelsNum = 2;
inline const TCHAR* const T10_PairPids[] = { TEXT("P1"), TEXT("P2") };
inline const TCHAR* const T10_PairLabels[] = { TEXT("POOL_00"), TEXT("POOL_01") };
inline constexpr int32 T10_PairsNum = 2;
inline const TCHAR* const T10_Unmatched[] = { TEXT("P3") };
inline constexpr int32 T10_UnmatchedNum = 1;
inline const TCHAR* const T12_Pids[] = { TEXT("NE0"), TEXT("NE1"), TEXT("SW3") };
inline constexpr int32 T12_PidsNum = 3;
inline const TCHAR* const T12_Labels[] = { TEXT("POOL_PIN_NE0"), TEXT("POOL_PIN_NE1"), TEXT("POOL_PIN_SW3") };
inline constexpr int32 T12_LabelsNum = 3;
inline const TCHAR* const T12_PairPids[] = { TEXT("NE0"), TEXT("NE1"), TEXT("SW3") };
inline const TCHAR* const T12_PairLabels[] = { TEXT("POOL_PIN_NE0"), TEXT("POOL_PIN_NE1"), TEXT("POOL_PIN_SW3") };
inline constexpr int32 T12_PairsNum = 3;
inline const TCHAR* const T12_Unmatched[] = { nullptr };
inline constexpr int32 T12_UnmatchedNum = 0;

// Test 25: lot_road_id's backward-compatible default.
inline const FLotDef T25_Lots[] = {
	{ 0.0, 820.0, TEXT("north"), nullptr },
	{ 0.0, 820.0, TEXT("north"), TEXT("arterial") },
	{ 0.0, 820.0, TEXT("west"), TEXT("cross") },
};
inline const TCHAR* const T25_Expected[] = { TEXT("arterial"), TEXT("arterial"), TEXT("cross") };
inline constexpr int32 T25Num = 3;

// Test 26: survives a restart, including a LEGACY lot with no road_id.
inline const FLotDef T26_P1_Lot = { 2050.0, 2870.0, TEXT("west"), TEXT("cross") };
inline constexpr int32 T26_P1_Tier = 2;
inline constexpr bool T26_P1_Owned = true;
inline constexpr double T26_P1_Accum = 12.5;
inline const FLotDef T26_P2_Lot = { -7380.0, -6560.0, TEXT("north"), nullptr };
inline constexpr int32 T26_P2_Tier = 0;
inline constexpr bool T26_P2_Owned = false;
inline constexpr double T26_P2_Accum = 0.0;
inline const TCHAR* const T26_P1_RoadId = TEXT("cross");
inline constexpr bool T26_P2_HasRoadIdKey = false;
inline const TCHAR* const T26_P2_RoadId = TEXT("arterial");

// ADDED BY THE PORT: overlap-scan determinism. When two lots both overlap
// a click, the C++ SORTS and always names the same one; the Python walks
// insertion order. A refusal that changes between runs is unactionable.
inline const FLotDef OverlapLotA = { 1640.0, 2460.0, TEXT("north"), TEXT("arterial") };
inline const FLotDef OverlapLotB = { 1700.0, 2520.0, TEXT("north"), TEXT("arterial") };
inline const FClickCase OverlapAOnly = { 2000.0, 1500.0, false, false, TEXT("overlap: [1590.0, 2410.0] on the arterial crosses an existing lot at [1640.0, 2460.0] on the arterial"), { 0.0, 0.0, nullptr, nullptr } };
inline const FClickCase OverlapBOnly = { 2000.0, 1500.0, false, false, TEXT("overlap: [1590.0, 2410.0] on the arterial crosses an existing lot at [1700.0, 2520.0] on the arterial"), { 0.0, 0.0, nullptr, nullptr } };

// Test 27: the corner - world footprints, not per-road spans.
inline const FLotDef T27_Lot0 = { 1640.0, 2460.0, TEXT("south"), TEXT("arterial") };
inline const FRect T27_Rect0 = { 1640.0, 2460.0, -2630.0, -1130.0 };
inline const FLotDef T27_Lot1 = { -2460.0, -1640.0, TEXT("east"), TEXT("cross") };
inline const FRect T27_Rect1 = { 1130.0, 2630.0, -2460.0, -1640.0 };

} // namespace StacktownPlacementOracle
