// GENERATED by Tools/oracle/emit_roads_inl.py from the Python oracle.
// DO NOT HAND-EDIT - regenerate. Covers placement.py self-tests 28-39,
// the drawn-road half (Phase 1 step 4).
//
//   python3 Tools/oracle/gen_roads_fixture.py
//   python3 Tools/oracle/emit_roads_inl.py
#pragma once

namespace StacktownRoadsOracle
{
struct FSegDef { const TCHAR* Id; double StartX; double StartY;
                 double EndX; double EndY; const TCHAR* WidthClass; };
struct FDrawCase { double X0; double Y0; double X1; double Y1;
                   bool bPinsActive; bool bOk; const TCHAR* Reason; FSegDef Road; };
struct FRectDef { double XMin; double XMax; double YMin; double YMax; };
struct FLotDef2 { double X0; double X1; const TCHAR* Side; const TCHAR* RoadId; };

inline constexpr double MinRoadLength = 820.0;

// 28: lot_rect reduces to the old hard-coded constants for both built-ins.
inline const FLotDef2 T28_Lot0 = { 100.0, 500.0, TEXT("north"), TEXT("arterial") };
inline const FRectDef T28_Rect0 = { 100.0, 500.0, 1130.0, 2630.0 };
inline const FLotDef2 T28_Lot1 = { 200.0, 600.0, TEXT("west"), TEXT("cross") };
inline const FRectDef T28_Rect1 = { -2630.0, -1130.0, 200.0, 600.0 };

// 29: side conventions READ OFF the segment geometry, not stored.
struct FOrientCase { FSegDef Seg; const TCHAR* SidePlus; const TCHAR* SideMinus; bool bAxisX; };
inline const FOrientCase T29Orientation[] = {
	{ { TEXT("H"), 0.0, 100.0, 500.0, 100.0, TEXT("avenue") }, TEXT("north"), TEXT("south"), true },
	{ { TEXT("V"), 300.0, 0.0, 300.0, 900.0, TEXT("avenue") }, TEXT("west"), TEXT("east"), false },
};
inline constexpr int32 T29OrientationNum = 2;

// 30: the built-ins, plus whatever has been drawn.
inline const TCHAR* const T30_Before[] = { TEXT("arterial"), TEXT("cross") };
inline constexpr int32 T30_BeforeNum = 2;
inline const TCHAR* const T30_After[] = { TEXT("arterial"), TEXT("cross"), TEXT("R1") };
inline constexpr int32 T30_AfterNum = 3;
inline const FSegDef T30_Drawn = { TEXT("R1"), 0.0, 100.0, 500.0, 100.0, TEXT("avenue") };

// 31-37: every accept and every named refusal.
inline const FDrawCase T31 = { 6200.0, 3000.0, 7600.0, 3000.0, true, true, TEXT(""), { TEXT("R1"), 6200.0, 3000.0, 7600.0, 3000.0, TEXT("avenue") } };
inline const FDrawCase T32 = { 0.0, 3000.0, 1000.0, 3800.0, true, false, TEXT("too diagonal: roads must run close to north-south or east-west in this version"), { nullptr, 0.0, 0.0, 0.0, 0.0, nullptr } };
inline const FDrawCase T33 = { 6200.0, 3000.0, 6700.0, 3000.0, true, false, TEXT("too short: 500 uu is under the 820 uu a single lot needs"), { nullptr, 0.0, 0.0, 0.0, 0.0, nullptr } };
inline const FDrawCase T34 = { 7000.0, 3000.0, 8000.0, 3000.0, true, false, TEXT("off-board: the drawn road would leave the plate"), { nullptr, 0.0, 0.0, 0.0, 0.0, nullptr } };
inline const FDrawCase T35 = { 6200.0, 0.0, 7600.0, 0.0, true, false, TEXT("crosses: the drawn road would cross the arterial road"), { nullptr, 0.0, 0.0, 0.0, 0.0, nullptr } };
inline const FDrawCase T36 = { 2000.0, 2900.0, 3000.0, 2900.0, true, false, TEXT("overlap: the drawn road would cross a pinned lot at [1130.0, 3590.0]"), { nullptr, 0.0, 0.0, 0.0, 0.0, nullptr } };
inline const FDrawCase T36b = { 2000.0, 2900.0, 3000.0, 2900.0, false, true, TEXT(""), { TEXT("R1"), 2000.0, 2900.0, 3000.0, 2900.0, TEXT("avenue") } };
inline const FDrawCase T37 = { 3000.0, 3400.0, 3000.0, 4230.0, true, true, TEXT(""), { TEXT("R1"), 3000.0, 3400.0, 3000.0, 4230.0, TEXT("avenue") } };

// ADDED BY THE PORT: a near-axis drag snaps its minor coordinate to the
// START point. Every accepted road in 28-39 has equal ends, so nothing
// there separates start from end.
inline const FDrawCase NearHorizontal = { 6200.0, 3000.0, 7600.0, 3050.0, true, true, TEXT(""), { TEXT("R1"), 6200.0, 3000.0, 7600.0, 3000.0, TEXT("avenue") } };
inline const FDrawCase NearVertical = { 3000.0, 3400.0, 3050.0, 4230.0, true, true, TEXT(""), { TEXT("R1"), 3000.0, 3400.0, 3000.0, 4230.0, TEXT("avenue") } };

// 38: draw_road end to end, R1 then R2, and a refusal naming R1 itself.
inline const TCHAR* const T38_FirstId = TEXT("R1");
inline const FSegDef T38_FirstStored = { TEXT("R1"), 6200.0, 3000.0, 7600.0, 3000.0, TEXT("avenue") };
inline const TCHAR* const T38_SecondId = TEXT("R2");
inline const FSegDef T38_SecondStored = { TEXT("R2"), 3000.0, 3400.0, 3000.0, 4230.0, TEXT("avenue") };
inline const FDrawCase T38_CrossesR1 = { 6900.0, 2000.0, 6900.0, 4230.0, true, false, TEXT("crosses: the drawn road would cross the R1 road"), { nullptr, 0.0, 0.0, 0.0, 0.0, nullptr } };
inline const TCHAR* const T38_Ids[] = { TEXT("R1"), TEXT("R2") };
inline constexpr int32 T38_IdsNum = 2;

// 39: a lot placed AGAINST a drawn road, through place() itself.
inline const FSegDef T39_Drawn = { TEXT("R1"), 6200.0, 3000.0, 7600.0, 3000.0, TEXT("avenue") };
inline constexpr double T39_ClickX = 6900.0;
inline constexpr double T39_ClickY = 1700.0;
inline const TCHAR* const T39_Pid = TEXT("P1");
inline constexpr bool T39_Ok = true;
inline const FLotDef2 T39_Lot = { 6490.0, 7310.0, TEXT("south"), TEXT("R1") };
inline const FRectDef T39_Rect = { 6490.0, 7310.0, 370.0, 1870.0 };

} // namespace StacktownRoadsOracle
