// GENERATED by Tools/oracle/emit_roads_inl.py from the Python oracle.
// DO NOT HAND-EDIT - regenerate. Covers placement.py self-tests 28-48:
// the drawn-road half (Phase 1 step 4) and road types as mechanics.
//
//   python3 Tools/oracle/gen_roads_fixture.py
//   python3 Tools/oracle/emit_roads_inl.py
#pragma once

namespace StacktownRoadsOracle
{
struct FSegDef { const TCHAR* Id; double StartX; double StartY;
                 double EndX; double EndY; const TCHAR* WidthClass; };
struct FDrawCase { double X0; double Y0; double X1; double Y1;
                   bool bPinsActive; bool bOk; const TCHAR* Reason; FSegDef Road; };
struct FRectDef { double XMin; double XMax; double YMin; double YMax; };
struct FLotDef2 { double X0; double X1; const TCHAR* Side; const TCHAR* RoadId; };
struct FClickCase2 { double X; double Y; bool bPinsActive; bool bOk;
                     const TCHAR* Reason; FLotDef2 Lot; };
struct FTypeRow { const TCHAR* Type; double CostPer100uu; double RentMult;
                  double Width; bool bFrontage; double Half; double MaxReach;
                  double Cost1400; const TCHAR* Material; };
struct FRentCase { const TCHAR* Own; const TCHAR* Highway; double Mult; };

inline constexpr double MinRoadLength = 820.0;
// The balance every GEOMETRY case runs on. Roads cost money since road
// types, and a 1400 uu avenue is $140 against the $100 a fresh city
// starts with - so a case about geometry is given a balance that cannot
// be the reason it refuses. The price is tested on its own in 44.
inline constexpr double GeometryMoney = 1000.0;

// 28: lot_rect reduces to the old hard-coded constants for both built-ins.
inline const FLotDef2 T28_Lot0 = { 100.0, 500.0, TEXT("north"), TEXT("arterial") };
inline const FRectDef T28_Rect0 = { 100.0, 500.0, 1130.0, 2630.0 };
inline const FLotDef2 T28_Lot1 = { 200.0, 600.0, TEXT("west"), TEXT("cross") };
inline const FRectDef T28_Rect1 = { -2630.0, -1130.0, 200.0, 600.0 };

// 29: side conventions READ OFF the segment geometry, not stored.
struct FOrientCase { FSegDef Seg; const TCHAR* SidePlus; const TCHAR* SideMinus; bool bAxisX; };
inline const FOrientCase T29Orientation[] = {
	{ { TEXT("H"), 0.0, 100.0, 500.0, 100.0, TEXT("avenue") }, TEXT("north"), TEXT("south"), true },
	{ { TEXT("V"), 300.0, 0.0, 300.0, 900.0, TEXT("avenue") }, TEXT("west"), TEXT("east"), false },
};
inline constexpr int32 T29OrientationNum = 2;

// 30: the built-ins, plus whatever has been drawn.
inline const TCHAR* const T30_Before[] = { TEXT("arterial"), TEXT("cross") };
inline constexpr int32 T30_BeforeNum = 2;
inline const TCHAR* const T30_After[] = { TEXT("arterial"), TEXT("cross"), TEXT("R1") };
inline constexpr int32 T30_AfterNum = 3;
inline const FSegDef T30_Drawn = { TEXT("R1"), 0.0, 100.0, 500.0, 100.0, TEXT("avenue") };

// 31-37: every accept and every named refusal.
inline const FDrawCase T31 = { 6200.0, 3000.0, 7600.0, 3000.0, true, true, TEXT(""), { TEXT("R1"), 6200.0, 3000.0, 7600.0, 3000.0, TEXT("avenue") } };
inline const FDrawCase T32 = { 0.0, 3000.0, 1000.0, 3800.0, true, false, TEXT("too diagonal: roads must run close to north-south or east-west in this version"), { nullptr, 0.0, 0.0, 0.0, 0.0, nullptr } };
inline const FDrawCase T33 = { 6200.0, 3000.0, 6700.0, 3000.0, true, false, TEXT("too short: 500 uu is under the 820 uu a single lot needs"), { nullptr, 0.0, 0.0, 0.0, 0.0, nullptr } };
inline const FDrawCase T34 = { 7000.0, 3000.0, 8000.0, 3000.0, true, false, TEXT("off-board: the drawn road would leave the plate"), { nullptr, 0.0, 0.0, 0.0, 0.0, nullptr } };
inline const FDrawCase T35 = { 6200.0, 0.0, 7600.0, 0.0, true, false, TEXT("crosses: the drawn road would cross the arterial road"), { nullptr, 0.0, 0.0, 0.0, 0.0, nullptr } };
inline const FDrawCase T36 = { 2000.0, 2900.0, 3000.0, 2900.0, true, false, TEXT("overlap: the drawn road would cross a pinned lot at [1130.0, 3590.0]"), { nullptr, 0.0, 0.0, 0.0, 0.0, nullptr } };
inline const FDrawCase T36b = { 2000.0, 2900.0, 3000.0, 2900.0, false, true, TEXT(""), { TEXT("R1"), 2000.0, 2900.0, 3000.0, 2900.0, TEXT("avenue") } };
inline const FDrawCase T37 = { 3000.0, 3400.0, 3000.0, 4230.0, true, true, TEXT(""), { TEXT("R1"), 3000.0, 3400.0, 3000.0, 4230.0, TEXT("avenue") } };

// ADDED BY THE PORT: a near-axis drag snaps its minor coordinate to the
// START point. Every accepted road in 28-39 has equal ends, so nothing
// there separates start from end.
inline const FDrawCase NearHorizontal = { 6200.0, 3000.0, 7600.0, 3050.0, true, true, TEXT(""), { TEXT("R1"), 6200.0, 3000.0, 7600.0, 3000.0, TEXT("avenue") } };
inline const FDrawCase NearVertical = { 3000.0, 3400.0, 3050.0, 4230.0, true, true, TEXT(""), { TEXT("R1"), 3000.0, 3400.0, 3000.0, 4230.0, TEXT("avenue") } };

// 38: draw_road end to end, R1 then R2, and a refusal naming R1 itself.
inline const TCHAR* const T38_FirstId = TEXT("R1");
inline const FSegDef T38_FirstStored = { TEXT("R1"), 6200.0, 3000.0, 7600.0, 3000.0, TEXT("avenue") };
inline const TCHAR* const T38_SecondId = TEXT("R2");
inline const FSegDef T38_SecondStored = { TEXT("R2"), 3000.0, 3400.0, 3000.0, 4230.0, TEXT("avenue") };
inline const FDrawCase T38_CrossesR1 = { 6900.0, 2000.0, 6900.0, 4230.0, true, false, TEXT("crosses: the drawn road would cross the R1 road"), { nullptr, 0.0, 0.0, 0.0, 0.0, nullptr } };
inline const TCHAR* const T38_Ids[] = { TEXT("R1"), TEXT("R2") };
inline constexpr int32 T38_IdsNum = 2;

// 39: a lot placed AGAINST a drawn road, through place() itself.
inline const FSegDef T39_Drawn = { TEXT("R1"), 6200.0, 3000.0, 7600.0, 3000.0, TEXT("avenue") };
inline constexpr double T39_ClickX = 6900.0;
inline constexpr double T39_ClickY = 1700.0;
inline const TCHAR* const T39_Pid = TEXT("P1");
inline constexpr bool T39_Ok = true;
inline const FLotDef2 T39_Lot = { 6490.0, 7310.0, TEXT("south"), TEXT("R1") };
inline const FRectDef T39_Rect = { 6490.0, 7310.0, 370.0, 1870.0 };

// ---- ROAD TYPES AS MECHANICS, self-tests 40-48 -----------------------
// MONDAY_DECISIONS section 2. Every number below came out of the oracle
// running these exact scenarios; none of it was retyped.
inline constexpr double Verge = 430.0;
inline constexpr double HighwayReach = 2000.0;
// Named apart from Stacktown::DefaultRoadType()/RoadTypeNames() on purpose:
// a test brings both namespaces in, and the point is to COMPARE them.
inline const TCHAR* const OracleDefaultType = TEXT("avenue");
inline const TCHAR* const OracleTypeNames[] = { TEXT("dirt"), TEXT("avenue"), TEXT("boulevard"), TEXT("highway") };
inline constexpr int32 OracleTypeNamesNum = 4;

// 40/41: the per-type table as the oracle computes it.
inline const FTypeRow T40_Types[] = {
	{ TEXT("dirt"), 5.0, 0.75, 900.0, true, 880.0, 2980.0, 70.0, TEXT("MI_road_dirt") },
	{ TEXT("avenue"), 10.0, 1.0, 1400.0, true, 1130.0, 3230.0, 140.0, TEXT("MI_road_avenue") },
	{ TEXT("boulevard"), 20.0, 1.25, 1400.0, true, 1130.0, 3230.0, 280.0, TEXT("MI_road_boulevard") },
	{ TEXT("highway"), 30.0, 1.1, 2000.0, false, 1430.0, 3530.0, 420.0, TEXT("MI_road_highway") },
};
inline constexpr int32 T40_TypesNum = 4;
// A road with NO width class - both built-ins - IS the avenue.
inline constexpr double T40_UntypedHalf = 1130.0;
inline constexpr double T40_UntypedReach = 3230.0;
// A vertical 1400 uu run prices identically to a horizontal one.
inline const FSegDef T41_VerticalSeg = { TEXT("X"), 0.0, 100.0, 0.0, 1500.0, TEXT("avenue") };
inline constexpr double T41_VerticalLength = 1400.0;
inline const FSegDef T41_ShortDirtSeg = { TEXT("X"), 0.0, 0.0, 700.0, 0.0, TEXT("dirt") };
inline constexpr double T41_ShortDirtCost = 35.0;

// 42: the highway refuses frontage. The SAME segment drawn as each type.
inline constexpr double T42_Seg[] = { 7500.0, 1500.0, 7500.0, 4230.0 };
inline const FSegDef T42_HighwayStored = { TEXT("R1"), 7500.0, 1500.0, 7500.0, 4230.0, TEXT("highway") };
inline constexpr double T42_MoneyAfterHighway = 181.0;
inline const FClickCase2 T42_BesideHighway = { 5200.0, 3800.0, true, false, TEXT("no frontage: the R1 is a highway and nothing may face it"), { 0.0, 0.0, nullptr, nullptr } };
inline const FClickCase2 T42_BesideAvenue = { 5200.0, 3800.0, true, true, TEXT(""), { 3390.0, 4210.0, TEXT("west"), TEXT("R1") } };
inline const FClickCase2 T42_FarFromEverything = { -7000.0, -4000.0, true, false, TEXT("off-board: (-7000.0, -4000.0) is not within reach of any road"), { 0.0, 0.0, nullptr, nullptr } };

// 43: and nothing may be LAID ACROSS one.
inline const FClickCase2 T43_WithHighway = { 7000.0, 1500.0, true, false, TEXT("in the road: [6590.0, 7410.0] would run across the R1, a highway"), { 0.0, 0.0, nullptr, nullptr } };
inline const FClickCase2 T43_Without = { 7000.0, 1500.0, true, true, TEXT(""), { 6590.0, 7410.0, TEXT("north"), TEXT("arterial") } };

// 44: roads cost money, on a state left at money_start deliberately.
inline constexpr double T44_MoneyStart = 100.0;
inline const FDrawCase T44_AvenueRefused = { 6200.0, 3000.0, 7600.0, 3000.0, true, false, TEXT("can't afford: a 1400 uu avenue costs 140.00, money is 100.00"), { nullptr, 0.0, 0.0, 0.0, 0.0, nullptr } };
inline const TCHAR* const T44_AvenueClass = TEXT("avenue");
inline constexpr double T44_MoneyAfterRefusal = 100.0;
inline const FSegDef T44_DirtStored = { TEXT("R1"), 6200.0, 3000.0, 7600.0, 3000.0, TEXT("dirt") };
inline constexpr double T44_MoneyAfter = 30.0;

// 45: a narrower road pulls its own frontage line in.
inline const FRectDef T45_DirtRoadRect = { 6200.0, 7600.0, 2120.0, 3880.0 };
inline constexpr double T45_ClickX = 6900.0;
inline constexpr double T45_ClickY = 2000.0;
inline const FLotDef2 T45_Lot = { 6490.0, 7310.0, TEXT("south"), TEXT("R1") };
inline const FRectDef T45_LotRect = { 6490.0, 7310.0, 620.0, 2120.0 };

// 46: the rent multiplier - own type, then the highway proximity bonus,
// which MULTIPLIES, measured pavement to pad and bounded at 2,000 uu.
inline const FLotDef2 T46_Lot = { 6490.0, 7310.0, TEXT("south"), TEXT("D") };
inline const FRectDef T46_DirtLotRect = { 6490.0, 7310.0, 620.0, 2120.0 };
inline constexpr double T46_FarDistance = 2120.0;
inline const FSegDef T46_NearHighway = { TEXT("HW"), 7500.0, 1500.0, 7500.0, 4230.0, TEXT("highway") };
inline const FSegDef T46_FarHighway = { TEXT("HW"), 7500.0, -4230.0, 7500.0, -1500.0, TEXT("highway") };
inline const FRentCase T46_Cases[] = {
	{ TEXT("dirt"), nullptr, 0.75 },
	{ TEXT("avenue"), nullptr, 1.0 },
	{ TEXT("boulevard"), nullptr, 1.25 },
	{ TEXT("dirt"), TEXT("near"), 0.8250000000000001 },
	{ TEXT("dirt"), TEXT("far"), 0.75 },
};
inline constexpr int32 T46_CasesNum = 5;

// 47: an unrecognised type is refused at the boundary, with a reason.
inline const TCHAR* const T47_Class = TEXT("motorway");
inline const FDrawCase T47_Unknown = { 6200.0, 3000.0, 7600.0, 3000.0, true, false, TEXT("unknown road type 'motorway': expected one of dirt, avenue, boulevard, highway"), { nullptr, 0.0, 0.0, 0.0, 0.0, nullptr } };

// 48: _in_crossing measures each road's OWN pavement.
inline constexpr double T48_X = 6200.0;
inline constexpr double T48_Y = 500.0;
inline const FSegDef T48_Segment = { TEXT("HW"), 7500.0, -4230.0, 7500.0, 4230.0, TEXT("highway") };
inline constexpr bool T48_Highway = true;
inline constexpr bool T48_Avenue = false;
inline constexpr bool T48_BuiltinsAtOrigin = true;

} // namespace StacktownRoadsOracle
