// placement.py self-tests 28-39, ported: the drawn-road half (Phase 1 step 4).
//
//   UnrealEditor-Cmd <uproject> -ExecCmds="Automation RunTests Stacktown.Roads; Quit" \
//     -unattended -nopause -nullrhi -log
//
// This is the PURE RESOLVER only, which is the half the engineering seat owns.
// The road world side - POOL_ROAD actors and _road_transform - is the
// coordinator's engine work and is deliberately absent.
//
// Expectations come from RoadsOracleFixture.inl, generated by running
// placement.py, as in steps 1 and 2. Refusal reasons are asserted as exact
// strings, not the Python's substrings.

#include "Misc/AutomationTest.h"
#include "StacktownPlacementTestCommon.h"
#include "StacktownEconomyTestCommon.h"
#include "RoadsOracleFixture.inl"

#if WITH_DEV_AUTOMATION_TESTS

using namespace Stacktown;
using namespace StacktownTest;
using namespace StacktownRoadsOracle;

#define STACKTOWN_ROADS_TEST(TestClass, PrettyName) \
	IMPLEMENT_SIMPLE_AUTOMATION_TEST(TestClass, PrettyName, \
		EAutomationTestFlags::EditorContext | EAutomationTestFlags::ProductFilter) \
	bool TestClass::RunTest(const FString& Parameters)

namespace
{
	/** A fresh city with the balance every GEOMETRY case here runs on.
	 *
	 *  Roads cost money since road types (2026-09-06), and a 1400 uu avenue is
	 *  $140 against the $100 a fresh city starts with - so a case about geometry
	 *  is given a balance that cannot be the reason it refuses. The number is the
	 *  oracle's own (GeometryMoney), not a second copy chosen here, and its own
	 *  states were funded identically. The PRICE is tested on a state left at
	 *  money_start, in Stacktown.Roads.Afford. */
	FCityState RoadSeed()
	{
		FEconRules R = OracleRules();
		FCityState S = SeedState(R);
		S.Money = GeometryMoney;
		return S;
	}

	FLotPlacement LotFrom2(const FLotDef2& D)
	{
		FLotPlacement L;
		L.X0 = D.X0;
		L.X1 = D.X1;
		L.Side = FString(D.Side);
		if (D.RoadId != nullptr) { L.RoadId = FString(D.RoadId); }
		return L;
	}

	void CheckSeg(FAutomationTestBase& T, const TCHAR* What,
		const FString& GotId, const FRoadSegment& Got, const FSegDef& Want)
	{
		T.TestEqual(FString::Printf(TEXT("%s: id"), What), GotId, FString(Want.Id));
		T.TestEqual(FString::Printf(TEXT("%s: start x"), What), Got.StartX, Want.StartX, 1e-9);
		T.TestEqual(FString::Printf(TEXT("%s: start y"), What), Got.StartY, Want.StartY, 1e-9);
		T.TestEqual(FString::Printf(TEXT("%s: end x"), What), Got.EndX, Want.EndX, 1e-9);
		T.TestEqual(FString::Printf(TEXT("%s: end y"), What), Got.EndY, Want.EndY, 1e-9);
		T.TestEqual(FString::Printf(TEXT("%s: width class"), What),
			Got.WidthClass, FString(Want.WidthClass));
	}

	void CheckDraw(FAutomationTestBase& T, const TCHAR* What,
		const FPlacementBoard& Board, const FCityState& State, const FDrawCase& C)
	{
		const FRoadDrawResult R = ResolveRoadDraw(Board, State, C.X0, C.Y0, C.X1, C.Y1,
			TEXT("avenue"), C.bPinsActive);
		T.TestEqual(FString::Printf(TEXT("%s: ok"), What), BoolStr(R.bOk), BoolStr(C.bOk));
		T.TestEqual(FString::Printf(TEXT("%s: reason"), What), R.Reason, FString(C.Reason));
		if (C.bOk && C.Road.Id != nullptr)
		{
			CheckSeg(T, What, R.Id, R.Segment, C.Road);
		}
	}
}

// --- 28: lot_rect still reduces to the old constants for both built-ins ----------
STACKTOWN_ROADS_TEST(FStacktownRoadsLotRectReduces, "Stacktown.Roads.LotRectReduces")
{
	const FPlacementBoard Board = OracleBoard();
	const FRoad* Arterial = FindRoad(Board.Roads, TEXT("arterial"));
	const FRoad* Cross = FindRoad(Board.Roads, TEXT("cross"));
	TestNotNull(TEXT("arterial"), Arterial);
	TestNotNull(TEXT("cross"), Cross);
	if (Arterial == nullptr || Cross == nullptr) { return false; }

	// Both built-ins have centreline 0 in the relevant axis, so the generalized
	// axis lookup must reproduce exactly what this used to hard-code.
	const FLotRect R0 = LotRect(Board.Rules, Board.Econ, *Arterial, LotFrom2(T28_Lot0));
	TestEqual(TEXT("arterial xmin"), R0.XMin, T28_Rect0.XMin, 1e-9);
	TestEqual(TEXT("arterial xmax"), R0.XMax, T28_Rect0.XMax, 1e-9);
	TestEqual(TEXT("arterial ymin"), R0.YMin, T28_Rect0.YMin, 1e-9);
	TestEqual(TEXT("arterial ymax"), R0.YMax, T28_Rect0.YMax, 1e-9);

	const FLotRect R1 = LotRect(Board.Rules, Board.Econ, *Cross, LotFrom2(T28_Lot1));
	TestEqual(TEXT("cross xmin"), R1.XMin, T28_Rect1.XMin, 1e-9);
	TestEqual(TEXT("cross xmax"), R1.XMax, T28_Rect1.XMax, 1e-9);
	TestEqual(TEXT("cross ymin"), R1.YMin, T28_Rect1.YMin, 1e-9);
	TestEqual(TEXT("cross ymax"), R1.YMax, T28_Rect1.YMax, 1e-9);
	return true;
}

// --- 29: orientation is read off the geometry, never stored ----------------------
STACKTOWN_ROADS_TEST(FStacktownRoadsOrientation, "Stacktown.Roads.Orientation")
{
	for (int32 i = 0; i < T29OrientationNum; ++i)
	{
		const FOrientCase& C = T29Orientation[i];
		FRoadSegment Seg;
		Seg.StartX = C.Seg.StartX; Seg.StartY = C.Seg.StartY;
		Seg.EndX = C.Seg.EndX;     Seg.EndY = C.Seg.EndY;
		Seg.WidthClass = FString(C.Seg.WidthClass);
		const FRoad Road = RoadDictFromSegment(FString(C.Seg.Id), Seg);
		TestEqual(FString::Printf(TEXT("%s side_plus"), C.Seg.Id),
			Road.SidePlus, FString(C.SidePlus));
		TestEqual(FString::Printf(TEXT("%s side_minus"), C.Seg.Id),
			Road.SideMinus, FString(C.SideMinus));
		TestEqual(FString::Printf(TEXT("%s axis"), C.Seg.Id),
			BoolStr(Road.bAxisX), BoolStr(C.bAxisX));
	}
	return true;
}

// --- 30: the built-ins, then whatever has been drawn -----------------------------
STACKTOWN_ROADS_TEST(FStacktownRoadsAllRoads, "Stacktown.Roads.AllRoads")
{
	const FPlacementBoard Board = OracleBoard();
	FCityState S = RoadSeed();

	TArray<FRoad> Before = Board.AllRoads(S);
	TestEqual(TEXT("built-ins only on a fresh city"), Before.Num(), T30_BeforeNum);
	for (int32 i = 0; i < T30_BeforeNum && i < Before.Num(); ++i)
	{
		TestEqual(FString::Printf(TEXT("before %d"), i), Before[i].Id, FString(T30_Before[i]));
	}

	FRoadSegment Seg;
	Seg.StartX = T30_Drawn.StartX; Seg.StartY = T30_Drawn.StartY;
	Seg.EndX = T30_Drawn.EndX;     Seg.EndY = T30_Drawn.EndY;
	Seg.WidthClass = FString(T30_Drawn.WidthClass);
	S.Roads.Add(FString(T30_Drawn.Id), Seg);

	TArray<FRoad> After = Board.AllRoads(S);
	TestEqual(TEXT("drawn road joins the list"), After.Num(), T30_AfterNum);
	for (int32 i = 0; i < T30_AfterNum && i < After.Num(); ++i)
	{
		TestEqual(FString::Printf(TEXT("after %d"), i), After[i].Id, FString(T30_After[i]));
	}
	return true;
}

// ADDED BY THE PORT: id order is CREATION order, numerically. The Python gets
// this free from dict insertion order; a C++ port that reloads from JSON does
// not, and the order decides which road a crossing refusal names.
STACKTOWN_ROADS_TEST(FStacktownRoadsIdOrder, "Stacktown.Roads.IdOrder")
{
	TArray<FString> Ids = { TEXT("R10"), TEXT("R2"), TEXT("R1"), TEXT("R11") };
	SortRoadIds(Ids);
	TestEqual(TEXT("R1 first"),  Ids[0], FString(TEXT("R1")));
	TestEqual(TEXT("then R2"),   Ids[1], FString(TEXT("R2")));
	TestEqual(TEXT("then R10"),  Ids[2], FString(TEXT("R10")));
	TestEqual(TEXT("then R11"),  Ids[3], FString(TEXT("R11")));
	return true;
}

// --- 31-37: every accept and every named refusal ---------------------------------
STACKTOWN_ROADS_TEST(FStacktownRoadsDrawRules, "Stacktown.Roads.DrawRules")
{
	const FPlacementBoard Board = OracleBoard();
	const FCityState S = RoadSeed();

	CheckDraw(*this, TEXT("happy horizontal"), Board, S, T31);
	// WAS "too diagonal", until roads at any direction (2026-09-06, item 11)
	// removed that refusal. These coordinates still refuse - they start on the
	// cross street's own centreline - but for the reason they should, and the
	// fixture carries whichever reason the oracle gave. The gate opening is
	// asserted in Stacktown.Roads.DiagonalAccepted.
	CheckDraw(*this, TEXT("starts on the cross street"), Board, S, T32);
	CheckDraw(*this, TEXT("too short"), Board, S, T33);
	CheckDraw(*this, TEXT("off board"), Board, S, T34);
	CheckDraw(*this, TEXT("crosses a built-in"), Board, S, T35);
	// The pinned check is SEPARATE from the placed-lot scan, because a pin has
	// no placement and the lot loop skips every one of them by construction.
	CheckDraw(*this, TEXT("crosses a pin"), Board, S, T36);
	// The same coordinates in empty mode accept: the same mode gate the click
	// path has, extended rather than reinvented.
	CheckDraw(*this, TEXT("empty mode accepts"), Board, S, T36b);
	CheckDraw(*this, TEXT("happy vertical"), Board, S, T37);

	// ADDED BY THE PORT: the minor coordinate comes from the START point. Every
	// accepted road in 28-39 is drawn with equal ends, so taking it from the END
	// instead is invisible to all of them; a near-axis drag separates the two.
	CheckDraw(*this, TEXT("near horizontal snaps to the start's y"), Board, S, NearHorizontal);
	CheckDraw(*this, TEXT("near vertical snaps to the start's x"), Board, S, NearVertical);
	return true;
}

// --- 38: draw_road end to end, and R1/R2 sequencing -------------------------------
STACKTOWN_ROADS_TEST(FStacktownRoadsDrawRoad, "Stacktown.Roads.DrawRoad")
{
	const FPlacementBoard Board = OracleBoard();
	FCityState S = RoadSeed();

	const FRoadDrawResult First = DrawRoad(Board, S, T31.X0, T31.Y0, T31.X1, T31.Y1,
		TEXT("avenue"), true);
	TestTrue(TEXT("first draw succeeds"), First.bOk);
	TestEqual(TEXT("first id"), First.Id, FString(T38_FirstId));
	TestTrue(TEXT("stored"), S.Roads.Contains(First.Id));
	// Inserted UNCHANGED - the same segment that was validated, not re-derived.
	CheckSeg(*this, TEXT("stored R1"), First.Id, S.Roads[First.Id], T38_FirstStored);

	// A candidate crossing R1 SPECIFICALLY - clear of both built-in corridors,
	// so the refusal can only be about the drawn road, and must name it.
	CheckDraw(*this, TEXT("crosses R1"), Board, S, T38_CrossesR1);

	const FRoadDrawResult Second = DrawRoad(Board, S, T37.X0, T37.Y0, T37.X1, T37.Y1,
		TEXT("avenue"), true);
	TestTrue(TEXT("second draw succeeds"), Second.bOk);
	TestEqual(TEXT("second id sequences"), Second.Id, FString(T38_SecondId));
	CheckSeg(*this, TEXT("stored R2"), Second.Id, S.Roads[Second.Id], T38_SecondStored);
	TestEqual(TEXT("two roads stored"), S.Roads.Num(), T38_IdsNum);

	// A refused draw must store nothing.
	const int32 Before = S.Roads.Num();
	DrawRoad(Board, S, T32.X0, T32.Y0, T32.X1, T32.Y1, TEXT("avenue"), true);
	TestEqual(TEXT("a refused draw stores nothing"), S.Roads.Num(), Before);
	return true;
}

// --- 39: a lot placed AGAINST a drawn road, end to end -----------------------------
STACKTOWN_ROADS_TEST(FStacktownRoadsPlaceAgainstDrawn, "Stacktown.Roads.PlaceAgainstDrawn")
{
	const FPlacementBoard Board = OracleBoard();
	FCityState S = RoadSeed();

	// T39's OWN road, not 31's: 39 places a lot and so moved north on
	// 2026-09-07, when a lot stopped being allowed to overlap the arterial's
	// corridor. At y=3000 its south frontage band ran 760 uu into that
	// pavement - the lot was always in the road and nothing was looking.
	const FRoadDrawResult Drawn = DrawRoad(Board, S, T39_Drawn.StartX, T39_Drawn.StartY,
		T39_Drawn.EndX, T39_Drawn.EndY, FString(T39_Drawn.WidthClass), true);
	TestTrue(TEXT("road drawn"), Drawn.bOk);

	// The click path must resolve against a drawn road exactly as it does the
	// built-ins - that is the whole point of roads becoming dynamic.
	const FPlaceResult P = Place(Board, S, T39_ClickX, T39_ClickY, true, Board.Rules.V0Width);
	TestEqual(TEXT("placed"), BoolStr(P.bOk), BoolStr(T39_Ok));
	TestEqual(TEXT("pid"), P.Pid, FString(T39_Pid));

	const FLotPlacement& Lot = S.Parcels[FString(T39_Pid)].Placement.GetValue();
	TestEqual(TEXT("x0"), Lot.X0, T39_Lot.X0, 1e-9);
	TestEqual(TEXT("x1"), Lot.X1, T39_Lot.X1, 1e-9);
	TestEqual(TEXT("side"), Lot.Side, FString(T39_Lot.Side));
	// road_id is the DRAWN road's, not a built-in string.
	TestEqual(TEXT("road id"), LotRoadId(Lot), FString(T39_Lot.RoadId));

	// And the world footprint comes off that road's own start, proving the axis
	// generalization end to end rather than in isolation.
	const TArray<FRoad> Candidates = Board.AllRoads(S);
	const FRoad* R1 = FindRoad(Candidates, LotRoadId(Lot));
	TestNotNull(TEXT("the drawn road is in the candidate list"), R1);
	if (R1 != nullptr)
	{
		const FLotRect Rect = LotRect(Board.Rules, Board.Econ, *R1, Lot);
		TestEqual(TEXT("rect xmin"), Rect.XMin, T39_Rect.XMin, 1e-9);
		TestEqual(TEXT("rect xmax"), Rect.XMax, T39_Rect.XMax, 1e-9);
		TestEqual(TEXT("rect ymin"), Rect.YMin, T39_Rect.YMin, 1e-9);
		TestEqual(TEXT("rect ymax"), Rect.YMax, T39_Rect.YMax, 1e-9);
	}
	return true;
}

#undef STACKTOWN_ROADS_TEST

#endif // WITH_DEV_AUTOMATION_TESTS
