// CURVED MULTI-NODE ROADS - placement.py self-tests 56-60, ported. Item 11's
// second half, and ROADS_AS_MECHANIC section 5's own shape: a Catmull-Rom
// through the committed nodes, resampled at the 410 quantum into straight
// chords, drawn as ONE road.
//
//   UnrealEditor-Cmd <uproject> -ExecCmds="Automation RunTests Stacktown.Roads; Quit" \
//     -unattended -nopause -nullrhi -log
//
// THE PLAYER DRAWS ONE GESTURE AND GETS ONE ROAD. The chords are how a curve
// is stored and drawn, not what it is: one decision, one price, one path id.
// Everything downstream reads the path rather than the chord, and the reason
// that matters is in Stacktown.Roads.PathIsOneRoad - consecutive chords share
// an endpoint, so counting chords would make every joint of every curve "the
// crossing" and no lot could front a curve at all.
//
// Expectations come from RoadsOracleFixture.inl, generated by running
// placement.py over these exact scenarios.

#include "Misc/AutomationTest.h"
#include "StacktownPlacementTestCommon.h"
#include "StacktownEconomyTestCommon.h"
#include "RoadsOracleFixture.inl"

#if WITH_DEV_AUTOMATION_TESTS

using namespace Stacktown;
using namespace StacktownTest;
using namespace StacktownRoadsOracle;

#define STACKTOWN_PATH_TEST(TestClass, PrettyName) \
	IMPLEMENT_SIMPLE_AUTOMATION_TEST(TestClass, PrettyName, \
		EAutomationTestFlags::EditorContext | EAutomationTestFlags::ProductFilter) \
	bool TestClass::RunTest(const FString& Parameters)

namespace
{
	TArray<FVector2D> NodesOf(const FNode* Src, int32 Count)
	{
		TArray<FVector2D> Out;
		for (int32 i = 0; i < Count; ++i) { Out.Add(FVector2D(Src[i].X, Src[i].Y)); }
		return Out;
	}
	const FString Avenue(TEXT("avenue"));
}

// --- 56: the sampler ----------------------------------------------------------
STACKTOWN_PATH_TEST(FStacktownRoadPathSampler, "Stacktown.Roads.Sampler")
{
	// Vertex for vertex against the oracle: the arc-length resampling, the
	// merged leftover and the snap, all in one answer.
	//
	// ARC LENGTH, not parameter space - a Catmull-Rom's parameter runs faster
	// round the outside of a bend, so even-t sampling gives long chords through
	// corners, which is exactly where a chord's error against the curve is
	// largest. And the leftover is MERGED into the chord before it rather than
	// left as a stub: a 50 uu chord is a road segment with a 2260 uu corridor
	// and no length - a bump on the board and a hole in the frontage.
	const FPlacementBoard Board = OracleBoard();
	const TArray<FVector2D> Pts = SamplePath(Board.Rules, NodesOf(Curve, CurveNum),
		Board.Rules.WidthQuantum);
	TestEqual(TEXT("vertex count"), Pts.Num(), T56_SampledNum);
	for (int32 i = 0; i < Pts.Num() && i < T56_SampledNum; ++i)
	{
		TestEqual(TEXT("vertex x"), Pts[i].X, T56_Sampled[i].X, 1e-9);
		TestEqual(TEXT("vertex y"), Pts[i].Y, T56_Sampled[i].Y, 1e-9);
	}

	// Two nodes is a straight line through them, not a curve.
	const TArray<FVector2D> Str = SamplePath(Board.Rules,
		NodesOf(T56_StraightNodes, T56_StraightNodesNum), Board.Rules.WidthQuantum);
	TestEqual(TEXT("straight vertex count"), Str.Num(), T56_StraightNum);
	for (int32 i = 0; i < Str.Num() && i < T56_StraightNum; ++i)
	{
		TestEqual(TEXT("straight x"), Str[i].X, T56_Straight[i].X, 1e-9);
		TestEqual(TEXT("straight y"), Str[i].Y, T56_Straight[i].Y, 1e-9);
	}
	return true;
}

// --- 57 + 58: one gesture, one road ------------------------------------------
STACKTOWN_PATH_TEST(FStacktownRoadPathIsOneRoad, "Stacktown.Roads.PathIsOneRoad")
{
	const FPlacementBoard Board = OracleBoard();
	FEconRules Rules = OracleRules();
	FCityState S = SeedState(Rules);
	S.Money = T57_MoneyBefore;

	const FRoadPathResult D = DrawRoadPath(Board, S, NodesOf(Curve, CurveNum), Avenue, false);
	if (!TestTrue(TEXT("curve drawn"), D.bOk)) { return false; }
	TestEqual(TEXT("path id"), D.PathId, FString(T57_PathId));
	TestEqual(TEXT("chord count"), D.Segments.Num(), T57_IdsNum);
	// ONE PRICE, for the whole gesture, from the polyline's own length.
	TestEqual(TEXT("priced once"), S.Money, T57_MoneyAfter, 1e-9);
	for (int32 i = 0; i < D.Segments.Num() && i < T57_IdsNum; ++i)
	{
		const FString Id(T57_Ids[i]);
		if (!TestTrue(TEXT("chord in state"), S.Roads.Contains(Id))) { continue; }
		const FRoadSegment& Seg = S.Roads[Id];
		TestEqual(TEXT("chord start x"), Seg.StartX, T57_Segments[i].StartX, 1e-9);
		TestEqual(TEXT("chord start y"), Seg.StartY, T57_Segments[i].StartY, 1e-9);
		TestEqual(TEXT("chord end x"), Seg.EndX, T57_Segments[i].EndX, 1e-9);
		TestEqual(TEXT("chord end y"), Seg.EndY, T57_Segments[i].EndY, 1e-9);
		TestEqual(TEXT("chords share one path"), Seg.Path, FString(T57_Segments[i].Path));
	}

	// THE JOINTS. A shared endpoint has `along` in range for BOTH chords, so
	// counting chords in InCrossing would call every joint of every curve
	// "pavement shared by more than one road" - and there is one every 410 uu.
	// Counting PATHS is what makes a curve carry lots at all.
	const TArray<FRoad> Roads = Board.AllRoads(S);
	for (int32 j = 0; j < T58_JointsNum; ++j)
	{
		int32 Chords = 0;
		for (const FRoad& Rd : Roads)
		{
			const FRoadProjection Pr = ProjectToRoad(Rd, T58_Joints[j].X, T58_Joints[j].Y);
			if (Pr.Along >= 0.0 && Pr.Along <= Pr.Length
				&& FMath::Abs(Pr.Across) < RoadHalf(Board.Rules, Board.Econ, Rd))
			{
				++Chords;
			}
		}
		TestTrue(TEXT("the joint sits in more than one chord"), Chords > 1);
		TestFalse(TEXT("and is not the crossing"),
			InCrossing(Board.Rules, Board.Econ, Roads, T58_Joints[j].X, T58_Joints[j].Y));
	}

	// A LOT FRONTS THE CURVE, spanning the joined run rather than the one
	// chord - which it must: the curve is sampled at 410 and the narrowest lot
	// in the catalogue is 820, so before PathSpan every click on a curve was
	// refused with "off-board: snapped span exceeds the R3 road" on completely
	// open ground.
	const FClickResult CR = ResolveClick(Board, S, T58_ClickX, T58_ClickY,
		false, Board.Rules.V0Width);
	if (!TestTrue(TEXT("a lot fronts the curve"), CR.bOk)) { return false; }
	TestEqual(TEXT("lot x0"), CR.Lot.X0, T58_Lot.X0, 1e-9);
	TestEqual(TEXT("lot x1"), CR.Lot.X1, T58_Lot.X1, 1e-9);
	TestEqual(TEXT("lot road"), LotRoadId(CR.Lot), FString(T58_Lot.RoadId));
	const FRoad* Own = FindRoad(Roads, LotRoadId(CR.Lot));
	if (!TestNotNull(TEXT("own chord"), Own)) { return false; }
	const FRoadFrame F = RoadFrame(*Own);
	TestEqual(TEXT("chord length"), F.Length, T58_ChordLength, 1e-9);
	TestTrue(TEXT("the chord is shorter than a lot"), F.Length < Board.Rules.V0Width);
	double Lo = 0.0, Hi = 0.0;
	PathSpan(Roads, *Own, Lo, Hi);
	TestEqual(TEXT("span min"), Lo, T58_SpanMin, 1e-9);
	TestEqual(TEXT("span max"), Hi, T58_SpanMax, 1e-9);
	TestTrue(TEXT("the span is wider than the chord"), Hi - Lo > F.Length);
	return true;
}

// --- 59: one decision ---------------------------------------------------------
STACKTOWN_PATH_TEST(FStacktownRoadPathIsOneDecision, "Stacktown.Roads.PathIsOneDecision")
{
	const FPlacementBoard Board = OracleBoard();
	FEconRules Rules = OracleRules();

	// ANY chord failing refuses the WHOLE path, and nothing is added or spent.
	// A path that half-built where it first hit something would leave the
	// player a road they did not draw and a bill for it.
	FCityState S = SeedState(Rules);
	S.Money = 40000.0;
	const FRoadPathResult X = DrawRoadPath(Board, S,
		NodesOf(T59_Crosses_Nodes, T59_Crosses_NodesNum), Avenue, false);
	TestEqual(TEXT("refused"), BoolStr(X.bOk), BoolStr(T59_Crosses_Ok));
	TestEqual(TEXT("the reason names the road and the chord"), X.Reason,
		FString(T59_Crosses_Reason));
	TestEqual(TEXT("no segments handed back"), X.Segments.Num(), T59_CrossesSegments);
	TestEqual(TEXT("nothing spent"), S.Money, 40000.0, 1e-9);
	TestEqual(TEXT("no road added"), S.Roads.Num(), 0);

	// THE PRICE IS THE PATH'S, and checked at the boundary so a price that is
	// merely wrong is caught and not only one that is absent.
	FCityState Fresh = SeedState(Rules);
	const FRoadPathResult A = ResolveRoadPath(Board, Fresh, NodesOf(Curve, CurveNum),
		Avenue, false);
	TestEqual(TEXT("a fresh city cannot afford it"), BoolStr(A.bOk), BoolStr(T59_Afford_Ok));
	TestEqual(TEXT("and is told the price"), A.Reason, FString(T59_Afford_Reason));
	FCityState Under = SeedState(Rules);
	Under.Money = T59_Cost - 1.0;
	TestEqual(TEXT("one uu under refuses"),
		BoolStr(ResolveRoadPath(Board, Under, NodesOf(Curve, CurveNum), Avenue, false).bOk),
		BoolStr(T59_UnderOk));
	FCityState Exact = SeedState(Rules);
	Exact.Money = T59_Cost;
	const FRoadPathResult Ex = DrawRoadPath(Board, Exact, NodesOf(Curve, CurveNum),
		Avenue, false);
	TestEqual(TEXT("the exact quote draws"), BoolStr(Ex.bOk), BoolStr(T59_ExactOk));
	TestEqual(TEXT("and spends all of it"), Exact.Money, 0.0, 1e-6);

	// The boundary refusals, each with its own words.
	FCityState S2 = SeedState(Rules);
	S2.Money = 40000.0;
	const FRoadPathResult U = ResolveRoadPath(Board, S2, NodesOf(Curve, CurveNum),
		FString(TEXT("motorway")), false);
	TestEqual(TEXT("unknown type refused"), BoolStr(U.bOk), BoolStr(T59_Unknown_Ok));
	TestEqual(TEXT("unknown type reason"), U.Reason, FString(T59_Unknown_Reason));
	TArray<FVector2D> One;
	One.Add(FVector2D(0.0, 0.0));
	const FRoadPathResult O = ResolveRoadPath(Board, S2, One, Avenue, false);
	TestEqual(TEXT("one node refused"), BoolStr(O.bOk), BoolStr(T59_OneNode_Ok));
	TestEqual(TEXT("one node reason"), O.Reason, FString(T59_OneNode_Reason));
	// The MIN LENGTH is the path's, not each chord's: a 410 chord is under the
	// 820 a lot needs, and refusing every curve for that would measure the
	// wrong thing.
	const FRoadPathResult Sh = ResolveRoadPath(Board, S2,
		NodesOf(T59_TooShort_Nodes, T59_TooShort_NodesNum), Avenue, false);
	TestEqual(TEXT("too short refused"), BoolStr(Sh.bOk), BoolStr(T59_TooShort_Ok));
	TestEqual(TEXT("too short reason"), Sh.Reason, FString(T59_TooShort_Reason));

	// THE PLATE CHECK IS ON THE POLYLINE, not on the nodes. A Catmull-Rom
	// reaches past its own nodes on a bend, so nodes that are all inside the
	// plate are not a proof that the road is - here every node is on the plate
	// and the curve still leaves it.
	for (int32 i = 0; i < T59_Overshoot_NodesNum; ++i)
	{
		TestTrue(TEXT("node is on the plate"),
			T59_Overshoot_Nodes[i].Y >= T59_Overshoot_PlateYMin);
	}
	TestTrue(TEXT("and the curve is not"), T59_Overshoot_MinY < T59_Overshoot_PlateYMin);
	FCityState S3 = SeedState(Rules);
	S3.Money = 40000.0;
	const FRoadPathResult Ov = ResolveRoadPath(Board, S3,
		NodesOf(T59_Overshoot_Nodes, T59_Overshoot_NodesNum), Avenue, false);
	TestEqual(TEXT("overshoot refused"), BoolStr(Ov.bOk), BoolStr(T59_Overshoot_Ok));
	TestEqual(TEXT("overshoot reason"), Ov.Reason, FString(T59_Overshoot_Reason));

	// And a curve may not be drawn through a standing building.
	FCityState S4 = SeedState(Rules);
	S4.Money = 40000.0;
	const FPlaceResult PL = Place(Board, S4, T59_Lot_ClickX, T59_Lot_ClickY,
		false, Board.Rules.V0Width);
	TestTrue(TEXT("lot placed"), PL.bOk);
	const FRoadPathResult Th = ResolveRoadPath(Board, S4,
		NodesOf(T59_Lot_Nodes, T59_Lot_NodesNum), Avenue, false);
	TestEqual(TEXT("through a building refused"), BoolStr(Th.bOk), BoolStr(T59_Lot_Ok));
	TestEqual(TEXT("and names the lot"), Th.Reason, FString(T59_Lot_Reason));

	// TWO NODES IS A ROAD - the straight case through the same door, so the
	// path path is not a second, parallel way of drawing.
	FCityState S5 = SeedState(Rules);
	S5.Money = 40000.0;
	const FRoadPathResult Two = DrawRoadPath(Board, S5,
		NodesOf(T59_Two_Nodes, T59_Two_NodesNum), Avenue, false);
	TestTrue(TEXT("two nodes draw"), Two.bOk);
	TestEqual(TEXT("path id"), Two.PathId, FString(T59_Two_PathId));
	TestEqual(TEXT("chord count"), Two.Segments.Num(), T59_Two_Count);
	for (int32 i = 0; i < Two.Segments.Num() && i < T59_Two_Count; ++i)
	{
		TestEqual(TEXT("chord start x"), Two.Segments[i].StartX, T59_Two_Segments[i].StartX, 1e-9);
		TestEqual(TEXT("chord end x"), Two.Segments[i].EndX, T59_Two_Segments[i].EndX, 1e-9);
		TestEqual(TEXT("chord y"), Two.Segments[i].StartY, T59_Two_Segments[i].StartY, 1e-9);
	}
	return true;
}

#endif // WITH_DEV_AUTOMATION_TESTS
