// ROAD TYPES AS MECHANICS - placement.py self-tests 40-48, ported.
//
//   UnrealEditor-Cmd <uproject> -ExecCmds="Automation RunTests Stacktown.Roads; Quit" \
//     -unattended -nopause -nullrhi -log
//
// Docs/MONDAY_DECISIONS.md section 2 decided the four types on 2026-09-01 -
// dirt, paved avenue, tree-lined boulevard, highway, the highway REFUSING
// frontage - and left every NUMBER open. Docs/NIGHT_PLAN.md adopts that
// section's own PROPOSED table as tonight's working defaults, and they live in
// econrules.json, so the owner retunes any cell without touching code.
//
// THE TYPE IS THE WIDTH CLASS the segment already carried, and its one existing
// value, 'avenue', is already one of the four names - so no schema changed and
// no saved city needs migrating.
//
// Expectations come from RoadsOracleFixture.inl, generated by running
// placement.py over these exact scenarios. Refusal reasons are asserted as
// exact strings, not the Python's substrings: a player reads the reason.

#include "Misc/AutomationTest.h"
#include "StacktownPlacementTestCommon.h"
#include "StacktownEconomyTestCommon.h"
#include "RoadsOracleFixture.inl"

#if WITH_DEV_AUTOMATION_TESTS

using namespace Stacktown;
using namespace StacktownTest;
using namespace StacktownRoadsOracle;

#define STACKTOWN_TYPES_TEST(TestClass, PrettyName) \
	IMPLEMENT_SIMPLE_AUTOMATION_TEST(TestClass, PrettyName, \
		EAutomationTestFlags::EditorContext | EAutomationTestFlags::ProductFilter) \
	bool TestClass::RunTest(const FString& Parameters)

namespace
{
	/** A fresh city with the balance every GEOMETRY case here runs on. Roads
	 *  cost money now, and a 1400 uu avenue is $140 against the $100 a fresh
	 *  city starts with - so a case about geometry is given a balance that
	 *  cannot be the reason it refuses. The number is the oracle's own, and its
	 *  states were funded identically. The PRICE is tested on a state left at
	 *  money_start, in Stacktown.Roads.Afford below. */
	FCityState TypeSeed()
	{
		FEconRules R = OracleRules();
		FCityState S = SeedState(R);
		S.Money = GeometryMoney;
		return S;
	}

	FRoadSegment SegOf(const FSegDef& D)
	{
		FRoadSegment S;
		S.StartX = D.StartX; S.StartY = D.StartY;
		S.EndX   = D.EndX;   S.EndY   = D.EndY;
		if (D.WidthClass != nullptr) { S.WidthClass = FString(D.WidthClass); }
		return S;
	}
}

// --- the compiled default, against the owner's file ---------------------------
STACKTOWN_TYPES_TEST(FStacktownRoadTypeRulesMatchOracle, "Stacktown.Roads.TypeRulesMatchOracle")
{
	// FEconRules SHIPS the table it parses, so a board built without a ruleset
	// still measures the city rather than measuring nothing. That default is the
	// one thing here that could quietly drift from econrules.json, and this is
	// what stops it: the comparison is against values the oracle read out of the
	// file, not against a second copy typed into a test.
	const TMap<FString, FRoadTypeRules> Shipped = DefaultRoadTypes();
	const TArray<FString>& Names = RoadTypeNames();
	TestEqual(TEXT("four types"), Names.Num(), OracleTypeNamesNum);
	TestEqual(TEXT("default type"), FString(Stacktown::DefaultRoadType()), FString(OracleDefaultType));
	for (int32 i = 0; i < OracleTypeNamesNum && i < Names.Num(); ++i)
	{
		// ORDER matters: it is the T-key cycle in road mode.
		TestEqual(TEXT("type name in order"), Names[i], FString(OracleTypeNames[i]));
	}
	for (int32 i = 0; i < T40_TypesNum; ++i)
	{
		const FTypeRow& Row = T40_Types[i];
		const FRoadTypeRules* T = Shipped.Find(FString(Row.Type));
		if (!TestNotNull(*FString::Printf(TEXT("shipped table has %s"), Row.Type), T)) { continue; }
		TestEqual(TEXT("cost per 100uu"), T->CostPer100uu, Row.CostPer100uu, 1e-9);
		TestEqual(TEXT("rent multiplier"), T->RentMult, Row.RentMult, 1e-9);
		TestEqual(TEXT("carriageway"), T->Width, Row.Width, 1e-9);
		TestEqual(TEXT("frontage"), BoolStr(T->bFrontage), BoolStr(Row.bFrontage));
	}
	return true;
}

// --- 40: the per-type corridor, and the reduction that makes it safe ----------
STACKTOWN_TYPES_TEST(FStacktownRoadTypeGeometry, "Stacktown.Roads.TypeGeometry")
{
	const FPlacementBoard Board = OracleBoard();
	TestEqual(TEXT("verge"), Board.Rules.Verge, StacktownRoadsOracle::Verge, 1e-9);
	for (int32 i = 0; i < T40_TypesNum; ++i)
	{
		const FTypeRow& Row = T40_Types[i];
		FRoad Probe;
		Probe.WidthClass = FString(Row.Type);
		TestEqual(TEXT("type of"), RoadTypeOf(Probe), FString(Row.Type));
		TestEqual(TEXT("half"), Stacktown::RoadHalf(Board.Rules, Board.Econ, Probe), Row.Half, 1e-9);
		TestEqual(TEXT("max reach"), Stacktown::RoadMaxReach(Board.Rules, Board.Econ, Probe), Row.MaxReach, 1e-9);
		TestEqual(TEXT("corridor is twice the half"),
			RoadCorridor(Board.Rules, Board.Econ, Probe.WidthClass), 2.0 * Row.Half, 1e-9);
		TestEqual(TEXT("frontage"), BoolStr(RoadHasFrontage(Board.Econ, Probe)), BoolStr(Row.bFrontage));
		TestEqual(TEXT("material"), RoadMaterialName(Probe.WidthClass), FString(Row.Material));
	}

	// THE REDUCTION. An avenue - and a road with NO width class at all, which is
	// what both built-ins are - is EXACTLY the constant the board was authored
	// against, which is what keeps every test before this one measuring the same
	// board it always did.
	const FRoad* Arterial = FindRoad(Board.Roads, FString(TEXT("arterial")));
	if (!TestNotNull(TEXT("arterial"), Arterial)) { return false; }
	TestEqual(TEXT("no width class means avenue"), RoadTypeOf(*Arterial), FString(OracleDefaultType));
	TestEqual(TEXT("untyped half is the oracle's"),
		Stacktown::RoadHalf(Board.Rules, Board.Econ, *Arterial), T40_UntypedHalf, 1e-9);
	TestEqual(TEXT("untyped half IS Rules.RoadHalf"),
		Stacktown::RoadHalf(Board.Rules, Board.Econ, *Arterial), Board.Rules.RoadHalf, 1e-9);
	TestEqual(TEXT("untyped reach is the oracle's"),
		Stacktown::RoadMaxReach(Board.Rules, Board.Econ, *Arterial), T40_UntypedReach, 1e-9);
	TestEqual(TEXT("untyped reach IS Rules.RoadMaxReach"),
		Stacktown::RoadMaxReach(Board.Rules, Board.Econ, *Arterial), Board.Rules.RoadMaxReach, 1e-9);
	return true;
}

// --- 41: price is derived from type and geometry, never stored ----------------
STACKTOWN_TYPES_TEST(FStacktownRoadTypeCost, "Stacktown.Roads.TypeCost")
{
	const FPlacementBoard Board = OracleBoard();
	for (int32 i = 0; i < T40_TypesNum; ++i)
	{
		const FTypeRow& Row = T40_Types[i];
		FRoadSegment S;
		S.EndX = 1400.0;
		S.WidthClass = FString(Row.Type);
		TestEqual(TEXT("length"), RoadLength(S), 1400.0, 1e-9);
		double Cost = 0.0;
		TestTrue(TEXT("priced"), RoadCost(Board.Econ, S, Cost));
		TestEqual(TEXT("cost of a 1400 uu road"), Cost, Row.Cost1400, 1e-9);
	}
	// A vertical run prices identically to a horizontal one of the same span:
	// length is the centreline's, not a coordinate difference.
	double VCost = 0.0;
	TestEqual(TEXT("vertical length"), RoadLength(SegOf(T41_VerticalSeg)), T41_VerticalLength, 1e-9);
	TestTrue(TEXT("vertical priced"), RoadCost(Board.Econ, SegOf(T41_VerticalSeg), VCost));
	TestEqual(TEXT("vertical costs the same as horizontal"), VCost, T40_Types[1].Cost1400, 1e-9);
	double SCost = 0.0;
	TestTrue(TEXT("short dirt priced"), RoadCost(Board.Econ, SegOf(T41_ShortDirtSeg), SCost));
	TestEqual(TEXT("half the length, half the price"), SCost, T41_ShortDirtCost, 1e-9);
	return true;
}

// --- 42 + 43: the highway refuses frontage, and refuses to be built across ----
STACKTOWN_TYPES_TEST(FStacktownRoadHighwayFrontage, "Stacktown.Roads.HighwayRefusesFrontage")
{
	const FPlacementBoard Board = OracleBoard();

	// THE SAME SEGMENT drawn twice - as a highway and as an avenue - with one
	// click between them. Both built-ins are out of reach from that click, so
	// the drawn road is the only thing that can answer it, which is what makes
	// the pair a clean A/B rather than two coincidences.
	FCityState S = TypeSeed();
	const FRoadDrawResult D = DrawRoad(Board, S, T42_Seg[0], T42_Seg[1], T42_Seg[2], T42_Seg[3],
		FString(T42_HighwayStored.WidthClass), true);
	TestTrue(TEXT("highway drawn"), D.bOk);
	TestEqual(TEXT("stored width class"), S.Roads[D.Id].WidthClass, FString(T42_HighwayStored.WidthClass));
	TestEqual(TEXT("money after a highway"), S.Money, T42_MoneyAfterHighway, 1e-9);

	const FClickResult Beside = ResolveClick(Board, S, T42_BesideHighway.X, T42_BesideHighway.Y,
		T42_BesideHighway.bPinsActive, Board.Rules.V0Width);
	TestEqual(TEXT("refused"), BoolStr(Beside.bOk), BoolStr(T42_BesideHighway.bOk));
	// A refusal a player can ACT on. The generic answer is "not within reach of
	// any road", which is true and useless standing on a highway's verge.
	TestEqual(TEXT("reason names the road and its type"), Beside.Reason, FString(T42_BesideHighway.Reason));

	FCityState A = TypeSeed();
	const FRoadDrawResult AD = DrawRoad(Board, A, T42_Seg[0], T42_Seg[1], T42_Seg[2], T42_Seg[3],
		FString(TEXT("avenue")), true);
	TestTrue(TEXT("avenue drawn"), AD.bOk);
	const FClickResult OnAvenue = ResolveClick(Board, A, T42_BesideAvenue.X, T42_BesideAvenue.Y,
		T42_BesideAvenue.bPinsActive, Board.Rules.V0Width);
	TestEqual(TEXT("the identical click places"), BoolStr(OnAvenue.bOk), BoolStr(T42_BesideAvenue.bOk));
	TestEqual(TEXT("x0"), OnAvenue.Lot.X0, T42_BesideAvenue.Lot.X0, 1e-9);
	TestEqual(TEXT("x1"), OnAvenue.Lot.X1, T42_BesideAvenue.Lot.X1, 1e-9);
	TestEqual(TEXT("side"), OnAvenue.Lot.Side, FString(T42_BesideAvenue.Lot.Side));
	TestEqual(TEXT("road"), LotRoadId(OnAvenue.Lot), FString(T42_BesideAvenue.Lot.RoadId));

	// 'no frontage' is bounded by the highway's OWN reach, not handed out
	// board-wide: a click outside every road's reach still gets 'off-board'.
	const FClickResult Far = ResolveClick(Board, S, T42_FarFromEverything.X, T42_FarFromEverything.Y,
		T42_FarFromEverything.bPinsActive, Board.Rules.V0Width);
	TestEqual(TEXT("far refused"), BoolStr(Far.bOk), BoolStr(T42_FarFromEverything.bOk));
	TestEqual(TEXT("far reason is off-board"), Far.Reason, FString(T42_FarFromEverything.Reason));

	// 43: refusing frontage is not enough on its own. Every other refusal in
	// ResolveClick is reached THROUGH the road a lot faces, so a road nothing
	// may face is unguarded by construction - a lot fronting the arterial can
	// still be laid straight across two thousand uu of motorway.
	const FClickResult Across = ResolveClick(Board, S, T43_WithHighway.X, T43_WithHighway.Y,
		T43_WithHighway.bPinsActive, Board.Rules.V0Width);
	TestEqual(TEXT("across refused"), BoolStr(Across.bOk), BoolStr(T43_WithHighway.bOk));
	TestEqual(TEXT("across reason"), Across.Reason, FString(T43_WithHighway.Reason));
	// The SAME click on a board with no highway places normally, which is what
	// proves the refusal is the highway's doing and not the coordinates'.
	FCityState Bare = TypeSeed();
	const FClickResult Control = ResolveClick(Board, Bare, T43_Without.X, T43_Without.Y,
		T43_Without.bPinsActive, Board.Rules.V0Width);
	TestEqual(TEXT("the same click without a highway places"), BoolStr(Control.bOk), BoolStr(T43_Without.bOk));
	TestEqual(TEXT("control x0"), Control.Lot.X0, T43_Without.Lot.X0, 1e-9);
	TestEqual(TEXT("control road"), LotRoadId(Control.Lot), FString(T43_Without.Lot.RoadId));
	return true;
}

// --- 44: roads cost money -----------------------------------------------------
STACKTOWN_TYPES_TEST(FStacktownRoadAfford, "Stacktown.Roads.Afford")
{
	// ON A STATE LEFT AT money_start deliberately - the funding note in TypeSeed
	// explains why every other case here is not.
	const FPlacementBoard Board = OracleBoard();
	FEconRules Rules = OracleRules();
	FCityState S = SeedState(Rules);
	TestEqual(TEXT("money_start"), S.Money, T44_MoneyStart, 1e-9);

	const FRoadDrawResult Quote = ResolveRoadDraw(Board, S, T44_AvenueRefused.X0, T44_AvenueRefused.Y0,
		T44_AvenueRefused.X1, T44_AvenueRefused.Y1, FString(T44_AvenueClass), T44_AvenueRefused.bPinsActive);
	TestEqual(TEXT("avenue refused"), BoolStr(Quote.bOk), BoolStr(T44_AvenueRefused.bOk));
	TestEqual(TEXT("reason carries the price and the balance"), Quote.Reason, FString(T44_AvenueRefused.Reason));

	// A REFUSAL SPENDS NOTHING. This is the property that lets the ghost preview
	// call the same function every frame.
	const FRoadDrawResult Tried = DrawRoad(Board, S, T44_AvenueRefused.X0, T44_AvenueRefused.Y0,
		T44_AvenueRefused.X1, T44_AvenueRefused.Y1, FString(T44_AvenueClass), T44_AvenueRefused.bPinsActive);
	TestFalse(TEXT("draw refused too"), Tried.bOk);
	TestEqual(TEXT("money untouched"), S.Money, T44_MoneyAfterRefusal, 1e-9);
	TestEqual(TEXT("and no road added"), S.Roads.Num(), 0);

	// The SAME road as a dirt track is $70 and draws, leaving exactly $30.
	const FRoadDrawResult Dirt = DrawRoad(Board, S, T44_AvenueRefused.X0, T44_AvenueRefused.Y0,
		T44_AvenueRefused.X1, T44_AvenueRefused.Y1, FString(T44_DirtStored.WidthClass),
		T44_AvenueRefused.bPinsActive);
	TestTrue(TEXT("the same road as dirt draws"), Dirt.bOk);
	TestEqual(TEXT("id"), Dirt.Id, FString(T44_DirtStored.Id));
	TestEqual(TEXT("stored class"), S.Roads[Dirt.Id].WidthClass, FString(T44_DirtStored.WidthClass));
	TestEqual(TEXT("money after"), S.Money, T44_MoneyAfter, 1e-9);
	return true;
}

// --- 45: a narrower road pulls its own frontage line in ------------------------
STACKTOWN_TYPES_TEST(FStacktownRoadNarrowerFrontage, "Stacktown.Roads.NarrowerFrontage")
{
	const FPlacementBoard Board = OracleBoard();
	FCityState S = TypeSeed();
	const FRoadDrawResult D = DrawRoad(Board, S, T44_AvenueRefused.X0, T44_AvenueRefused.Y0,
		T44_AvenueRefused.X1, T44_AvenueRefused.Y1, FString(T44_DirtStored.WidthClass), true);
	TestTrue(TEXT("dirt drawn"), D.bOk);

	// Its footprint is y 2120..3880, not the avenue's 1870..4130.
	const FLotRect RoadR = RoadRect(Board.Rules, Board.Econ, RoadDictFromSegment(D.Id, S.Roads[D.Id]));
	TestEqual(TEXT("road rect ymin"), RoadR.YMin, T45_DirtRoadRect.YMin, 1e-9);
	TestEqual(TEXT("road rect ymax"), RoadR.YMax, T45_DirtRoadRect.YMax, 1e-9);

	// And a lot on its south side sits at y 620..2120, not 370..1870. Same
	// click, same road geometry, different type - the point of a type being a
	// mechanic rather than a paint job.
	const FPlaceResult P = Place(Board, S, T45_ClickX, T45_ClickY, true, Board.Rules.V0Width);
	TestTrue(TEXT("placed"), P.bOk);
	if (!P.bOk) { return false; }
	const FLotPlacement& Lot = S.Parcels[P.Pid].Placement.GetValue();
	TestEqual(TEXT("side"), Lot.Side, FString(T45_Lot.Side));
	TestEqual(TEXT("road"), LotRoadId(Lot), FString(T45_Lot.RoadId));
	const TArray<FRoad> RoadsLocal = Board.AllRoads(S);
	const FRoad* Own = FindRoad(RoadsLocal, LotRoadId(Lot));
	if (!TestNotNull(TEXT("own road"), Own)) { return false; }
	const FLotRect Rect = LotRect(Board.Rules, Board.Econ, *Own, Lot);
	TestEqual(TEXT("lot rect ymin"), Rect.YMin, T45_LotRect.YMin, 1e-9);
	TestEqual(TEXT("lot rect ymax"), Rect.YMax, T45_LotRect.YMax, 1e-9);
	return true;
}

// --- 46: the rent multiplier ---------------------------------------------------
STACKTOWN_TYPES_TEST(FStacktownRoadRentMultiplier, "Stacktown.Roads.RentMultiplier")
{
	// TWO MECHANISMS, because MONDAY_DECISIONS section 2 describes two: a lot's
	// OWN road multiplies by its type, and a road that refuses frontage lifts
	// every lot within RoadHighwayReach of its PAVEMENT. The second has to be
	// proximity - nothing ever fronts a highway - and they MULTIPLY.
	//
	// NOT APPLIED BY Tick(). The economy loop is the coordinator's; this is the
	// pure function rent gets multiplied by, deliberately left un-wired.
	//
	// Synthetic states: the function is pure over (state, lot), and building the
	// adjacency by hand is the only way to hit the 2,000 uu edge from both sides.
	const FPlacementBoard Board = OracleBoard();
	TestEqual(TEXT("highway reach"), Board.Econ.RoadHighwayReach, HighwayReach, 1e-9);

	FLotPlacement Lot;
	Lot.X0 = T46_Lot.X0;
	Lot.X1 = T46_Lot.X1;
	Lot.Side = FString(T46_Lot.Side);
	Lot.RoadId = FString(T46_Lot.RoadId);

	for (int32 i = 0; i < T46_CasesNum; ++i)
	{
		const FRentCase& C = T46_Cases[i];
		FCityState S;
		FRoadSegment D;
		D.StartX = 6200.0; D.StartY = 3000.0; D.EndX = 7600.0; D.EndY = 3000.0;
		D.WidthClass = FString(C.Own);
		S.Roads.Add(FString(TEXT("D")), D);
		if (C.Highway != nullptr)
		{
			const bool bNear = FString(C.Highway) == FString(TEXT("near"));
			S.Roads.Add(FString(TEXT("HW")), SegOf(bNear ? T46_NearHighway : T46_FarHighway));
		}
		TestEqual(*FString::Printf(TEXT("%s%s"), C.Own, C.Highway ? C.Highway : TEXT(" alone")),
			RoadRentMultiplier(Board, S, Lot), C.Mult, 1e-9);
	}

	// The near miss the reach is bounded by: 2120 uu against a 2000 uu reach.
	// A test written at 10,000 uu would pass with the bound wrong by a lot.
	const FLotRect LotR = { T46_DirtLotRect.XMin, T46_DirtLotRect.XMax,
		T46_DirtLotRect.YMin, T46_DirtLotRect.YMax };
	TestEqual(TEXT("far distance, pavement to pad"),
		RectDistance(LotR, RoadRect(Board.Rules, Board.Econ,
			RoadDictFromSegment(FString(TEXT("HW")), SegOf(T46_FarHighway)))),
		T46_FarDistance, 1e-9);
	return true;
}

// --- 47: an unrecognised type is refused at the boundary -----------------------
STACKTOWN_TYPES_TEST(FStacktownRoadUnknownType, "Stacktown.Roads.UnknownType")
{
	// A REASON, not a traceback: a bad string arriving from a UI is a refusal a
	// player can read. Nothing is spent and no road is created.
	const FPlacementBoard Board = OracleBoard();
	FCityState S = TypeSeed();
	const double Before = S.Money;
	const FRoadDrawResult D = DrawRoad(Board, S, T47_Unknown.X0, T47_Unknown.Y0,
		T47_Unknown.X1, T47_Unknown.Y1, FString(T47_Class), T47_Unknown.bPinsActive);
	TestEqual(TEXT("refused"), BoolStr(D.bOk), BoolStr(T47_Unknown.bOk));
	TestEqual(TEXT("reason lists what is expected"), D.Reason, FString(T47_Unknown.Reason));
	TestEqual(TEXT("nothing spent"), S.Money, Before, 1e-9);
	TestEqual(TEXT("no road added"), S.Roads.Num(), 0);
	return true;
}

// --- 48: InCrossing measures each road's OWN pavement --------------------------
STACKTOWN_TYPES_TEST(FStacktownRoadCrossingOwnHalf, "Stacktown.Roads.CrossingUsesOwnHalf")
{
	// A point 1,300 uu from a centreline is standing ON a highway (half 1,430)
	// and would not be on an avenue (half 1,130) - so whether that point is
	// "pavement shared by more than one road" depends on the type, and nothing
	// else in these tests reaches this line.
	//
	// A DIRECT test, on a road list built by hand, and the honest reason why:
	// ResolveRoadDraw refuses any candidate whose corridor overlaps an existing
	// one, so no state reachable through DrawRoad can have two corridors sharing
	// ground at all - the only crossing that exists is the arterial and the
	// cross street, both avenues, where the constant and the per-type half
	// agree. The per-type half still belongs here: the built-ins are never
	// validated against that rule, and a wider road drawn against a rule that
	// ever softens would otherwise offer frontage on pavement a player stands in.
	const FPlacementBoard Board = OracleBoard();
	const FRoad* Arterial = FindRoad(Board.Roads, FString(TEXT("arterial")));
	const FRoad* Cross = FindRoad(Board.Roads, FString(TEXT("cross")));
	if (!TestNotNull(TEXT("arterial"), Arterial) || !TestNotNull(TEXT("cross"), Cross)) { return false; }

	const FRoad Hw = RoadDictFromSegment(FString(TEXT("HW")), SegOf(T48_Segment));
	FRoadSegment AvSeg = SegOf(T48_Segment);
	AvSeg.WidthClass = FString(TEXT("avenue"));
	const FRoad Av = RoadDictFromSegment(FString(TEXT("HW")), AvSeg);

	TArray<FRoad> WithHw; WithHw.Add(*Arterial); WithHw.Add(Hw);
	TArray<FRoad> WithAv; WithAv.Add(*Arterial); WithAv.Add(Av);
	TestEqual(TEXT("on a highway's pavement"),
		BoolStr(InCrossing(Board.Rules, Board.Econ, WithHw, T48_X, T48_Y)), BoolStr(T48_Highway));
	TestEqual(TEXT("not on an avenue's"),
		BoolStr(InCrossing(Board.Rules, Board.Econ, WithAv, T48_X, T48_Y)), BoolStr(T48_Avenue));

	TArray<FRoad> BuiltIns; BuiltIns.Add(*Arterial); BuiltIns.Add(*Cross);
	TestEqual(TEXT("the built-in crossing is still a crossing"),
		BoolStr(InCrossing(Board.Rules, Board.Econ, BuiltIns, 0.0, 0.0)), BoolStr(T48_BuiltinsAtOrigin));
	return true;
}

#endif // WITH_DEV_AUTOMATION_TESTS
