// ROADS AT ANY DIRECTION - placement.py self-tests 50-55, ported. Item 11's
// first half: the resolver, the lot frame and every overlap scan generalize
// off the road's own unit direction.
//
//   UnrealEditor-Cmd <uproject> -ExecCmds="Automation RunTests Stacktown.Roads; Quit" \
//     -unattended -nopause -nullrhi -log
//
// THE ONE THING WORTH CHECKING is the reduction: every axis-aligned case in
// Stacktown.Placement and Stacktown.Roads answers exactly as it did before,
// because a road at 0 or 90 degrees puts the general form back onto the old
// numbers. That is asserted here (the projection identity, quads against
// rects, the built-ins' side names) rather than argued, and it is what makes
// the change safe for every lot already in the owner's save.
//
// Expectations come from RoadsOracleFixture.inl, generated by running
// placement.py over these exact scenarios.

#include "Misc/AutomationTest.h"
#include "StacktownPlacementTestCommon.h"
#include "StacktownEconomyTestCommon.h"
#include "StacktownLotTransform.h"
#include "RoadsOracleFixture.inl"

#if WITH_DEV_AUTOMATION_TESTS

using namespace Stacktown;
using namespace StacktownTest;
using namespace StacktownRoadsOracle;

#define STACKTOWN_DIR_TEST(TestClass, PrettyName) \
	IMPLEMENT_SIMPLE_AUTOMATION_TEST(TestClass, PrettyName, \
		EAutomationTestFlags::EditorContext | EAutomationTestFlags::ProductFilter) \
	bool TestClass::RunTest(const FString& Parameters)

namespace
{
	FCityState DirSeed()
	{
		FEconRules R = OracleRules();
		FCityState S = SeedState(R);
		S.Money = GeometryMoney;
		return S;
	}

	FLotPlacement LotOf(const FLotDef2& D)
	{
		FLotPlacement L;
		L.X0 = D.X0; L.X1 = D.X1; L.Side = FString(D.Side);
		if (D.RoadId != nullptr) { L.RoadId = FString(D.RoadId); }
		return L;
	}
}

// --- 32b + 33b: the diagonal gate is open, and length is the centreline's ----
STACKTOWN_DIR_TEST(FStacktownRoadDiagonalAccepted, "Stacktown.Roads.DiagonalAccepted")
{
	const FPlacementBoard Board = OracleBoard();
	FCityState S = DirSeed();

	// The "too diagonal: roads must run close to north-south or east-west in
	// this version" refusal is gone; the version limit it named was
	// ResolveClick recovering a world position as start[axis] + along, which
	// now works in projection space and is correct at any angle.
	const FRoadDrawResult D = ResolveRoadDraw(Board, S, T32b_Diagonal.X0, T32b_Diagonal.Y0,
		T32b_Diagonal.X1, T32b_Diagonal.Y1, FString(TEXT("avenue")), T32b_Diagonal.bPinsActive);
	TestEqual(TEXT("a 45 degree road draws"), BoolStr(D.bOk), BoolStr(T32b_Diagonal.bOk));
	// Neither endpoint pulled onto an axis: the 3x dominance test survives as a
	// SNAP THRESHOLD, and 45 degrees is nowhere near it.
	TestEqual(TEXT("start x kept"), D.Segment.StartX, T32b_Diagonal.Road.StartX, 1e-9);
	TestEqual(TEXT("start y kept"), D.Segment.StartY, T32b_Diagonal.Road.StartY, 1e-9);
	TestEqual(TEXT("end x kept"), D.Segment.EndX, T32b_Diagonal.Road.EndX, 1e-9);
	TestEqual(TEXT("end y kept"), D.Segment.EndY, T32b_Diagonal.Road.EndY, 1e-9);

	// And a diagonal is measured along its CENTRELINE: 500 by 500 is 707 uu,
	// under the 820 a lot needs, where the sum of the two deltas says 1000.
	// The two ways of measuring agree on every axis-aligned road, so nothing
	// before this could tell them apart.
	const FRoadDrawResult Sh = ResolveRoadDraw(Board, S, T33b_DiagonalTooShort.X0,
		T33b_DiagonalTooShort.Y0, T33b_DiagonalTooShort.X1, T33b_DiagonalTooShort.Y1,
		FString(TEXT("avenue")), T33b_DiagonalTooShort.bPinsActive);
	TestEqual(TEXT("707 uu is too short"), BoolStr(Sh.bOk), BoolStr(T33b_DiagonalTooShort.bOk));
	TestEqual(TEXT("and the reason says 707"), Sh.Reason, FString(T33b_DiagonalTooShort.Reason));
	return true;
}

// --- 50: the separating-axis test reduces to the rectangle test --------------
STACKTOWN_DIR_TEST(FStacktownRoadQuadsReduce, "Stacktown.Roads.QuadsReduceToRects")
{
	// Not an argument about separating axes - the two functions are run against
	// each other on real lot geometry, including a pair that only TOUCHES,
	// which must be a miss because a lot sits exactly on its own road's
	// frontage line.
	const FPlacementBoard Board = OracleBoard();
	const FCityState S = DirSeed();
	const TArray<FRoad> Roads = Board.AllRoads(S);
	for (int32 i = 0; i < T50_PairsNum; ++i)
	{
		const FQuadPair& C = T50_Pairs[i];
		const FLotPlacement A = LotOf(C.A);
		const FLotPlacement B = LotOf(C.B);
		const FRoad* RA = FindRoad(Roads, LotRoadId(A));
		const FRoad* RB = FindRoad(Roads, LotRoadId(B));
		if (!TestNotNull(TEXT("road a"), RA) || !TestNotNull(TEXT("road b"), RB)) { continue; }
		const bool bQuads = QuadsOverlap(LotQuad(Board.Rules, Board.Econ, *RA, A),
			LotQuad(Board.Rules, Board.Econ, *RB, B));
		const bool bRects = RectsOverlap(LotRect(Board.Rules, Board.Econ, *RA, A),
			LotRect(Board.Rules, Board.Econ, *RB, B));
		TestEqual(TEXT("quads match the oracle"), BoolStr(bQuads), BoolStr(C.bQuads));
		TestEqual(TEXT("rects match the oracle"), BoolStr(bRects), BoolStr(C.bRects));
		TestEqual(TEXT("and each other"), BoolStr(bQuads), BoolStr(bRects));
	}
	return true;
}

// --- 51: the projection identity ---------------------------------------------
STACKTOWN_DIR_TEST(FStacktownRoadProjectionIdentity, "Stacktown.Roads.ProjectionIdentity")
{
	// A lot's X0/X1 are the scalar projection of its span onto the road's unit
	// direction. For both built-ins that IS the world coordinate they have
	// always been - S0 + Along == the world coordinate, exactly - which is why
	// no lot already in the owner's save changes meaning.
	const FPlacementBoard Board = OracleBoard();
	const FCityState S = DirSeed();
	const TArray<FRoad> Roads = Board.AllRoads(S);
	for (int32 i = 0; i < T51_ProjectionNum; ++i)
	{
		const FProjCase& C = T51_Projection[i];
		const FRoad* Road = FindRoad(Roads, FString(C.Road));
		if (!TestNotNull(TEXT("road"), Road)) { continue; }
		const FRoadFrame F = RoadFrame(*Road);
		TestEqual(TEXT("s0"), F.S0, C.S0, 1e-9);
		TestEqual(TEXT("length"), F.Length, C.Length, 1e-9);
		TestEqual(TEXT("ux"), F.Ux, C.Ux, 1e-9);
		TestEqual(TEXT("uy"), F.Uy, C.Uy, 1e-9);
		TestEqual(TEXT("nx"), F.Nx, C.Nx, 1e-9);
		TestEqual(TEXT("ny"), F.Ny, C.Ny, 1e-9);
		for (int32 k = 0; k < 5; ++k)
		{
			const FProjRow& Row = C.Points[k];
			const FRoadProjection Pr = ProjectToRoad(*Road, Row.X, Row.Y);
			TestEqual(TEXT("along"), Pr.Along, Row.Along, 1e-9);
			TestEqual(TEXT("s0 + along IS the world coordinate"), F.S0 + Pr.Along, Row.World, 1e-9);
			double Wx = 0.0, Wy = 0.0;
			PointAt(F, F.S0 + Pr.Along, 0.0, Wx, Wy);
			TestEqual(TEXT("and the point comes back"), Road->bAxisX ? Wx : Wy, Row.World, 1e-9);
		}
	}
	return true;
}

// --- 52: a lot on a 45 degree road, end to end, and its pose -----------------
STACKTOWN_DIR_TEST(FStacktownRoadDiagonalLot, "Stacktown.Roads.DiagonalLot")
{
	const FPlacementBoard Board = OracleBoard();
	FEconRules Rules = OracleRules();
	FCityState S = SeedState(Rules);
	S.Money = T52_MoneyBefore;

	const FRoadDrawResult D = DrawRoad(Board, S, T52_Segment.StartX, T52_Segment.StartY,
		T52_Segment.EndX, T52_Segment.EndY, FString(T52_Segment.WidthClass), true);
	TestTrue(TEXT("diagonal drawn"), D.bOk);
	TestEqual(TEXT("priced by its true length"), S.Money, T52_MoneyAfter, 1e-9);

	const FPlaceResult P = Place(Board, S, T52_ClickX, T52_ClickY, true, Board.Rules.V0Width);
	if (!TestTrue(TEXT("lot placed"), P.bOk)) { return false; }
	const FLotPlacement& Lot = S.Parcels[P.Pid].Placement.GetValue();
	TestEqual(TEXT("x0"), Lot.X0, T52_Lot.X0, 1e-9);
	TestEqual(TEXT("x1"), Lot.X1, T52_Lot.X1, 1e-9);
	TestEqual(TEXT("side"), Lot.Side, FString(T52_Lot.Side));
	TestEqual(TEXT("road"), LotRoadId(Lot), FString(T52_Lot.RoadId));

	// The pad is a ROTATED rectangle. Before this, ResolveClick recovered a
	// world position as start[axis] + along and could not have produced these
	// corners at all.
	const TArray<FRoad> Roads = Board.AllRoads(S);
	const FRoad* Own = FindRoad(Roads, LotRoadId(Lot));
	if (!TestNotNull(TEXT("own road"), Own)) { return false; }
	const FQuad Q = LotQuad(Board.Rules, Board.Econ, *Own, Lot);
	for (int32 k = 0; k < 4; ++k)
	{
		TestEqual(TEXT("pad corner x"), Q.X[k], T52_Quad.X[k], 0.01);
		TestEqual(TEXT("pad corner y"), Q.Y[k], T52_Quad.Y[k], 0.01);
	}

	// AND IT POSES. The anchor is the midpoint of the quad edge the pad's own
	// +x runs from, and the yaw is the direction from corner 0 to corner 1 -
	// both read off the ORACLE'S corners, so the world transform is tied to the
	// fixture rather than to a second hand-computed answer. Without this a
	// diagonal lot would resolve correctly and still stand in the wrong place.
	LotFrame::FPose Pose;
	TestTrue(TEXT("pose resolves"), LotFrame::Pose(Lot, Roads, Pose,
		RoadHalf(Board.Rules, Board.Econ, *Own)));
	TestEqual(TEXT("pose x"), Pose.X, (T52_Quad.X[0] + T52_Quad.X[3]) * 0.5, 0.01);
	TestEqual(TEXT("pose y"), Pose.Y, (T52_Quad.Y[0] + T52_Quad.Y[3]) * 0.5, 0.01);
	TestEqual(TEXT("pose yaw is the road's own direction"), Pose.Yaw,
		FMath::RadiansToDegrees(FMath::Atan2(T52_Quad.Y[1] - T52_Quad.Y[0],
			T52_Quad.X[1] - T52_Quad.X[0])), 0.01);

	// Both sides of the same span are placeable - they share no ground - and
	// the same span twice on the same side is not.
	FCityState Other = S;
	const FPlaceResult P2 = Place(Board, Other, T52_OtherX, T52_OtherY, true, Board.Rules.V0Width);
	TestTrue(TEXT("the other side of the same span places"), P2.bOk);
	if (P2.bOk)
	{
		TestEqual(TEXT("other side"), Other.Parcels[P2.Pid].Placement.GetValue().Side,
			FString(T52_OtherLot.Side));
	}
	FCityState Again = S;
	const FPlaceResult P3 = Place(Board, Again, T52_ClickX, T52_ClickY, true, Board.Rules.V0Width);
	TestEqual(TEXT("the same span twice refuses"), BoolStr(P3.bOk), BoolStr(T52_AgainOk));
	TestEqual(TEXT("and says why"), P3.Reason, FString(T52_AgainReason));
	return true;
}

// --- 53: side names come off the NORMAL --------------------------------------
STACKTOWN_DIR_TEST(FStacktownRoadSideNames, "Stacktown.Roads.SideNames")
{
	// The discriminating case runs down and to the right at a 2:1 slope: its
	// DIRECTION is Y-dominant, so a dominant-axis rule would call the plus side
	// 'west', and the normal points EAST - which is where those lots are. The
	// reversed segments are unreachable through the draw path now that the
	// endpoints are ordered, but RoadDictFromSegment must still answer for
	// them, so they are tested directly.
	for (int32 i = 0; i < T53_SidesNum; ++i)
	{
		const FSideRow& Row = T53_Sides[i];
		FRoadSegment Seg;
		Seg.StartX = Row.StartX; Seg.StartY = Row.StartY;
		Seg.EndX   = Row.EndX;   Seg.EndY   = Row.EndY;
		const FRoad Road = RoadDictFromSegment(FString(TEXT("X")), Seg);
		TestEqual(*FString::Printf(TEXT("%s: side plus"), Row.Label), Road.SidePlus, FString(Row.Plus));
		TestEqual(*FString::Printf(TEXT("%s: side minus"), Row.Label), Road.SideMinus, FString(Row.Minus));
		TestEqual(TEXT("dominant axis"), BoolStr(Road.bAxisX), BoolStr(Row.bAxisX));
		const FRoadFrame F = RoadFrame(Road);
		TestEqual(TEXT("normal x"), F.Nx, Row.Nx, 1e-6);
		TestEqual(TEXT("normal y"), F.Ny, Row.Ny, 1e-6);
	}
	return true;
}

// --- 54 + 55: every overlap scan compares PADS, not boxes --------------------
STACKTOWN_DIR_TEST(FStacktownRoadScansComparePads, "Stacktown.Roads.ScansComparePads")
{
	// A 45 degree lot's pad is an 820 x 1500 rectangle turned 45 degrees; its
	// bounding box is about 1640 square, and the empty corners are most of it.
	// So a box scan refuses real ground - which is a player-facing fact, not a
	// nicety. Each case below is shown against the box test that would have
	// refused it.
	const FPlacementBoard Board = OracleBoard();

	// 54: two houses along one diagonal street. Empty mode, because the pinned
	// frontage is wall to wall from |x| 1130 to 6050 and a diagonal long enough
	// for two lots cannot avoid it on this board - the same mode gate the click
	// path already has, not a special case invented here.
	{
		FCityState S = DirSeed();
		S.Money = 9000.0;
		const FRoadDrawResult D = DrawRoad(Board, S, T54_Segment.StartX, T54_Segment.StartY,
			T54_Segment.EndX, T54_Segment.EndY, FString(T54_Segment.WidthClass), false);
		TestTrue(TEXT("diagonal drawn"), D.bOk);
		for (int32 i = 0; i < 2; ++i)
		{
			const FPlaceResult P = Place(Board, S, T54_Clicks[i][0], T54_Clicks[i][1],
				false, Board.Rules.V0Width);
			if (!TestTrue(TEXT("lot placed"), P.bOk)) { continue; }
			const FLotPlacement& Lot = S.Parcels[P.Pid].Placement.GetValue();
			TestEqual(TEXT("x0"), Lot.X0, T54_Lots[i].X0, 1e-9);
			TestEqual(TEXT("x1"), Lot.X1, T54_Lots[i].X1, 1e-9);
		}
		if (S.Parcels.Contains(FString(TEXT("P2"))))
		{
			const FLotPlacement& A = S.Parcels[FString(TEXT("P1"))].Placement.GetValue();
			const FLotPlacement& B = S.Parcels[FString(TEXT("P2"))].Placement.GetValue();
			const TArray<FRoad> Roads = Board.AllRoads(S);
			const FRoad* Rd = FindRoad(Roads, LotRoadId(A));
			if (TestNotNull(TEXT("road"), Rd))
			{
				const FQuad QA = LotQuad(Board.Rules, Board.Econ, *Rd, A);
				const FQuad QB = LotQuad(Board.Rules, Board.Econ, *Rd, B);
				TestEqual(TEXT("pads miss"), BoolStr(QuadsOverlap(QA, QB)), BoolStr(T54_Quads));
				TestEqual(TEXT("boxes do not"),
					BoolStr(RectsOverlap(QuadRect(QA), QuadRect(QB))), BoolStr(T54_Rects));
			}
		}
	}

	// 55a: a drawn road against an existing lot.
	{
		FCityState S = DirSeed();
		S.Money = 40000.0;
		const FPlaceResult PA = Place(Board, S, T55_RvL_Click[0], T55_RvL_Click[1],
			false, Board.Rules.V0Width);
		TestTrue(TEXT("arterial lot placed"), PA.bOk);
		const FRoadDrawResult DA = ResolveRoadDraw(Board, S, T55_RvL_Draw[0], T55_RvL_Draw[1],
			T55_RvL_Draw[2], T55_RvL_Draw[3], FString(TEXT("avenue")), false);
		TestTrue(TEXT("the diagonal draws past it"), DA.bOk);
		if (PA.bOk && DA.bOk)
		{
			const FLotPlacement& Lot = S.Parcels[PA.Pid].Placement.GetValue();
			const TArray<FRoad> Roads = Board.AllRoads(S);
			const FRoad* Rd = FindRoad(Roads, LotRoadId(Lot));
			if (TestNotNull(TEXT("road"), Rd))
			{
				const FQuad QR = RoadQuad(Board.Rules, Board.Econ,
					RoadDictFromSegment(DA.Id, DA.Segment));
				const FQuad QL = LotQuad(Board.Rules, Board.Econ, *Rd, Lot);
				TestEqual(TEXT("corridor misses the pad"),
					BoolStr(QuadsOverlap(QR, QL)), BoolStr(T55_RvL_Quads));
				TestEqual(TEXT("boxes overlap"),
					BoolStr(RectsOverlap(QuadRect(QR), QuadRect(QL))), BoolStr(T55_RvL_Rects));
			}
		}
	}

	// 55b: a drawn road against another road.
	{
		FCityState S = DirSeed();
		S.Money = 40000.0;
		const FRoadDrawResult D1 = DrawRoad(Board, S, T55_RvR_First[0], T55_RvR_First[1],
			T55_RvR_First[2], T55_RvR_First[3], FString(TEXT("avenue")), false);
		TestTrue(TEXT("diagonal drawn"), D1.bOk);
		const FRoadDrawResult D2 = ResolveRoadDraw(Board, S, T55_RvR_Second[0], T55_RvR_Second[1],
			T55_RvR_Second[2], T55_RvR_Second[3], FString(TEXT("avenue")), false);
		TestTrue(TEXT("a road in its box corner draws"), D2.bOk);
		if (D1.bOk && D2.bOk)
		{
			const FQuad Q1 = RoadQuad(Board.Rules, Board.Econ,
				RoadDictFromSegment(D1.Id, S.Roads[D1.Id]));
			const FQuad Q2 = RoadQuad(Board.Rules, Board.Econ,
				RoadDictFromSegment(D2.Id, D2.Segment));
			TestEqual(TEXT("corridors miss"), BoolStr(QuadsOverlap(Q1, Q2)), BoolStr(T55_RvR_Quads));
			TestEqual(TEXT("boxes overlap"),
				BoolStr(RectsOverlap(QuadRect(Q1), QuadRect(Q2))), BoolStr(T55_RvR_Rects));
		}
	}

	// 55c: a lot against a HIGHWAY's corridor - the no-frontage scan, which is
	// a refusal rather than a nicety, so a box test there would block a legal
	// click on the ground beside a motorway.
	{
		FCityState S = DirSeed();
		S.Money = 40000.0;
		const FRoadDrawResult DC = DrawRoad(Board, S, T55_LvH_Road[0], T55_LvH_Road[1],
			T55_LvH_Road[2], T55_LvH_Road[3], FString(TEXT("avenue")), false);
		TestTrue(TEXT("diagonal drawn"), DC.bOk);
		const FRoadDrawResult DH = DrawRoad(Board, S, T55_LvH_Highway[0], T55_LvH_Highway[1],
			T55_LvH_Highway[2], T55_LvH_Highway[3], FString(TEXT("highway")), false);
		TestTrue(TEXT("highway drawn"), DH.bOk);
		const FClickResult CR = ResolveClick(Board, S, T55_LvH_Click[0], T55_LvH_Click[1],
			false, Board.Rules.V0Width);
		TestEqual(TEXT("the click still places"), BoolStr(CR.bOk), BoolStr(T55_LvH_StillPlaces));
		if (CR.bOk && DH.bOk)
		{
			TestEqual(TEXT("x0"), CR.Lot.X0, T55_LvH_Lot.X0, 1e-9);
			const TArray<FRoad> Roads = Board.AllRoads(S);
			const FRoad* Rd = FindRoad(Roads, LotRoadId(CR.Lot));
			if (TestNotNull(TEXT("road"), Rd))
			{
				const FQuad QL = LotQuad(Board.Rules, Board.Econ, *Rd, CR.Lot);
				const FQuad QH = RoadQuad(Board.Rules, Board.Econ,
					RoadDictFromSegment(DH.Id, S.Roads[DH.Id]));
				TestEqual(TEXT("pad misses the motorway"),
					BoolStr(QuadsOverlap(QL, QH)), BoolStr(T55_LvH_Quads));
				TestEqual(TEXT("boxes overlap"),
					BoolStr(RectsOverlap(QuadRect(QL), QuadRect(QH))), BoolStr(T55_LvH_Rects));
			}
		}
	}
	return true;
}

#endif // WITH_DEV_AUTOMATION_TESTS
