// placement.py self-tests 1-27, ported (Phase 1 step 2).
//
//   UnrealEditor-Cmd <uproject> -ExecCmds="Automation RunTests Stacktown.Placement; Quit" \
//     -unattended -nopause -nullrhi -log
//
// Tests 28-39 (drawn roads) are step 4's and are deliberately absent.
//
// Every expectation comes from PlacementOracleFixture.inl, generated by running
// placement.py. That is worth more here than it was for the economy: this
// module's own test COMMENTS have drifted from its assertions - test 3 says P1
// spans [-7380, -6560] where test 1 asserts [-7410, -6590], and test 20's
// arithmetic comment lands on 2050 where it asserts 2090. Both comments are
// stale and both assertions are right. A porter reading comments would have
// carried the drift across; generating the numbers cannot.
//
// Refusal REASONS are asserted as exact strings. The Python asserts substrings
// ('overlap' in reason), which would pass on a message that had lost the span,
// the road name, or the lot it collided with - the parts a player needs.

#include "Misc/AutomationTest.h"
#include "StacktownPlacementTestCommon.h"
#include "StacktownEconomyTestCommon.h"

#if WITH_DEV_AUTOMATION_TESTS

using namespace Stacktown;
using namespace StacktownTest;
using namespace StacktownPlacementOracle;

#define STACKTOWN_PLACE_TEST(TestClass, PrettyName) \
	IMPLEMENT_SIMPLE_AUTOMATION_TEST(TestClass, PrettyName, \
		EAutomationTestFlags::EditorContext | EAutomationTestFlags::ProductFilter) \
	bool TestClass::RunTest(const FString& Parameters)

namespace
{
	/** A fresh city, seeded the way citytick.seed_state() does. */
	FCityState Seed()
	{
		FEconRules R = OracleRules();
		return SeedState(R);
	}
}

// --- 1: a clean click near the plate's west edge --------------------------------
STACKTOWN_PLACE_TEST(FStacktownPlaceFirst, "Stacktown.Placement.FirstPlace")
{
	const FPlacementBoard Board = OracleBoard();
	FCityState S = Seed();

	const FPlaceResult R = Place(Board, S, T1_X, T1_Y, true, V0Width);
	TestEqual(TEXT("ok"), BoolStr(R.bOk), BoolStr(T1_Ok));
	TestEqual(TEXT("pid"), R.Pid, FString(T1_Pid));
	TestEqual(TEXT("no reason on success"), R.Reason, FString(T1_Reason));

	const FParcelState& P = S.Parcels[FString(T1_Pid)];
	TestEqual(TEXT("rid"), P.Rid, FString(T1_Rid));
	TestEqual(TEXT("tier seeds at 0"), P.Tier, T1_Tier);
	TestEqual(TEXT("width"), P.Width, T1_Width, 1e-9);
	TestFalse(TEXT("a placed lot is not owned yet"), P.bOwned);
	TestEqual(TEXT("performance neutral"), P.Performance, PerformanceNeutral, 1e-9);
	TestTrue(TEXT("placement present"), P.Placement.IsSet());
	FString Why;
	const bool bLot = P.Placement.IsSet() && LotMatches(P.Placement.GetValue(), T1_Lot, Why);
	TestTrue(FString::Printf(TEXT("placement matches the oracle (%s)"), *Why), bLot);
	return true;
}

// --- 2: off-board, and nothing registered ---------------------------------------
STACKTOWN_PLACE_TEST(FStacktownPlaceOffBoard, "Stacktown.Placement.OffBoard")
{
	const FPlacementBoard Board = OracleBoard();
	FCityState S = Seed();
	Place(Board, S, T1_X, T1_Y, true, V0Width);
	const int32 Before = S.Parcels.Num();

	const FPlaceResult R = Place(Board, S, T2_X, T2_Y, true, V0Width);
	TestEqual(TEXT("ok"), BoolStr(R.bOk), BoolStr(T2_Ok));
	TestEqual(TEXT("pid empty on refusal"), R.Pid, FString());
	TestEqual(TEXT("reason"), R.Reason, FString(T2_Reason));
	// A refused placement must not register. The Python asserts 'P2' is absent;
	// asserting the whole count catches a refusal that added something else.
	TestEqual(TEXT("a refused placement adds nothing"), S.Parcels.Num(), Before);
	return true;
}

// --- 3 + 4: overlap on one side, independence of the other ----------------------
STACKTOWN_PLACE_TEST(FStacktownPlaceSides, "Stacktown.Placement.Sides")
{
	const FPlacementBoard Board = OracleBoard();
	FCityState S = Seed();
	Place(Board, S, T1_X, T1_Y, true, V0Width);

	{
		FCityState Copy = S;
		const FPlaceResult R = Place(Board, Copy, T3_X, T3_Y, true, V0Width);
		TestEqual(TEXT("same-side overlap ok"), BoolStr(R.bOk), BoolStr(T3_Ok));
		TestEqual(TEXT("same-side overlap reason"), R.Reason, FString(T3_Reason));
	}
	{
		// The SAME x on the opposite side is not an overlap: frontage sides are
		// independent spans.
		FCityState Copy = S;
		const FPlaceResult R = Place(Board, Copy, T4_X, T4_Y, true, V0Width);
		TestEqual(TEXT("opposite side ok"), BoolStr(R.bOk), BoolStr(T4_Ok));
		TestEqual(TEXT("opposite side pid"), R.Pid, FString(T4_Pid));
		FString Why;
		const bool bLot = LotMatches(Copy.Parcels[FString(T4_Pid)].Placement.GetValue(), T4_Lot, Why);
		TestTrue(FString::Printf(TEXT("south lot (%s)"), *Why), bLot);
	}
	return true;
}

// --- 5: the next pid in sequence, never a reused one -----------------------------
STACKTOWN_PLACE_TEST(FStacktownPlaceNextPid, "Stacktown.Placement.NextPid")
{
	const FPlacementBoard Board = OracleBoard();
	FCityState S = Seed();
	Place(Board, S, T1_X, T1_Y, true, V0Width);
	Place(Board, S, T4_X, T4_Y, true, V0Width);

	const FPlaceResult R = Place(Board, S, T5_X, T5_Y, true, V0Width);
	TestEqual(TEXT("ok"), BoolStr(R.bOk), BoolStr(T5_Ok));
	TestEqual(TEXT("pid"), R.Pid, FString(T5_Pid));
	FString Why;
	const bool bLot = LotMatches(S.Parcels[FString(T5_Pid)].Placement.GetValue(), T5_Lot, Why);
	TestTrue(FString::Printf(TEXT("east-margin lot (%s)"), *Why), bLot);
	return true;
}

// --- 6: a placed parcel is a pinned parcel plus exactly one key -------------------
STACKTOWN_PLACE_TEST(FStacktownPlaceShape, "Stacktown.Placement.Shape")
{
	const FPlacementBoard Board = OracleBoard();
	FCityState S = Seed();
	Place(Board, S, T1_X, T1_Y, true, V0Width);
	const FParcelState& Placed = S.Parcels[FString(T1_Pid)];

	// In C++ the "shape" claim is about which FIELDS carry data, since both
	// paths share one struct. The claim that survives the port: a placed parcel
	// differs from a pinned one in the placement field and nothing else.
	FParcelState Pinned;
	Pinned.Rid = Board.Rules.V0Recipe;
	Pinned.Tier = 0;
	Pinned.Width = V0Width;

	TestEqual(TEXT("only one key distinguishes them"), T6_ExtraCount, 1);
	TestEqual(TEXT("and it is the placement"), FString(T6_ExtraKey), FString(TEXT("placement")));
	TestFalse(TEXT("a pinned parcel carries no placement"), Pinned.Placement.IsSet());
	TestTrue(TEXT("a placed parcel does"), Placed.Placement.IsSet());
	TestEqual(TEXT("rid otherwise identical"), Placed.Rid, Pinned.Rid);
	TestEqual(TEXT("tier otherwise identical"), Placed.Tier, Pinned.Tier);
	TestEqual(TEXT("failed otherwise identical"), BoolStr(Placed.bFailed), BoolStr(Pinned.bFailed));
	TestEqual(TEXT("performance otherwise identical"), Placed.Performance, Pinned.Performance, 1e-9);
	return true;
}

// --- 7: containment, not equality ------------------------------------------------
STACKTOWN_PLACE_TEST(FStacktownPlacePlateContainsBlocks, "Stacktown.Placement.PlateContainsBlocks")
{
	// The plate's real bounds were MEASURED off the board mesh in the editor,
	// and citylayout was proven the wrong authority for them twice by the
	// owner's live clicks. Nothing here can re-derive them; what is still true
	// and still worth checking is that the plate contains the blocks.
	TestTrue(TEXT("plate reaches the west-most block"), PlateXMin <= BlockEnvXMin);
	TestTrue(TEXT("plate reaches the east-most block"), BlockEnvXMax <= PlateXMax);
	return true;
}

// --- 8: the pool cap beats geometry ----------------------------------------------
STACKTOWN_PLACE_TEST(FStacktownPlacePoolExhausted, "Stacktown.Placement.PoolExhausted")
{
	const FPlacementBoard Board = OracleBoard();
	FCityState S = Seed();
	// Built directly rather than by real clicks: clicks overlap-refuse around
	// 28, so the count check would never outlive the geometry check.
	const FLotDef Degenerate = { 0.0, 0.0, TEXT("north"), nullptr };
	for (int32 i = 0; i < PoolSize; ++i)
	{
		S.Parcels.Add(FString::Printf(TEXT("ZZ%d"), i), PlacedParcel(Board, Degenerate));
	}
	const FPlaceResult R = Place(Board, S, T8_X, T8_Y, true, V0Width);
	TestEqual(TEXT("ok"), BoolStr(R.bOk), BoolStr(T8_Ok));
	TestEqual(TEXT("reason"), R.Reason, FString(T8_Reason));
	return true;
}

// --- 9, 10, 12: plan_reactivation -------------------------------------------------
namespace
{
	void CheckPlan(FAutomationTestBase& T, const TCHAR* What,
		const TCHAR* const* Pids, int32 PidsNum,
		const TCHAR* const* Labels, int32 LabelsNum,
		const TCHAR* const* WantPids, const TCHAR* const* WantLabels, int32 PairsNum,
		const TCHAR* const* WantUnmatched, int32 UnmatchedNum)
	{
		TArray<FString> P, L;
		for (int32 i = 0; i < PidsNum; ++i)   { P.Add(FString(Pids[i])); }
		for (int32 i = 0; i < LabelsNum; ++i) { L.Add(FString(Labels[i])); }

		TArray<TPair<FString, FString>> Pairs;
		TArray<FString> Unmatched;
		PlanReactivation(P, L, Pairs, Unmatched);

		T.TestEqual(FString::Printf(TEXT("%s: pair count"), What), Pairs.Num(), PairsNum);
		for (int32 i = 0; i < PairsNum && i < Pairs.Num(); ++i)
		{
			T.TestEqual(FString::Printf(TEXT("%s: pair %d pid"), What, i),
				Pairs[i].Key, FString(WantPids[i]));
			T.TestEqual(FString::Printf(TEXT("%s: pair %d label"), What, i),
				Pairs[i].Value, FString(WantLabels[i]));
		}
		T.TestEqual(FString::Printf(TEXT("%s: unmatched count"), What),
			Unmatched.Num(), UnmatchedNum);
		for (int32 i = 0; i < UnmatchedNum && i < Unmatched.Num(); ++i)
		{
			T.TestEqual(FString::Printf(TEXT("%s: unmatched %d"), What, i),
				Unmatched[i], FString(WantUnmatched[i]));
		}
	}
}

STACKTOWN_PLACE_TEST(FStacktownPlanReactivation, "Stacktown.Placement.PlanReactivation")
{
	CheckPlan(*this, TEXT("enough slots"), T9_Pids, T9_PidsNum, T9_Labels, T9_LabelsNum,
		T9_PairPids, T9_PairLabels, T9_PairsNum, T9_Unmatched, T9_UnmatchedNum);
	// Too few slots: the leftovers are REPORTED, never silently dropped - a
	// state/pool desync has to refuse loudly.
	CheckPlan(*this, TEXT("too few slots"), T10_Pids, T10_PidsNum, T10_Labels, T10_LabelsNum,
		T10_PairPids, T10_PairLabels, T10_PairsNum, T10_Unmatched, T10_UnmatchedNum);
	// Genuinely generic: a pin-key namespace plans identically. It never sees a
	// placement at all, so it is oblivious to road_id by construction.
	CheckPlan(*this, TEXT("pin-key namespace"), T12_Pids, T12_PidsNum, T12_Labels, T12_LabelsNum,
		T12_PairPids, T12_PairLabels, T12_PairsNum, T12_Unmatched, T12_UnmatchedNum);
	return true;
}

// --- 11 + 11b: the pinned-span check and its mode gate ----------------------------
STACKTOWN_PLACE_TEST(FStacktownPlacePinnedSpans, "Stacktown.Placement.PinnedSpans")
{
	const FPlacementBoard Board = OracleBoard();
	const FCityState S = Seed();

	const FClickResult Refused = ResolveClick(Board, S, T11.X, T11.Y, T11.bPinsActive, V0Width);
	TestEqual(TEXT("pins active: ok"), BoolStr(Refused.bOk), BoolStr(T11.bOk));
	TestEqual(TEXT("pins active: reason"), Refused.Reason, FString(T11.Reason));

	// The SAME click in empty mode accepts. The pinned-span check applied
	// regardless of mode once, so a dormant pin's ground kept refusing real
	// clicks on a board with nothing standing on it.
	const FClickResult Accepted = ResolveClick(Board, S, T11b.X, T11b.Y, T11b.bPinsActive, V0Width);
	TestEqual(TEXT("empty mode: ok"), BoolStr(Accepted.bOk), BoolStr(T11b.bOk));
	TestEqual(TEXT("empty mode: no reason"), Accepted.Reason, FString(T11b.Reason));
	FString Why;
	const bool bLot = LotMatches(Accepted.Lot, T11b.Lot, Why);
	TestTrue(FString::Printf(TEXT("empty-mode lot (%s)"), *Why), bLot);
	return true;
}

// --- 13 + 14: each road alone reduces to its own axis's math -----------------------
namespace
{
	void CheckResolve(FAutomationTestBase& T, const TCHAR* What,
		const TArray<FRoad>& Roads, const FPlacementRules& Rules, const FResolveCase& C)
	{
		FRoadLocal Local;
		const FRoad* Got = ResolveRoad(Rules, Roads, C.X, C.Y, Local);
		if (C.Road == nullptr)
		{
			T.TestNull(FString::Printf(TEXT("%s (%.0f, %.0f): no road"), What, C.X, C.Y), Got);
			return;
		}
		if (Got == nullptr)
		{
			T.AddError(FString::Printf(TEXT("%s (%.0f, %.0f): expected road '%s', got none"),
				What, C.X, C.Y, C.Road));
			return;
		}
		T.TestEqual(FString::Printf(TEXT("%s (%.0f, %.0f): road"), What, C.X, C.Y),
			Got->Id, FString(C.Road));
		T.TestEqual(FString::Printf(TEXT("%s (%.0f, %.0f): along"), What, C.X, C.Y),
			Local.Along, C.Along, 1e-9);
		T.TestEqual(FString::Printf(TEXT("%s (%.0f, %.0f): across"), What, C.X, C.Y),
			Local.Across, C.Across, 1e-9);
		T.TestEqual(FString::Printf(TEXT("%s (%.0f, %.0f): side"), What, C.X, C.Y),
			Local.Side, FString(C.Side));
	}
}

STACKTOWN_PLACE_TEST(FStacktownResolveRoadAlone, "Stacktown.Placement.ResolveRoadAlone")
{
	const FPlacementBoard Board = OracleBoard();
	const TArray<FRoad> Arterial = OnlyRoad(Board, TEXT("arterial"));
	const TArray<FRoad> Cross    = OnlyRoad(Board, TEXT("cross"));

	for (int32 i = 0; i < T13ArterialAloneNum; ++i)
	{
		CheckResolve(*this, TEXT("arterial alone"), Arterial, Board.Rules, T13ArterialAlone[i]);
	}
	// The cross street's own axis: across reduces to -x, and positive x is
	// 'east' the same way positive y is 'north' for the arterial. Both
	// conventions fall out of the projection; neither is asserted separately.
	for (int32 i = 0; i < T14CrossAloneNum; ++i)
	{
		CheckResolve(*this, TEXT("cross alone"), Cross, Board.Rules, T14CrossAlone[i]);
	}
	return true;
}

// --- 15, 17, 18, 19: nearest road, the band's edges, point-to-segment, reach --------
STACKTOWN_PLACE_TEST(FStacktownResolveRoadSelection, "Stacktown.Placement.ResolveRoadSelection")
{
	const FPlacementBoard Board = OracleBoard();
	const TArray<FRoad>& Both = Board.Roads;

	// The same point test 13 resolves to the arterial ALONE goes to the cross
	// street once both are offered - which is the whole force of "alone".
	CheckResolve(*this, TEXT("nearest wins"), Both, Board.Rules, T15);
	CheckResolve(*this, TEXT("past the crossing band"), Both, Board.Rules, T17);
	// Point-to-SEGMENT: far past the arterial's east end but exactly on its
	// infinite centreline. An infinite-line distance would read 0 and accept.
	CheckResolve(*this, TEXT("point to segment"),
		OnlyRoad(Board, TEXT("arterial")), Board.Rules, T18);
	for (int32 i = 0; i < T19TooFarNum; ++i)
	{
		CheckResolve(*this, TEXT("too far"), Both, Board.Rules, T19TooFar[i]);
	}
	return true;
}

// --- 16: the crossing band refuses -------------------------------------------------
STACKTOWN_PLACE_TEST(FStacktownResolveRoadCrossing, "Stacktown.Placement.ResolveRoadCrossing")
{
	const FPlacementBoard Board = OracleBoard();
	for (int32 i = 0; i < T16CrossingNum; ++i)
	{
		CheckResolve(*this, TEXT("crossing"), Board.Roads, Board.Rules, T16Crossing[i]);
	}
	return true;
}

// --- 20 + 21: the cross street's two sides, through place() -------------------------
STACKTOWN_PLACE_TEST(FStacktownPlaceCrossStreet, "Stacktown.Placement.CrossStreet")
{
	const FPlacementBoard Board = OracleBoard();
	FCityState S = Seed();

	const FPlaceResult West = Place(Board, S, T20_X, T20_Y, true, V0Width);
	TestEqual(TEXT("west ok"), BoolStr(West.bOk), BoolStr(T20_Ok));
	TestEqual(TEXT("west pid"), West.Pid, FString(T20_Pid));
	FString Why;
	TestTrue(FString::Printf(TEXT("west lot (%s)"), *Why),
		LotMatches(S.Parcels[FString(T20_Pid)].Placement.GetValue(), T20_Lot, Why));

	const FPlaceResult East = Place(Board, S, T21_X, T21_Y, true, V0Width);
	TestEqual(TEXT("east ok"), BoolStr(East.bOk), BoolStr(T21_Ok));
	TestEqual(TEXT("east pid"), East.Pid, FString(T21_Pid));
	TestTrue(FString::Printf(TEXT("east lot (%s)"), *Why),
		LotMatches(S.Parcels[FString(T21_Pid)].Placement.GetValue(), T21_Lot, Why));
	return true;
}

// --- 22 + 23: in-the-road, read off the WINNING road's own frame ---------------------
STACKTOWN_PLACE_TEST(FStacktownPlaceInTheRoad, "Stacktown.Placement.InTheRoad")
{
	const FPlacementBoard Board = OracleBoard();

	const FClickResult A = ResolveClick(Board, Seed(), T22.X, T22.Y, T22.bPinsActive, V0Width);
	TestEqual(TEXT("arterial frame ok"), BoolStr(A.bOk), BoolStr(T22.bOk));
	TestEqual(TEXT("arterial frame reason"), A.Reason, FString(T22.Reason));

	// The case a blind abs(y) check could never produce, and the reason the
	// refusal has to name the winning road rather than assume the arterial.
	const FClickResult C = ResolveClick(Board, Seed(), T23.X, T23.Y, T23.bPinsActive, V0Width);
	TestEqual(TEXT("cross frame ok"), BoolStr(C.bOk), BoolStr(T23.bOk));
	TestEqual(TEXT("cross frame reason"), C.Reason, FString(T23.Reason));
	return true;
}

// --- 24: the crossing refusal is reachable through the click layer -------------------
STACKTOWN_PLACE_TEST(FStacktownPlaceCrossingClick, "Stacktown.Placement.CrossingClick")
{
	const FPlacementBoard Board = OracleBoard();
	for (int32 i = 0; i < T24CrossingNum; ++i)
	{
		const FClickCase& C = T24Crossing[i];
		const FClickResult R = ResolveClick(Board, Seed(), C.X, C.Y, C.bPinsActive, V0Width);
		TestEqual(FString::Printf(TEXT("(%.0f, %.0f) ok"), C.X, C.Y), BoolStr(R.bOk), BoolStr(C.bOk));
		TestEqual(FString::Printf(TEXT("(%.0f, %.0f) reason"), C.X, C.Y), R.Reason, FString(C.Reason));
	}
	return true;
}

// --- 25: lot_road_id's backward-compatible default ------------------------------------
STACKTOWN_PLACE_TEST(FStacktownLotRoadId, "Stacktown.Placement.LotRoadId")
{
	for (int32 i = 0; i < T25Num; ++i)
	{
		const FLotPlacement L = LotFrom(T25_Lots[i]);
		TestEqual(FString::Printf(TEXT("case %d"), i), LotRoadId(L), FString(T25_Expected[i]));
	}
	return true;
}

// --- 26: survives a restart, legacy lot included ---------------------------------------
STACKTOWN_PLACE_TEST(FStacktownPlaceRoundTrip, "Stacktown.Placement.RoundTrip")
{
	const FPlacementBoard Board = OracleBoard();
	FCityState S = Seed();

	FParcelState P1 = PlacedParcel(Board, T26_P1_Lot);
	P1.Tier = T26_P1_Tier;
	P1.bOwned = T26_P1_Owned;
	P1.Accum = T26_P1_Accum;
	S.Parcels.Add(TEXT("P1"), P1);

	FParcelState P2 = PlacedParcel(Board, T26_P2_Lot);   // legacy: no road_id key
	P2.Accum = T26_P2_Accum;
	S.Parcels.Add(TEXT("P2"), P2);

	FCityState Back;
	FString Err;
	TestTrue(TEXT("round trip parses"), CityStateFromJson(CityStateToJson(S), Back, Err));

	const FLotPlacement& L1 = Back.Parcels[TEXT("P1")].Placement.GetValue();
	TestEqual(TEXT("P1 road_id survived"), LotRoadId(L1), FString(T26_P1_RoadId));
	TestEqual(TEXT("P1 tier survived"), Back.Parcels[TEXT("P1")].Tier, T26_P1_Tier);
	TestEqual(TEXT("P1 owned survived"), BoolStr(Back.Parcels[TEXT("P1")].bOwned), BoolStr(T26_P1_Owned));

	// THE LEGACY LOT. Its road_id key must still be ABSENT after the round trip,
	// not filled in with the default. A writer that helpfully materialised
	// "arterial" here would silently rewrite the owner's real save on first load.
	const FLotPlacement& L2 = Back.Parcels[TEXT("P2")].Placement.GetValue();
	TestEqual(TEXT("P2 road_id key still absent"),
		BoolStr(L2.RoadId.IsSet()), BoolStr(T26_P2_HasRoadIdKey));
	TestEqual(TEXT("P2 still reads as arterial"), LotRoadId(L2), FString(T26_P2_RoadId));

	FString Why;
	const bool bSame = StatesEqual(S, Back, 1e-9, Why);
	TestTrue(FString::Printf(TEXT("whole state round-trips (%s)"), *Why), bSame);
	return true;
}

// --- 27: THE CORNER ---------------------------------------------------------------------
STACKTOWN_PLACE_TEST(FStacktownPlaceCorner, "Stacktown.Placement.Corner")
{
	const FPlacementBoard Board = OracleBoard();

	// An arterial lot and a cross-street lot share ground at a corner while
	// their spans live on different axes, so a per-road span scan never compared
	// them and the owner placed a lot onto a standing building. Both directions.
	{
		FCityState S = Seed();
		S.Parcels.Add(TEXT("A"), PlacedParcel(Board, T27_Lot0));
		const FClickResult R = ResolveClick(Board, S, T27Cross.X, T27Cross.Y,
			T27Cross.bPinsActive, V0Width);
		TestEqual(TEXT("cross click ok"), BoolStr(R.bOk), BoolStr(T27Cross.bOk));
		TestEqual(TEXT("cross click reason"), R.Reason, FString(T27Cross.Reason));
	}
	{
		FCityState S = Seed();
		S.Parcels.Add(TEXT("C"), PlacedParcel(Board, T27_Lot1));
		const FClickResult R = ResolveClick(Board, S, T27Arterial.X, T27Arterial.Y,
			T27Arterial.bPinsActive, V0Width);
		TestEqual(TEXT("arterial click ok"), BoolStr(R.bOk), BoolStr(T27Arterial.bOk));
		TestEqual(TEXT("arterial click reason"), R.Reason, FString(T27Arterial.Reason));
	}
	// The world footprints those refusals are computed from.
	const FRoad* Arterial = FindRoad(Board.Roads, TEXT("arterial"));
	const FRoad* Cross    = FindRoad(Board.Roads, TEXT("cross"));
	TestNotNull(TEXT("arterial exists"), Arterial);
	TestNotNull(TEXT("cross exists"), Cross);
	if (Arterial != nullptr && Cross != nullptr)
	{
		const FLotRect R0 = LotRect(Board.Rules, *Arterial, LotFrom(T27_Lot0));
		TestEqual(TEXT("arterial lot xmin"), R0.XMin, T27_Rect0.XMin, 1e-9);
		TestEqual(TEXT("arterial lot xmax"), R0.XMax, T27_Rect0.XMax, 1e-9);
		TestEqual(TEXT("arterial lot ymin"), R0.YMin, T27_Rect0.YMin, 1e-9);
		TestEqual(TEXT("arterial lot ymax"), R0.YMax, T27_Rect0.YMax, 1e-9);

		const FLotRect R1 = LotRect(Board.Rules, *Cross, LotFrom(T27_Lot1));
		TestEqual(TEXT("cross lot xmin"), R1.XMin, T27_Rect1.XMin, 1e-9);
		TestEqual(TEXT("cross lot xmax"), R1.XMax, T27_Rect1.XMax, 1e-9);
		TestEqual(TEXT("cross lot ymin"), R1.YMin, T27_Rect1.YMin, 1e-9);
		TestEqual(TEXT("cross lot ymax"), R1.YMax, T27_Rect1.YMax, 1e-9);
	}
	return true;
}

// --- ADDED BY THE PORT, not one of the 27 -----------------------------------------
// The snap grid. Every click coordinate in the Python's own 27 already lands on
// the 10 uu grid, so a port that TRUNCATED instead of rounding passed all of
// them - the mutation proving that survived until this test existed. Python's
// round() is half-to-EVEN, and the snap is what fixes lot spans in JSON, so the
// tie-breaking rule is part of the contract.
STACKTOWN_PLACE_TEST(FStacktownPlaceSnap, "Stacktown.Placement.Snap")
{
	const FPlacementBoard Board = OracleBoard();
	for (int32 i = 0; i < SnapCasesNum; ++i)
	{
		const FSnapCase& C = SnapCases[i];
		TestEqual(FString::Printf(TEXT("snap(%.1f)"), C.In),
			Snap(Board.Rules, C.In), C.Expected, 1e-9);
	}
	// The same rule reached through a real click, not just the helper.
	FString Why;
	const FClickResult A = ResolveClick(Board, Seed(), SnapClick.X, SnapClick.Y,
		SnapClick.bPinsActive, V0Width);
	TestEqual(TEXT("off-grid click ok"), BoolStr(A.bOk), BoolStr(SnapClick.bOk));
	TestTrue(FString::Printf(TEXT("off-grid click lot (%s)"), *Why),
		LotMatches(A.Lot, SnapClick.Lot, Why));
	const FClickResult B = ResolveClick(Board, Seed(), SnapClickHalf.X, SnapClickHalf.Y,
		SnapClickHalf.bPinsActive, V0Width);
	TestEqual(TEXT("half-case click ok"), BoolStr(B.bOk), BoolStr(SnapClickHalf.bOk));
	TestTrue(FString::Printf(TEXT("half-case click lot (%s)"), *Why),
		LotMatches(B.Lot, SnapClickHalf.Lot, Why));
	return true;
}

// --- ADDED BY THE PORT, not one of the 27 -----------------------------------------
// OVERLAP-SCAN DETERMINISM. The coordinator asked for a test that would catch an
// unsorted walk. In Tick() no such test can exist: rent is
// RentPerTier * (tier + 1) * Demand, the tier spread is at most 7x, every value
// is exactly representable, and all 5040 orderings of the seven possible rents
// sum to exactly 21.0 - checked, not assumed. Tick()'s sort is defensive, and
// saying a test proves it would be false.
//
// The overlap scan IS observable. When two existing lots both overlap a click,
// whichever is visited first is the one the refusal names. UE's TMap iterates in
// INSERTION order, so an unsorted walk names whichever lot happened to be added
// first; this port sorts, so it always names the same one. Deliberate divergence
// from the Python, which walks insertion order: a refusal that changes between
// runs is one nobody can act on.
STACKTOWN_PLACE_TEST(FStacktownPlaceOverlapOrder, "Stacktown.Placement.OverlapOrder")
{
	const FPlacementBoard Board = OracleBoard();
	FCityState S = Seed();
	// Inserted B FIRST, so insertion order and sorted order disagree.
	S.Parcels.Add(TEXT("B"), PlacedParcel(Board, OverlapLotB));
	S.Parcels.Add(TEXT("A"), PlacedParcel(Board, OverlapLotA));

	const FClickResult R = ResolveClick(Board, S, OverlapAOnly.X, OverlapAOnly.Y,
		OverlapAOnly.bPinsActive, V0Width);
	TestEqual(TEXT("refused"), BoolStr(R.bOk), BoolStr(OverlapAOnly.bOk));
	// A sorts before B, so A is named - even though B was added first. Both
	// reasons are the oracle's own, captured one lot at a time.
	TestEqual(TEXT("names the sorted-first lot"), R.Reason, FString(OverlapAOnly.Reason));
	TestNotEqual(TEXT("and not the insertion-first one"), R.Reason, FString(OverlapBOnly.Reason));
	return true;
}

#undef STACKTOWN_PLACE_TEST

#endif // WITH_DEV_AUTOMATION_TESTS
