// The seventeen econrules.py known-answer tests, ported (Phase 1 step 1).
//
// Run headless:
//   UnrealEditor-Cmd <uproject> -ExecCmds="Automation RunTests Stacktown.Economy; Quit" \
//     -unattended -nopause -nullrhi -log
//
// Each test below names the Python assertion group it carries across. The
// expected values are NOT transcribed from the Python's comments: they come from
// EconOracleFixture.inl, generated by running econrules.py itself. A hand-typed
// expectation is the "check that asks the wrong question and returns ok" shape
// that HANDOFF section 5 files as this project's most expensive category, and a
// porter copying numbers out of comments is exactly how one gets written.

#include "Misc/AutomationTest.h"
#include "StacktownEconomyTestCommon.h"

#if WITH_DEV_AUTOMATION_TESTS

using namespace Stacktown;
using namespace StacktownTest;

#define STACKTOWN_ECON_TEST(TestClass, PrettyName) \
	IMPLEMENT_SIMPLE_AUTOMATION_TEST(TestClass, PrettyName, \
		EAutomationTestFlags::EditorContext | EAutomationTestFlags::ProductFilter) \
	bool TestClass::RunTest(const FString& Parameters)

// --- 1: price ------------------------------------------------------------------
STACKTOWN_ECON_TEST(FStacktownEconPrice, "Stacktown.Economy.Price")
{
	const FEconRules R = OracleRules();
	for (const StacktownOracle::FTierWidthCase& C : StacktownOracle::PriceCases)
	{
		TestEqual(FString::Printf(TEXT("price(t%d, w%.0f)"), C.Tier, C.Width),
			Price(R, C.Tier, C.Width), C.Expected, Tol);
	}
	return true;
}

// --- 2: rent -------------------------------------------------------------------
STACKTOWN_ECON_TEST(FStacktownEconRent, "Stacktown.Economy.Rent")
{
	const FEconRules R = OracleRules();
	for (const StacktownOracle::FTierDemandCase& C : StacktownOracle::RentCases)
	{
		TestEqual(FString::Printf(TEXT("rent(t%d, demand %.2f)"), C.Tier, C.Demand),
			Rent(R, C.Tier, C.Demand), C.Expected, Tol);
	}
	return true;
}

// --- 3: buy, then ten ticks ----------------------------------------------------
STACKTOWN_ECON_TEST(FStacktownEconBuyThenTick, "Stacktown.Economy.BuyThenTick")
{
	const FEconRules R = OracleRules();
	FCityState S = CityWith(TEXT("P1"), Parcel(TEXT("vernacular"), 0, 1230.0), 100.0);

	const FVerbResult Bought = Buy(R, S, TEXT("P1"));
	TestTrue(TEXT("buy succeeded"), Bought.bOk);
	TestEqual(TEXT("money after buy"), S.Money, StacktownOracle::BuyThenTick10_AfterBuyMoney, Tol);

	int32 EventCount = 0;
	TArray<FEconEvent> Events;
	for (int32 i = 0; i < 10; ++i)
	{
		Tick(R, S, Events);
		EventCount += Events.Num();
	}
	TestEqual(TEXT("money after 10 ticks"), S.Money, StacktownOracle::BuyThenTick10_Money, Tol);
	TestEqual(TEXT("accum after 10 ticks"), S.Parcels[TEXT("P1")].Accum,
		StacktownOracle::BuyThenTick10_Accum, Tol);
	TestEqual(TEXT("tier never moved"), S.Parcels[TEXT("P1")].Tier, StacktownOracle::BuyThenTick10_Tier);
	TestEqual(TEXT("no events across 10 ticks"), EventCount, StacktownOracle::BuyThenTick10_Events);
	return true;
}

// --- 4 + 5: per-recipe ladders, and a blocked tier-up naming the missing mesh ---
STACKTOWN_ECON_TEST(FStacktownEconLadder, "Stacktown.Economy.Ladder")
{
	const TSharedRef<FStaticCatalogue> Cat = OracleCatalogue();
	for (const StacktownOracle::FLadderCase& C : StacktownOracle::LadderCases)
	{
		const FVerbResult Got = TierUpAllowed(*Cat, C.Rid, C.Tier, C.Width);
		TestEqual(FString::Printf(TEXT("tier_up_allowed(%s, t%d).ok"), C.Rid, C.Tier),
			BoolStr(Got.bOk), BoolStr(C.bOk));
		// The exact string, not a substring. The Python asserts on fragments
		// ('top of ladder' in why); a fragment match would pass on a reason that
		// had lost the recipe name or the tier count, which is precisely the
		// information the refusal exists to carry.
		TestEqual(FString::Printf(TEXT("tier_up_allowed(%s, t%d).reason"), C.Rid, C.Tier),
			Got.Reason, FString(C.Reason));
	}
	return true;
}

// The asset-name grammar the blocked-growth reason quotes. SM_Bld_<rid>_t<n>_w<w>.
STACKTOWN_ECON_TEST(FStacktownEconAssetName, "Stacktown.Economy.AssetName")
{
	const TSharedRef<FStaticCatalogue> Cat = OracleCatalogue();
	TestEqual(TEXT("office t0 w2050"), Cat->AssetName(TEXT("office"), 0, 2050.0),
		FString(StacktownOracle::AssetName_office_t0_w2050));
	TestEqual(TEXT("office t1 w2050"), Cat->AssetName(TEXT("office"), 1, 2050.0),
		FString(StacktownOracle::AssetName_office_t1_w2050));
	TestEqual(TEXT("vernacular t0 w1230"), Cat->AssetName(TEXT("vernacular"), 0, 1230.0),
		FString(StacktownOracle::AssetName_vernacular_t0_w1230));
	TestEqual(TEXT("office t0 is baked"), BoolStr(Cat->AssetExists(TEXT("office"), 0, 2050.0)),
		BoolStr(StacktownOracle::AssetExists_office_t0_w2050));
	TestEqual(TEXT("office t1 is not baked"), BoolStr(Cat->AssetExists(TEXT("office"), 1, 2050.0)),
		BoolStr(StacktownOracle::AssetExists_office_t1_w2050));
	return true;
}

// --- 6: the retired growth branch, at the case that used to fire loudest -------
STACKTOWN_ECON_TEST(FStacktownEconGrowthRetired, "Stacktown.Economy.GrowthRetired")
{
	const FEconRules R = OracleRules();
	// Accum past the retired threshold AND the next tier unbaked: the exact
	// state that used to emit GROWTH_BLOCKED. One tick must now do nothing but
	// accrue rent.
	FCityState S = CityWith(TEXT("OF"), Parcel(TEXT("office"), 0, 2050.0, true, 39.9), 0.0);
	TArray<FEconEvent> Events;
	Tick(R, S, Events);
	TestEqual(TEXT("money"), S.Money, StacktownOracle::TickRetired_Money, Tol);
	TestEqual(TEXT("accum"), S.Parcels[TEXT("OF")].Accum, StacktownOracle::TickRetired_Accum, Tol);
	TestEqual(TEXT("tier unchanged"), S.Parcels[TEXT("OF")].Tier, StacktownOracle::TickRetired_Tier);
	TestEqual(TEXT("no events"), Events.Num(), StacktownOracle::TickRetired_Events);
	return true;
}

// --- 7: buy refuses, by name ---------------------------------------------------
STACKTOWN_ECON_TEST(FStacktownEconBuyRefusals, "Stacktown.Economy.BuyRefusals")
{
	const FEconRules R = OracleRules();
	{
		FCityState S = CityWith(TEXT("P"), Parcel(TEXT("vernacular"), 0, 1230.0), 1.0);
		const FVerbResult Got = Buy(R, S, TEXT("P"));
		TestEqual(TEXT("insufficient.ok"), BoolStr(Got.bOk), BoolStr(StacktownOracle::Buy_insufficient_Ok));
		TestEqual(TEXT("insufficient.reason"), Got.Reason,
			FString(StacktownOracle::Buy_insufficient_Reason));
		TestEqual(TEXT("a refused buy spends nothing"), S.Money, 1.0, Tol);
		TestFalse(TEXT("a refused buy transfers nothing"), S.Parcels[TEXT("P")].bOwned);
	}
	{
		FCityState S; S.Money = 100.0;
		const FVerbResult Got = Buy(R, S, TEXT("NOPE"));
		TestEqual(TEXT("missing.ok"), BoolStr(Got.bOk), BoolStr(StacktownOracle::Buy_missing_Ok));
		TestEqual(TEXT("missing.reason"), Got.Reason, FString(StacktownOracle::Buy_missing_Reason));
	}
	{
		FCityState S = CityWith(TEXT("P"), Parcel(TEXT("vernacular"), 0, 1230.0, true), 100.0);
		const FVerbResult Got = Buy(R, S, TEXT("P"));
		TestEqual(TEXT("already.ok"), BoolStr(Got.bOk), BoolStr(StacktownOracle::Buy_already_Ok));
		TestEqual(TEXT("already.reason"), Got.Reason, FString(StacktownOracle::Buy_already_Reason));
		TestEqual(TEXT("a refused buy is not charged twice"), S.Money, 100.0, Tol);
	}
	return true;
}

// --- 8: retirement holds under volume, not just a handful of ticks -------------
STACKTOWN_ECON_TEST(FStacktownEconThousandTicks, "Stacktown.Economy.ThousandTicks")
{
	const FEconRules R = OracleRules();
	FCityState S = CityWith(TEXT("P1"), Parcel(TEXT("vernacular"), 0, 1230.0, true), 0.0);
	int32 EventCount = 0;
	TArray<FEconEvent> Events;
	for (int32 i = 0; i < 1000; ++i)
	{
		Tick(R, S, Events);
		EventCount += Events.Num();
	}
	TestEqual(TEXT("money after 1000 ticks"), S.Money, StacktownOracle::Tick1000_Money, 1e-6);
	TestEqual(TEXT("accum after 1000 ticks"), S.Parcels[TEXT("P1")].Accum,
		StacktownOracle::Tick1000_Accum, 1e-6);
	TestEqual(TEXT("tier still 0 after 1000 ticks"), S.Parcels[TEXT("P1")].Tier,
		StacktownOracle::Tick1000_Tier);
	TestEqual(TEXT("no event ever fired"), EventCount, StacktownOracle::Tick1000_Events);
	return true;
}

// --- 9: the two multipliers, directly ------------------------------------------
STACKTOWN_ECON_TEST(FStacktownEconClimbPremium, "Stacktown.Economy.ClimbAndPremium")
{
	for (const StacktownOracle::FIntCase& C : StacktownOracle::ClimbCases)
	{
		TestEqual(FString::Printf(TEXT("climb(%d)"), C.In), Climb(C.In), C.Expected);
	}
	for (const StacktownOracle::FDoubleCase& C : StacktownOracle::PremiumCases)
	{
		TestEqual(FString::Printf(TEXT("premium(%.2f)"), C.In), Premium(C.In), C.Expected, Tol);
	}
	const FEconRules R = OracleRules();
	for (const StacktownOracle::FTierPerfCase& C : StacktownOracle::UpgradePriceCases)
	{
		TestEqual(FString::Printf(TEXT("upgrade_price(t%d, perf %.2f)"), C.Tier, C.Performance),
			UpgradePrice(R, C.Tier, C.Performance), C.Expected, Tol);
	}
	for (const StacktownOracle::FIntCase& C : StacktownOracle::RepairPriceCases)
	{
		TestEqual(FString::Printf(TEXT("repair_price(t%d)"), C.In),
			RepairPrice(R, C.In), static_cast<double>(C.Expected), Tol);
	}
	return true;
}

// --- 10: upgrade pricing, and proof both multipliers actually multiply ---------
STACKTOWN_ECON_TEST(FStacktownEconUpgradePricing, "Stacktown.Economy.UpgradePricing")
{
	const FEconRules R = OracleRules();
	const TSharedRef<FStaticCatalogue> Cat = OracleCatalogue();

	FCityState S = CityWith(TEXT("P1"), Parcel(TEXT("vernacular"), 0, 1230.0, true), 100.0);
	const FVerbResult First = Upgrade(R, *Cat, S, TEXT("P1"));
	TestTrue(TEXT("first upgrade succeeds"), First.bOk);
	TestEqual(TEXT("money after first upgrade"), S.Money, StacktownOracle::UpgradeHappy_Money, Tol);
	TestEqual(TEXT("tier after first upgrade"), S.Parcels[TEXT("P1")].Tier,
		StacktownOracle::UpgradeHappy_Tier);

	// CLIMB MULTIPLIES. The same lot at tier 1 costs twice its first upgrade, so
	// the 50 left over is not enough. A flat re-use of the tier-0 price would
	// have wrongly succeeded here - that is what this asserts, not merely that
	// something was refused.
	const FVerbResult Second = Upgrade(R, *Cat, S, TEXT("P1"));
	TestEqual(TEXT("climbed price refuses.ok"), BoolStr(Second.bOk),
		BoolStr(StacktownOracle::Upgrade_CLIMB_REFUSES_Ok));
	TestEqual(TEXT("climbed price refuses.reason"), Second.Reason,
		FString(StacktownOracle::Upgrade_CLIMB_REFUSES_Reason));

	// PREMIUM MULTIPLIES. A fresh tier-0 lot at the worst performance costs
	// exactly double, which 100 can just afford - to the penny.
	FCityState W = CityWith(TEXT("P2"),
		Parcel(TEXT("vernacular"), 0, 1230.0, true, 0.0, false, -1.0), 100.0);
	const FVerbResult Worst = Upgrade(R, *Cat, W, TEXT("P2"));
	TestTrue(TEXT("worst performance still affords double"), Worst.bOk);
	TestEqual(TEXT("money after"), W.Money, StacktownOracle::UpgradeWorst_Money, Tol);
	TestEqual(TEXT("tier after"), W.Parcels[TEXT("P2")].Tier, StacktownOracle::UpgradeWorst_Tier);
	return true;
}

// --- 11: every upgrade refusal, and performance never being one of them --------
STACKTOWN_ECON_TEST(FStacktownEconUpgradeRefusals, "Stacktown.Economy.UpgradeRefusals")
{
	const FEconRules R = OracleRules();
	const TSharedRef<FStaticCatalogue> Cat = OracleCatalogue();

	FCityState S;
	S.Money = 1000.0;
	S.Demand = 1.0;
	S.Parcels.Add(TEXT("UNOWNED"), Parcel(TEXT("vernacular"), 0, 1230.0));
	S.Parcels.Add(TEXT("FAILED"),  Parcel(TEXT("vernacular"), 0, 1230.0, true, 0.0, true));
	S.Parcels.Add(TEXT("TOPPED"),  Parcel(TEXT("office"), 3, 2050.0, true));
	S.Parcels.Add(TEXT("UNBAKED"), Parcel(TEXT("office"), 0, 2050.0, true));
	S.Parcels.Add(TEXT("WORST"),   Parcel(TEXT("vernacular"), 0, 1230.0, true, 0.0, false, -1.0));

	struct FRefusal { const TCHAR* Pid; bool bOk; const TCHAR* Reason; };
	const FRefusal Refusals[] = {
		{ TEXT("UNOWNED"), StacktownOracle::Upgrade_UNOWNED_Ok, StacktownOracle::Upgrade_UNOWNED_Reason },
		{ TEXT("FAILED"),  StacktownOracle::Upgrade_FAILED_Ok,  StacktownOracle::Upgrade_FAILED_Reason  },
		{ TEXT("TOPPED"),  StacktownOracle::Upgrade_TOPPED_Ok,  StacktownOracle::Upgrade_TOPPED_Reason  },
		{ TEXT("UNBAKED"), StacktownOracle::Upgrade_UNBAKED_Ok, StacktownOracle::Upgrade_UNBAKED_Reason },
		{ TEXT("NOPE"),    StacktownOracle::Upgrade_NOPE_Ok,    StacktownOracle::Upgrade_NOPE_Reason    },
	};
	for (const FRefusal& Case : Refusals)
	{
		const double MoneyBefore = S.Money;
		const FVerbResult Got = Upgrade(R, *Cat, S, Case.Pid);
		TestEqual(FString::Printf(TEXT("upgrade(%s).ok"), Case.Pid), BoolStr(Got.bOk), BoolStr(Case.bOk));
		TestEqual(FString::Printf(TEXT("upgrade(%s).reason"), Case.Pid), Got.Reason, FString(Case.Reason));
		TestEqual(FString::Printf(TEXT("upgrade(%s) charged nothing"), Case.Pid),
			S.Money, MoneyBefore, Tol);
	}

	// Ruling (3) in one assertion: the WORST possible performance, with money to
	// spare, still upgrades. Performance surcharges; it never gates.
	const FVerbResult Worst = Upgrade(R, *Cat, S, TEXT("WORST"));
	TestEqual(TEXT("worst performance does not block"), BoolStr(Worst.bOk), BoolStr(StacktownOracle::Upgrade_WORST_Ok));
	TestEqual(TEXT("worst performance tier climbed"), S.Parcels[TEXT("WORST")].Tier, 1);
	return true;
}

// --- 12 + 13: repair ------------------------------------------------------------
STACKTOWN_ECON_TEST(FStacktownEconRepair, "Stacktown.Economy.Repair")
{
	const FEconRules R = OracleRules();

	FCityState S = CityWith(TEXT("P1"),
		Parcel(TEXT("vernacular"), 1, 1230.0, true, 0.0, true), 150.0);
	const FVerbResult Got = Repair(R, S, TEXT("P1"));
	TestTrue(TEXT("repair succeeded"), Got.bOk);
	TestEqual(TEXT("money after repair"), S.Money, StacktownOracle::RepairHappy_Money, Tol);
	TestEqual(TEXT("failed cleared"), BoolStr(S.Parcels[TEXT("P1")].bFailed), BoolStr(StacktownOracle::RepairHappy_Failed));
	return true;
}

STACKTOWN_ECON_TEST(FStacktownEconRepairRefusals, "Stacktown.Economy.RepairRefusals")
{
	const FEconRules R = OracleRules();
	FCityState S;
	S.Money = 1.0;
	S.Demand = 1.0;
	S.Parcels.Add(TEXT("UNOWNED"), Parcel(TEXT("vernacular"), 0, 1230.0));
	S.Parcels.Add(TEXT("FINE"),    Parcel(TEXT("vernacular"), 0, 1230.0, true));
	S.Parcels.Add(TEXT("POOR"),    Parcel(TEXT("vernacular"), 0, 1230.0, true, 0.0, true));

	struct FRefusal { const TCHAR* Pid; bool bOk; const TCHAR* Reason; };
	const FRefusal Refusals[] = {
		{ TEXT("UNOWNED"), StacktownOracle::Repair_UNOWNED_Ok, StacktownOracle::Repair_UNOWNED_Reason },
		{ TEXT("FINE"),    StacktownOracle::Repair_FINE_Ok,    StacktownOracle::Repair_FINE_Reason    },
		{ TEXT("POOR"),    StacktownOracle::Repair_POOR_Ok,    StacktownOracle::Repair_POOR_Reason    },
		{ TEXT("NOPE"),    StacktownOracle::Repair_NOPE_Ok,    StacktownOracle::Repair_NOPE_Reason    },
	};
	for (const FRefusal& Case : Refusals)
	{
		const FVerbResult Got = Repair(R, S, Case.Pid);
		TestEqual(FString::Printf(TEXT("repair(%s).ok"), Case.Pid), BoolStr(Got.bOk), BoolStr(Case.bOk));
		TestEqual(FString::Printf(TEXT("repair(%s).reason"), Case.Pid), Got.Reason, FString(Case.Reason));
	}
	TestEqual(TEXT("no refusal spent money"), S.Money, 1.0, Tol);
	return true;
}

// --- 14: what counts as a win ---------------------------------------------------
STACKTOWN_ECON_TEST(FStacktownEconIsWin, "Stacktown.Economy.IsWin")
{
	for (const StacktownOracle::FPnlCase& C : StacktownOracle::IsWinCases)
	{
		TestEqual(FString::Printf(TEXT("is_win(%g)"), C.Pnl), BoolStr(IsWin(C.Pnl)), BoolStr(C.bExpected));
	}
	return true;
}

// --- 15 + 16: milestone credits and per-win bonuses -----------------------------
STACKTOWN_ECON_TEST(FStacktownEconTradeArithmetic, "Stacktown.Economy.TradeArithmetic")
{
	for (const StacktownOracle::FCountRewardCase& C : StacktownOracle::CountRewardCases)
	{
		TestEqual(FString::Printf(TEXT("trade_count_reward(%d, +%d)"), C.Before, C.New),
			TradeCountReward(C.Before, C.New, C.PerN, C.Amount), C.Expected, Tol);
	}
	const TArray<double> Three = { 5.0, -2.0, 10.0 };
	TestEqual(TEXT("bonus over 2 wins of 3"), TradeOutcomeBonus(Three, 5.0), 10.0, Tol);
	TestEqual(TEXT("bonus over nothing"), TradeOutcomeBonus(TArray<double>(), 5.0), 0.0, Tol);
	return true;
}

// --- 17: the ledger, and its idempotency ----------------------------------------
STACKTOWN_ECON_TEST(FStacktownEconTradeLedger, "Stacktown.Economy.TradeLedger")
{
	const FEconRules R = OracleRules();

	TArray<double> Ledger;
	Ledger.Append(StacktownOracle::LedgerPnls, StacktownOracle::LedgerPnlsNum);

	FCityState S;
	TArray<FEconEvent> Events;
	ApplyTradeLedger(R, S, Ledger, Events);
	TestEqual(TEXT("money"), S.Money, StacktownOracle::Ledger_Money, Tol);
	TestEqual(TEXT("trades_processed"), S.TradesProcessed, StacktownOracle::Ledger_Processed);
	TestEqual(TEXT("event count"), Events.Num(), StacktownOracle::LedgerEvents_First_Num);
	if (Events.Num() == 2)
	{
		// Credits first, then bonus - the Python's append order, asserted as an
		// order and not a set, because one of the cases below asserts a
		// single-element list exactly.
		TestEqual(TEXT("event 0 is credits"), BoolStr(Events[0].Type == EEconEventType::TradeCredits), BoolStr(true));
		TestEqual(TEXT("event 0 amount"), Events[0].Amount, StacktownOracle::LedgerEvents_First_0_Amount, Tol);
		TestEqual(TEXT("event 1 is bonus"), BoolStr(Events[1].Type == EEconEventType::TradeBonus), BoolStr(true));
		TestEqual(TEXT("event 1 amount"), Events[1].Amount, StacktownOracle::LedgerEvents_First_1_Amount, Tol);
	}

	// IDEMPOTENT: the same ledger again is a true no-op, not merely "it worked
	// once". This is what survives a session restart.
	const FCityState Before = S;
	TArray<FEconEvent> Replay;
	ApplyTradeLedger(R, S, Ledger, Replay);
	TestEqual(TEXT("replay changed no money"), S.Money, Before.Money, Tol);
	TestEqual(TEXT("replay changed no count"), S.TradesProcessed, Before.TradesProcessed);
	TestEqual(TEXT("replay emitted nothing"), Replay.Num(), StacktownOracle::LedgerEvents_Replay_Num);

	// A LONGER ledger: only the new entries are read. Three more trades, two
	// wins, and 12->15 does not cross the next multiple of ten, so the bonus
	// lands and no credits do.
	TArray<double> Longer;
	Longer.Append(StacktownOracle::LedgerPnlsLonger, StacktownOracle::LedgerPnlsLongerNum);
	TArray<FEconEvent> LongerEvents;
	ApplyTradeLedger(R, S, Longer, LongerEvents);
	TestEqual(TEXT("money after longer ledger"), S.Money, StacktownOracle::LedgerLonger_Money, Tol);
	TestEqual(TEXT("count after longer ledger"), S.TradesProcessed, StacktownOracle::LedgerLonger_Processed);
	TestEqual(TEXT("longer ledger event count"), LongerEvents.Num(), StacktownOracle::LedgerEvents_Longer_Num);
	if (LongerEvents.Num() == 1)
	{
		TestEqual(TEXT("the one event is a bonus"),
			BoolStr(LongerEvents[0].Type == EEconEventType::TradeBonus), BoolStr(true));
		TestEqual(TEXT("its amount"), LongerEvents[0].Amount,
			StacktownOracle::LedgerEvents_Longer_0_Amount, Tol);
	}
	return true;
}

// --- ADDED BY THE PORT, not one of the seventeen --------------------------------
// The Python ticks a single parcel. C++ has a hazard the Python does not: TMap
// iteration order is unspecified, and floating-point addition is not
// associative, so summing rent in hash order makes Money depend on how the map
// happened to bucket. The Python walks sorted(parcels.items()); Tick() sorts to
// match. This is the test that would catch that sort being removed.
STACKTOWN_ECON_TEST(FStacktownEconMultiParcelOrder, "Stacktown.Economy.MultiParcelOrder")
{
	const FEconRules R = OracleRules();
	FCityState S;
	S.Money = 0.0;
	S.Demand = StacktownOracle::TickMulti_Demand;
	S.Parcels.Add(TEXT("C"), Parcel(TEXT("vernacular"), 2, 1230.0, true));
	S.Parcels.Add(TEXT("A"), Parcel(TEXT("vernacular"), 0, 1230.0, true));
	S.Parcels.Add(TEXT("B"), Parcel(TEXT("office"), 1, 2050.0, false));

	TArray<FEconEvent> Events;
	Tick(R, S, Events);
	TestEqual(TEXT("summed money"), S.Money, StacktownOracle::TickMulti_Money, Tol);
	TestEqual(TEXT("A accrued"), S.Parcels[TEXT("A")].Accum, StacktownOracle::TickMulti_Accum_A, Tol);
	TestEqual(TEXT("C accrued"), S.Parcels[TEXT("C")].Accum, StacktownOracle::TickMulti_Accum_C, Tol);
	TestEqual(TEXT("an unowned parcel accrues nothing"),
		S.Parcels[TEXT("B")].Accum, StacktownOracle::TickMulti_Accum_B, Tol);
	return true;
}

#undef STACKTOWN_ECON_TEST

#endif // WITH_DEV_AUTOMATION_TESTS
