// GENERATED by Tools/oracle/gen_board_data.py from Content/Python/citylayout.py.
// DO NOT HAND-EDIT - regenerate. This is PRODUCTION data: the board the live
// game stands on. Cross-checked at generation time against
// placement.PINNED_SPANS, so the board the game uses is the board the ported
// refusal logic was tested against.
//
//   python3 Tools/oracle/gen_board_data.py
#pragma once

namespace Stacktown
{
namespace BoardData
{
struct FRoadRow { const TCHAR* Id; double StartX; double StartY; double EndX;
                  double EndY; const TCHAR* SidePlus; const TCHAR* SideMinus; bool bAxisX; };
struct FPinRow  { const TCHAR* Key; double X0; double X1; const TCHAR* Side; };

inline const FRoadRow Roads[] = {
	{ TEXT("arterial"), -7650.0, 0.0, 7650.0, 0.0, TEXT("north"), TEXT("south"), true },
	{ TEXT("cross"), 0.0, -4230.0, 0.0, 4230.0, TEXT("west"), TEXT("east"), false },
};
inline constexpr int32 RoadsNum = 2;

// The fourteen pinned lots, WITH their citylayout keys - the keys are what
// lets a pinned parcel find its own span and therefore its pose.
inline const FPinRow PinnedSpans[] = {
	{ TEXT("NE0"), 1130.0, 3590.0, TEXT("north") },
	{ TEXT("NE1"), 3590.0, 4410.0, TEXT("north") },
	{ TEXT("NE2"), 4410.0, 6050.0, TEXT("north") },
	{ TEXT("NW0"), -6050.0, -4820.0, TEXT("north") },
	{ TEXT("NW1"), -4820.0, -3590.0, TEXT("north") },
	{ TEXT("NW2"), -3590.0, -2360.0, TEXT("north") },
	{ TEXT("NW3"), -2360.0, -1130.0, TEXT("north") },
	{ TEXT("SE0"), 1130.0, 3180.0, TEXT("south") },
	{ TEXT("SE1"), 3180.0, 4820.0, TEXT("south") },
	{ TEXT("SE2"), 4820.0, 6050.0, TEXT("south") },
	{ TEXT("SW0"), -6050.0, -4820.0, TEXT("south") },
	{ TEXT("SW1"), -4820.0, -4000.0, TEXT("south") },
	{ TEXT("SW2"), -4000.0, -2770.0, TEXT("south") },
	{ TEXT("SW3"), -2770.0, -1130.0, TEXT("south") },
};
inline constexpr int32 PinnedSpansNum = 14;

inline constexpr double PlateXMin = -7650.0;
inline constexpr double PlateXMax = 7650.0;
inline constexpr double PlateYMin = -4230.0;
inline constexpr double PlateYMax = 4230.0;
inline constexpr double PositionQuantum = 10.0;
inline constexpr double V0Width = 820.0;
inline constexpr double RoadHalf = 1130.0;
inline constexpr double BlockDepth = 1500.0;
inline constexpr double RoadMaxReach = 3230.0;
inline constexpr int32 PoolSize = 30;
inline const TCHAR* const V0Recipe = TEXT("vernacular");

} // namespace BoardData
} // namespace Stacktown
